import{Bot,CheckCircle2,Clock3,Layers3,Network,Search,ShieldCheck,Sparkles,Target,Users,Wand2}from'lucide-react';
import type{PageProps}from'../types';
import{AssetCard,Bars,Metric,Panel,Progress,StatusGrid}from'./common';

const playable=(a:any)=>a?.playable_url||a?.source_url||a?.url;
const asset=(p:PageProps,keys:string[])=>playable(p.assetForName?.(keys));

export function HomePage(p:PageProps){
 const active=p.data.projects.filter((x:any)=>!['complete','failed','archived'].includes(x.status)).length;
 const complete=p.data.generations.filter((x:any)=>x.status==='complete').length;
 const success=p.data.generations.length?Math.round(complete/p.data.generations.length*100):0;
 if(p.view==='V2')return <><div className="vw-split"><Panel title="Studio Overview" className="vw-tall"><StatusGrid items={[['Projects',String(p.data.projects.length),'live'],['Active',String(active),'in motion'],['Generations',String(p.data.generations.length),'recorded'],['Success',success?success+'%':'—','truthful'] ]}/><Bars items={p.data.projects.slice(0,5).map((x:any,i:number)=>[x.title.slice(0,20),[78,63,49,84,36][i]||50,x.status])}/></Panel><Panel title="Today"><div className="vw-stack">{p.data.projects.slice(0,5).map((x:any)=><button className="vw-list-row" key={x.id}><div><b>{x.title}</b><small>{x.medium||x.universe||'Project'}</small></div><span>{x.status}</span></button>)}</div></Panel></div></>;
 if(p.view==='V3')return <><Panel title="Project Focus"><div className="vw-focus"><AssetCard title="Crossroads of Identity" subtitle="Production focus" url={asset(p,['crossroads'])}/><AssetCard title="Children’s Series" subtitle="Series pipeline" url={asset(p,['children','school'])}/><AssetCard title="True Stories" subtitle="Narrative development" url={asset(p,['true stories','evelyn'])}/></div></Panel><Panel title="System pulse"><StatusGrid items={[['Avatar State','Active'],['Continuity','Gated'],['World State','Next'],['THELMA','Ready']]}/></Panel></>;
 return <><section className="vw-hero home"><div className="vw-hero-copy"><span>YOUR CREATIVE OPERATING SYSTEM</span><h2>Bring Your Ideas to Life</h2><p>From story and characters to places, production, finishing and distribution—everything stays connected.</p><button onClick={()=>p.open('vision-builder')}>Start Creating</button></div><div className="vw-hero-grid">{[
   ['Crossroads of Identity',['crossroads']],['Children’s Series',['children','school']],['Commercials',['commercial','pepsi']],['True Stories',['true stories','evelyn']]
  ].map(([t,k]:any)=><AssetCard key={t} title={t} url={asset(p,k)} subtitle="Open project"/>)}</div></section>
  <div className="vw-metrics"><Metric label="Active Projects" value={active}/><Metric label="Scene Generated" value={complete}/><Metric label="Minutes Created" value="—" delta="not yet metered"/><Metric label="Success Rate" value={success?success+'%':'—'} delta="completed generations"/></div>
  <Panel title="Recent Projects" action="View all"><div className="vw-card-grid four">{p.data.projects.slice(0,4).map((x:any)=><AssetCard key={x.id} title={x.title} subtitle={[x.medium,x.status].filter(Boolean).join(' · ')} url={playable(p.data.assets.find((a:any)=>a?.metadata?.project_id===x.id))}/>)}</div></Panel></>;
}

export function VisionBuilderPage(p:PageProps){
 if(p.view==='V2')return <><Panel title="Blueprint & Dependencies"><div className="vw-flow-row">{['Intent','Audience','Avatar State','World State','Story','Production','QC','Distribution'].map((x,i)=><div className="vw-flow-node" key={x}><span>{String(i+1).padStart(2,'0')}</span><b>{x}</b></div>)}</div></Panel><Panel title="Locked prerequisites"><StatusGrid items={[['Avatar identity','Exact version'],['World state','Persistent'],['Acceptance','Defined'],['Provider route','Truthful']]}/></Panel></>;
 if(p.view==='V3')return <Panel title="Concept-to-Production Map"><div className="vw-map-canvas">{['Concept','Research','Design','Scene','Render','QC','Release'].map((x,i)=><div className={'vw-map-node n'+i} key={x}><Wand2/><b>{x}</b></div>)}</div></Panel>;
 return <><section className="vw-hero builder"><div className="vw-hero-copy"><span>CREATE WITHOUT LIMITS</span><h2>Create Without Limits</h2><p>Videos • Images • Books • Movies</p><div className="vw-tabs"><button className="on">Text → Video</button><button>Image Generation</button><button>Scene Composer</button><button>Story Builder</button></div></div><div className="vw-hero-feature"><AssetCard title="Active visual reference" subtitle="Exact project asset only" url={asset(p,['balloon','crossroads','children'])}/></div></section><Panel title="Recent Creations" action="View all"><div className="vw-card-grid six">{p.data.assets.slice(0,6).map((a:any,i:number)=><AssetCard key={a.id||i} title={a.name||a.kind||'Production asset'} subtitle={a.kind||'asset'} url={playable(a)}/>)}</div></Panel></>;
}

export function StrategicPlannerPage(p:PageProps){
 if(p.view==='V2')return <><Panel title="Scenario & Roadmap Studio"><div className="vw-roadmap">{[['MVP reliability',15,26],['Memory + agents',30,34],['Autonomous production',52,28],['Enterprise scale',72,24]].map(([n,l,w]:any)=><div key={n}><span>{n}</span><i><b style={{marginLeft:l+'%',width:w+'%'}}/></i></div>)}</div></Panel><Panel title="Scenario controls"><StatusGrid items={[['Base Case','Selected'],['Aggressive','Available'],['Cost Guard','On'],['Approval Gate','Architect']]}/></Panel></>;
 if(p.view==='V3')return <><Panel title="Goals, Risks & Outcomes"><div className="vw-three-col"><StatusGrid items={[['Goal','Long-form production'],['Measure','Acceptance + cost'],['Owner','Architect']]}/><StatusGrid items={[['Risk','Continuity drift'],['Risk','Provider limits'],['Risk','False connection state']]}/><StatusGrid items={[['Control','Version locks'],['Control','Evidence gate'],['Control','Fallback routing']]}/></div></Panel></>;
 return <><Panel title="Strategic Command Center" action="Q4 2026"><div className="vw-roadmap">{[['Enterprise Growth',0,34],['Product Launch',12,28],['Content Series',33,31],['Grant Applications',50,21],['Marketing Campaign',62,27],['Platform Expansion',74,20]].map(([n,l,w]:any)=><div key={n}><span>{n}</span><i><b style={{marginLeft:l+'%',width:w+'%'}}/></i></div>)}</div><div className="vw-metrics compact"><Metric label="Active Goals" value="12"/><Metric label="On Track" value="8" tone="green"/><Metric label="At Risk" value="3" tone="pink"/><Metric label="Completed" value="7"/></div></Panel></>;
}

export function InitiativesPage(p:PageProps){
 const cols=[['Ideation','New concepts'],['In Planning','Resource lock'],['In Progress','Active work'],['Review','Awaiting decision'],['Completed','Delivered']];
 if(p.view==='V1')return <><div className="vw-metrics"><Metric label="Active Initiatives" value="4"/><Metric label="Planning" value="3"/><Metric label="Blocked" value="1" tone="pink"/><Metric label="Completed" value="7" tone="green"/></div><Panel title="Initiative Overview"><div className="vw-card-grid four">{[['Avatar State',['balloon']],['World State',['world','location']],['Long-form Stitching',['video']],['Quality Gate',['quality']]].map(([t,k]:any)=><AssetCard title={t} subtitle="Foundation initiative" url={asset(p,k)} key={t}/>)}</div></Panel></>;
 if(p.view==='V3')return <><Panel title="Impact & Dependencies"><Bars items={[['VisionWeaver',90,'high'],['THELMA',82,'high'],['CEO Dashboard',58,'medium'],['CMGIO',55,'medium']]}/></Panel><Panel title="Dependency map"><div className="vw-network"><Network/><b>Initiative → System → Gate → Evidence</b></div></Panel></>;
 return <div className="vw-kanban">{cols.map(([title,sub],i)=><section key={title}><header><b>{title}</b><span>{[7,8,5,4,8][i]}</span></header><AssetCard title={'Initiative '+(i+1)} subtitle={sub} url={asset(p,[i%2?'balloon':'crossroads'])}/><AssetCard title={'Initiative '+(i+6)} subtitle={i%2?'Research':'Production'} url={asset(p,[i%2?'children':'balloon'])}/></section>)}</div>;
}

export function ProgramsPage(p:PageProps){
 const rows=p.data.projects.slice(0,8);
 if(p.view==='V1')return <><div className="vw-metrics"><Metric label="Programs" value="4"/><Metric label="Projects" value={p.data.projects.length}/><Metric label="Active" value={rows.filter((r:any)=>!['complete','failed'].includes(r.status)).length}/><Metric label="Blocked" value={rows.filter((r:any)=>r.status==='failed').length} tone="pink"/></div><Panel title="Portfolio Command"><div className="vw-card-grid four">{rows.slice(0,4).map((x:any)=><AssetCard key={x.id} title={x.title} subtitle={x.status}/>)}</div></Panel></>;
 if(p.view==='V3')return <Panel title="Timeline & Dependencies"><div className="vw-roadmap">{rows.slice(0,6).map((x:any,i:number)=><div key={x.id}><span>{x.title.slice(0,22)}</span><i><b style={{marginLeft:(i*10)+'%',width:(25+(i%3)*8)+'%'}}/></i></div>)}</div></Panel>;
 return <><div className="vw-metrics compact"><Metric label="Total Projects" value={p.data.projects.length}/><Metric label="Active" value={rows.filter((r:any)=>!['complete','failed'].includes(r.status)).length}/><Metric label="Completed" value={rows.filter((r:any)=>r.status==='complete').length} tone="green"/><Metric label="Success Rate" value={p.data.projects.length?Math.round(p.data.projects.filter((r:any)=>r.status==='complete').length/p.data.projects.length*100)+'%':'—'}/></div><Panel title="Program & Project Workspace" action="All Projects"><div className="vw-project-table">{rows.length?rows.map((x:any,i:number)=><div key={x.id}><AssetCard title={x.title} subtitle={x.medium||x.universe||'Project'} url={playable(p.data.assets.find((a:any)=>a?.metadata?.project_id===x.id))}/><Progress label="" value={[72,44,86,61,33,90,52,77][i%8]} status={x.status}/></div>):<p>No production projects yet.</p>}</div></Panel></>;
}

export function CopilotPage(p:PageProps){
 const agents=[['Research Agent','Sources · trends · citations'],['Content Agent','Scripts · copy · story'],['Video Agent','Scenes · shots · prompts'],['Compliance Agent','Rights · claims · policy'],['CMGIO Agent','Growth intelligence'],['Quality Control','Continuity · release gates']];
 if(p.view==='V1')return <><div className="vw-metrics"><Metric label="Orchestrator" value="THELMA"/><Metric label="Specialists" value="7"/><Metric label="Pending Approval" value="0"/><Metric label="Memory" value="Evidence-linked"/></div><Panel title="AI Command Center"><div className="vw-agent-grid">{agents.map(a=><article key={a[0]}><Bot/><b>{a[0]}</b><small>{a[1]}</small></article>)}</div></Panel></>;
 if(p.view==='V3')return <Panel title="Specialist Marketplace"><div className="vw-agent-grid">{[['THELMA','Orchestration'],['H.E.N.R.Y.','Architecture'],['P.E.R.C.Y.','Security'],['V.E.R.I.T.A.S.','Evidence'],['The Auditor','Quality'],['Canon Keeper','Memory']].map(a=><article key={a[0]}><Sparkles/><b>{a[0]}</b><small>{a[1]}</small><span>Available</span></article>)}</div></Panel>;
 return <><div className="vw-agent-grid">{agents.map((a,i)=><article key={a[0]}><div className="vw-agent-icon"><Bot/></div><b>{a[0]}</b><small>{a[1]}</small><footer><span>{[6,8,3,5,2,4][i]} tasks</span><em>{i%2?'Standby':'Working'}</em></footer></article>)}</div><div className="vw-chat-command"><Bot/><span>Ask the AI Co-Pilot anything…</span><button>Research</button><button>Create</button><button>Analyze</button><button>Automate</button></div></>;
}

export function CMIPage(p:PageProps){
 if(p.view==='V2')return <><Panel title="Signals & Trends"><Bars items={[['AI media creation',84,'rising'],['Short-to-long repurposing',72,'rising'],['Interactive story worlds',63,'watch'],['Synthetic sameness',78,'risk']]}/></Panel></>;
 if(p.view==='V3')return <Panel title="Opportunity Intelligence"><div className="vw-card-grid three">{['Catalog licensing','Commercial templates','Education IP'].map((x,i)=><article className="vw-opportunity" key={x}><Target/><b>{x}</b><small>{['Reusable avatars, worlds and assets','Verticalized creative systems','Repeatable production + distribution'][i]}</small></article>)}</div></Panel>;
 return <><div className="vw-two-col"><Panel title="Engagement Trends"><div className="vw-line-chart"><span/><i/><b/></div></Panel><Panel title="Audience Demographics"><div className="vw-donut"><span><b>—</b><small>Audience data</small></span></div></Panel></div><Panel title="Top Content" action="View all"><div className="vw-card-grid five">{[['Crossroads',['crossroads']],['Children’s Series',['children']],['Commercials',['commercial','pepsi']],['True Stories',['evelyn','true stories']],['World Packs',['world','location']]].map(([t,k]:any)=><AssetCard title={t} subtitle="Tracked content" url={asset(p,k)} key={t}/>)}</div></Panel></>;
}

export function GuildPage(p:PageProps){
 const items=[['Crossroads Ep.1 · Final Edit','In Review'],['Children’s Series Ep.3','Approved'],['Pepsi Zero Ad · 30s','Revision'],['True Stories Ep.2','Pending'],['Educational Short · Water Science','Pending']];
 if(p.view==='V1')return <><Panel title="Guild Overview"><StatusGrid items={[['Submissions','5'],['Approved','1'],['Revision','1'],['Pending','2']]}/></Panel></>;
 if(p.view==='V3')return <Panel title="Department Workrooms"><div className="vw-agent-grid">{['Design','Motion','Sound','Edit','Marketing','Automation'].map(x=><article key={x}><Layers3/><b>{x}</b><small>Production department</small></article>)}</div></Panel>;
 return <Panel title="Review & Decision Queue" action="All Submissions"><div className="vw-review-list">{items.map((x,i)=><div key={x[0]}><AssetCard title={x[0]} subtitle={['Director','Content Team','Commercial Unit','Narrative Team','Education Team'][i]} url={asset(p,[i===0?'crossroads':i===1?'children':i===2?'pepsi':'evelyn'])}/><span className={'vw-state s'+i}>{x[1]}</span></div>)}</div></Panel>;
}

export function TeamsPage(p:PageProps){
 if(p.view==='V2')return <Panel title="Authority & Handoff Map"><div className="vw-flow-row">{['The Architect','C-Suite','Directors Guild','THELMA','Specialists'].map((x,i)=><div className="vw-flow-node" key={x}><span>{i+1}</span><b>{x}</b></div>)}</div></Panel>;
 if(p.view==='V3')return <><Panel title="Workforce & Agent Capacity"><Bars items={[['Executive',75,'available'],['Production',62,'available'],['AI Agents',88,'available'],['Review',54,'available']]}/></Panel></>;
 const people=[['The Architect','System Owner'],['THELMA AI','Operations AI'],['CMGIO','Growth & Marketing'],['Chief Human Experience','Culture & People']];
 return <><div className="vw-team-head">{people.map((x,i)=><article key={x[0]}><div className={'vw-person p'+i}>{i===1?<Bot/>:<Users/>}</div><b>{x[0]}</b><small>{x[1]}</small></article>)}</div><Panel title="Team Directory"><table className="vw-table"><thead><tr><th>Name</th><th>Role</th><th>Department</th><th>Status</th><th>Access</th></tr></thead><tbody>{[['Creative Director','Editor','Creative'],['Sound Designer','Editor','Studio'],['AI Orchestrator','System','Production'],['Research Agent','Analyst','CMI']].map(r=><tr key={r[0]}><td>{r[0]}</td><td>{r[1]}</td><td>{r[2]}</td><td><span className="vw-live">Active</span></td><td>Owned</td></tr>)}</tbody></table></Panel></>;
}
