import{Box,Clapperboard,Film,Globe2,Layers3,Map,Mic2,Package,Palette,Play,ShoppingBag,SlidersHorizontal,Volume2,Wand2}from'lucide-react';
import type{PageProps}from'../types';
import{AssetCard,Bars,Metric,Panel,Progress,StatusGrid}from'./common';

const playable=(a:any)=>a?.playable_url||a?.source_url||a?.url;
const asset=(p:PageProps,keys:string[])=>playable(p.assetForName?.(keys));

export function BookCreationPage(p:PageProps){
 if(p.view==='V2')return <><div className="vw-two-col"><Panel title="Writing Workspace"><div className="vw-editor-mock"><header>Chapter 01 · Convergence</header><h4>Opening sequence</h4><p>Write, edit, structure and preserve canon inside the project record.</p><div className="vw-editor-lines">{Array.from({length:10}).map((_,i)=><i key={i}/>)}</div></div></Panel><Panel title="Book State"><StatusGrid items={[['Outline','Available'],['Characters','Linked'],['World','Linked'],['Canon','Versioned'],['Covers','Assets'],['Publish','Gated']]}/></Panel></div></>;
 if(p.view==='V3')return <><Panel title="Publishing Pipeline"><div className="vw-flow-row">{['Manuscript','Edit','Illustrate','Accessibility','Package','Distribute'].map((x,i)=><div className="vw-flow-node" key={x}><span>{i+1}</span><b>{x}</b></div>)}</div></Panel><Panel title="Release controls"><StatusGrid items={[['EPUB','Available'],['PDF','Available'],['Audiobook','Planned'],['Rights','Required']]}/></Panel></>;
 return <><section className="vw-book-hero"><div><span>BOOK CREATION</span><h2>From Idea to Published Book</h2><p>Story, characters, world, chapters, editing, cover assets and distribution remain connected to the same canon.</p></div><AssetCard title="Crossroads of Identity" subtitle="Book 1 · Convergence" url={asset(p,['crossroads'])}/></section><div className="vw-card-grid four">{['Story Development','Characters','World Building','Outline & Chapters','Writing Studio','Editing & QA','Covers & Assets','Publish & Distribute'].map((x,i)=><article className="vw-tool-card" key={x}><span>{String(i+1).padStart(2,'0')}</span><b>{x}</b><small>Open workspace</small></article>)}</div></>;
}

export function AvatarEngineeringPage(p:PageProps){
 const avatar=p.data.characters[0];
 const binding=p.data.avatar_bindings.find((x:any)=>x.character_id===avatar?.id)||p.data.avatar_bindings[0];
 const continuity=p.data.continuity_jobs[0];
 const capsule=p.data.continuity_capsules.find((x:any)=>x.source_generation_id===continuity?.generation_id);
 const ready=continuity?.dissection_state==='PASSED'&&continuity?.qc_state==='PASS'&&capsule?.approval_state==='LOCKED';
 if(p.view==='V1')return <><div className="vw-metrics"><Metric label="Characters" value={p.data.characters.length}/><Metric label="Active Bindings" value={p.data.avatar_bindings.filter((x:any)=>x.binding_state==='ACTIVE').length}/><Metric label="Coverage Sets" value="1"/><Metric label="QC Ready" value={ready?'Yes':'No'} tone={ready?'green':'amber'}/></div><Panel title="Avatar Overview"><div className="vw-card-grid four">{p.data.characters.slice(0,8).map((x:any)=><AssetCard key={x.id} title={x.name} subtitle={x.visual_anchor||'Character'} url={playable(p.data.assets.find((a:any)=>JSON.stringify(a.metadata||{}).includes(x.id)))}/>)}</div></Panel></>;
 if(p.view==='V3')return <><Panel title="360 Engineering"><div className="vw-coverage-grid">{['Front','3/4 Left','Left','Rear Left','Back','Rear Right','Right','3/4 Right'].map((x,i)=><AssetCard key={x} title={x} subtitle="View slot" url={asset(p,['balloon','character'])}/>)}</div></Panel><Panel title="Coverage profiles"><StatusGrid items={[['16-view','Wardrobe state'],['24-view','Study only'],['32-view','Canonical master'],['64-slot','Calibration pending']]}/></Panel></>;
 return <><section className="vw-avatar-hero"><AssetCard title={avatar?.name||'Active Avatar'} subtitle={avatar?.visual_anchor||'Locked identity'} url={asset(p,['balloon','character'])}/><div className="vw-avatar-copy"><span>AVATAR STATE STUDIO</span><h2>{avatar?.name||'No active avatar'}</h2><p>{avatar?.visual_anchor||'Select or create an avatar to begin an exact-version production state.'}</p><div className="vw-chips"><span>{binding?.binding_state||'UNBOUND'}</span><span>V2 Selected</span><span>{continuity?.qc_state||'QC PENDING'}</span></div></div><div className={'vw-readiness '+(ready?'ready':'blocked')}><b>{ready?'CONTINUITY READY':'SHOT 02 BLOCKED'}</b><small>{ready?'Locked capsule available':'Observed state + QC + locked capsule required'}</small></div></section><div className="vw-two-col"><Panel title="Avatar State"><StatusGrid items={[['Identity',binding?'Locked':'Unbound'],['Appearance',binding?'Locked':'Unbound'],['Voice',binding?'Resolved':'Unbound'],['Performance',binding?'Locked':'Unbound'],['Coverage','QC Pending'],['Cast',binding?'Assigned':'Unbound']]}/></Panel><Panel title="Continuity Gate"><StatusGrid items={[['Media',continuity?.media_access_state||'Available Private'],['Dissection',continuity?.dissection_state||'Waiting'],['QC',continuity?.qc_state||'Pending'],['Capsule',capsule?.approval_state||'Not Created']]}/></Panel></div><Panel title="Avatar Reference Coverage" action="Open 360"><div className="vw-card-grid six">{['Front','3/4 Left','Left','Back','Right','3/4 Right'].map((x,i)=><AssetCard title={x} subtitle="Exact reference" url={asset(p,['balloon','character'])} key={x}/>)}</div></Panel></>;
}

export function WorldsLocationsPage(p:PageProps){
 if(p.view==='V1')return <><Panel title="Cinematic Location Grid"><div className="vw-card-grid four">{[['Chicago',['chicago']],['Mumbai',['mumbai']],['Atlanta',['atlanta']],['Houston',['houston']],['Tampa',['tampa']],['World Pack 01',['world']],['Historical',['history']],['Rural',['rural']]].map(([x,k]:any)=><AssetCard title={x} subtitle="Location reference" url={asset(p,k)} key={x}/>)}</div></Panel></>;
 if(p.view==='V3')return <><div className="vw-two-col"><Panel title="World Builder Studio"><StatusGrid items={[['Geometry','Persistent'],['Weather','Stateful'],['Lighting','Physical'],['Audio','Directional'],['Physics','Causal'],['Provenance','Tracked']]}/><div className="vw-map-canvas world"><div className="vw-map-node n0"><Globe2/><b>World State</b></div><div className="vw-map-node n2"><Map/><b>Zones</b></div><div className="vw-map-node n4"><Volume2/><b>Acoustics</b></div></div></Panel><Panel title="Environment controls"><Bars items={[['Rain',72,'steady'],['Wind',38,'light'],['Daylight',46,'overcast'],['Crowd',8,'low']]}/></Panel></div></>;
 return <><div className="vw-map-layout"><Panel title="Interactive Map"><div className="vw-map-stage"><div className="vw-map-grid"/><span className="pin p1">Chicago</span><span className="pin p2">Atlanta</span><span className="pin p3">Tampa</span><span className="pin p4">Mumbai</span></div></Panel><div className="vw-map-side"><Panel title="World State"><StatusGrid items={[['Location Packs','Available'],['Weather','Persistent'],['Lighting','Persistent'],['Audio','Spatial'],['Physics','Enabled'],['Canon','Versioned']]}/></Panel><Panel title="Selected Location"><AssetCard title="Red Balloon World" subtitle="Wet brick sidewalk · steady rain" url={asset(p,['balloon'])}/></Panel></div></div></>;
}

export function DesignStudioPage(p:PageProps){
 if(p.view==='V1')return <><section className="vw-hero builder"><div className="vw-hero-copy"><span>DESIGN STUDIO</span><h2>Create & Build</h2><p>Avatars, environments, props, effects and reusable visual systems.</p></div><div className="vw-hero-feature"><Palette/></div></section><div className="vw-card-grid five">{['Avatars','Scenes','Props','Effects','Templates'].map((x,i)=><AssetCard key={x} title={x} subtitle="Create collection" url={asset(p,[i===0?'character':i===1?'world':'design'])}/>)}</div></>;
 if(p.view==='V3')return <><Panel title="Catalogue Builder"><div className="vw-library-layout"><aside>{['All','Avatars','Scenes','Products','Effects','Templates','Licensed'].map((x,i)=><span className={i===0?'on':''} key={x}>{x}</span>)}</aside><div className="vw-card-grid three">{['Reusable Avatar','Location Pack','Product Kit','Effect Pack','Scene Template','Brand Kit'].map((x,i)=><AssetCard key={x} title={x} subtitle="Catalogue item" url={asset(p,[i%2?'world':'character'])}/>)}</div></div></Panel></>;
 return <><div className="vw-studio-toolbar"><span className="on">Create</span><span>Catalogue</span><span>Buildout</span><button onClick={()=>p.open('avatar-engineering')}>Design Avatars</button><button onClick={()=>p.open('scene-production')}>Scenes</button><span>Effects</span><span>Store</span></div><div className="vw-two-col wide-left"><Panel title="Design Workspace"><div className="vw-design-canvas"><div className="vw-design-subject"><AssetCard title="Current Design" subtitle="Exact asset reference" url={asset(p,['character','balloon'])}/></div></div></Panel><div><Panel title="Build Controls"><StatusGrid items={[['Identity Lock','On'],['References','Exact'],['Versioning','On'],['Rights','Tracked']]}/></Panel><Panel title="Recent"><div className="vw-card-grid two"><AssetCard title="Avatar Pack" url={asset(p,['character'])}/><AssetCard title="World Pack" url={asset(p,['world','location'])}/></div></Panel></div></div></>;
}

export function DesignCommercialPage(p:PageProps){
 if(p.view==='V2')return <><div className="vw-two-col wide-left"><Panel title="Interactive Commercial Studio"><div className="vw-design-canvas ad"><AssetCard title="Hero Product" subtitle="Exact identity lock" url={asset(p,['pepsi','commercial'])}/></div></Panel><Panel title="Placement Controls"><StatusGrid items={[['Product identity','Locked'],['Brand assets','Locked'],['Claims','Source-required'],['Placement','Mapped'],['Rights','Tracked']]}/></Panel></div></>;
 if(p.view==='V3')return <><Panel title="Placement & Performance"><div className="vw-three-col"><StatusGrid items={[['Hero placement','Primary'],['Background placement','Available'],['Logo exposure','Tracked']]}/><Bars items={[['Attention',76,'modeled'],['Recall',63,'modeled'],['Clarity',88,'QC']]}/><StatusGrid items={[['Platform','Multi-format'],['Versions','Tracked'],['Approval','Required']]}/></div></Panel></>;
 return <><div className="vw-metrics compact"><Metric label="Templates" value="2,000"/><Metric label="Structures" value="40"/><Metric label="Verticals" value="25"/><Metric label="Modes" value="2"/></div><Panel title="Campaign Command Grid"><div className="vw-card-grid four">{[['Commercial Creativity',['pepsi','commercial']],['Product Design',['product']],['Product Placement',['placement']],['Placement Mapping',['map','commercial']]].map(([x,k]:any)=><AssetCard title={x} subtitle="Open station" url={asset(p,k)} key={x}/>)}</div></Panel><Panel title="Production flow"><div className="vw-flow-row">{['Brief','Concept','Script','Locks','Production','Edit/QC','Approve','Publish'].map((x,i)=><div className="vw-flow-node" key={x}><span>{i+1}</span><b>{x}</b></div>)}</div></Panel></>;
}

export function SceneProductionPage(p:PageProps){
 const current=p.data.projects.find((x:any)=>/balloon/i.test(x.title+' '+x.source_concept))||p.data.projects[0];
 if(p.view==='V2')return <><Panel title="Timeline & Continuity"><div className="vw-edit-timeline">{['Picture','Dialogue','Ambience','SFX','Music','Continuity'].map((x,i)=><div key={x}><span>{x}</span><i><b style={{left:(i*4)+'%',width:(74-i*6)+'%'}}/></i></div>)}</div></Panel><div className="vw-two-col"><Panel title="Continuity Capsule"><StatusGrid items={[['Source Shot','Shot 01'],['Ending Frame','Required'],['Motion Tail','Required'],['World State','Required'],['QC','Blocking']]}/></Panel><Panel title="Stitching"><StatusGrid items={[['Shot 01','Existing'],['Shot 02','Blocked'],['Transition','Pending'],['Long-form','Assemble']]}/></Panel></div></>;
 if(p.view==='V3')return <><Panel title="Scene Operations"><div className="vw-kanban three">{['Prepare','Render','Review'].map((x,i)=><section key={x}><header><b>{x}</b><span>{i+1}</span></header><AssetCard title={current?.title||'Scene'} subtitle={['Locked inputs','Provider job','Human decision'][i]} url={asset(p,['balloon'])}/></section>)}</div></Panel></>;
 return <><div className="vw-studio-toolbar"><span className="on">Overview</span><span>Scene Library</span><span>Shot Builder</span><button onClick={()=>p.open('production-studio')}>Production Tools</button><button onClick={()=>p.open('production-studio')}>Continuity</button><span>Live Preview</span><span>Export</span></div><div className="vw-two-col wide-left"><Panel title="Current Scene"><AssetCard title={current?.title||'Boy & Red Balloon'} subtitle="Shot 01 · exact source record" url={asset(p,['balloon'])}/></Panel><Panel title="Production Pipeline"><StatusGrid items={[['Storyboard','Complete'],['Avatar State','Locked'],['World State','In Review'],['Render','Stored'],['QC','Pending'],['Stitch','Blocked']]}/></Panel></div><Panel title="Production Tools"><div className="vw-card-grid five">{[['Shot Builder',Clapperboard],['Camera',Play],['Lighting',SlidersHorizontal],['Sound',Mic2],['Continuity',Layers3]].map(([x,I]:any)=><article className="vw-tool-card" key={x}><I/><b>{x}</b><small>Open tool</small></article>)}</div></Panel></>;
}

export function PostProductionPage(p:PageProps){
 if(p.view==='V2')return <><div className="vw-three-col"><Panel title="Color"><Bars items={[['Exposure',62,''],['Contrast',54,''],['Saturation',46,''],['Skin tone',78,'QC']]}/></Panel><Panel title="Audio"><Bars items={[['Dialogue',74,''],['Ambience',58,''],['SFX',44,''],['Music',36,'']]}/></Panel><Panel title="VFX"><StatusGrid items={[['Clean-up','Available'],['Tracking','Available'],['Compositing','Available'],['QC','Required']]}/></Panel></div></>;
 if(p.view==='V3')return <><Panel title="AI Finishing & Delivery"><div className="vw-flow-row">{['Select Master','AI Assist','Human Review','QC','Render Master','Package'].map((x,i)=><div className="vw-flow-node" key={x}><span>{i+1}</span><b>{x}</b></div>)}</div></Panel></>;
 return <><Panel title="Edit & Finish Desk"><div className="vw-edit-preview"><AssetCard title="Program Monitor" subtitle="Selected production master" url={asset(p,['balloon','crossroads'])}/><div className="vw-edit-controls"><span><Play/>Play (preview unavailable)</span><span>00:00:00:00</span><span>1080p</span></div></div><div className="vw-edit-timeline">{['Video 1','Video 2','Dialogue','Ambience','Music'].map((x,i)=><div key={x}><span>{x}</span><i><b style={{left:(i*3)+'%',width:(82-i*7)+'%'}}/></i></div>)}</div></Panel></>;
}

export function DistributionGrowthPage(p:PageProps){
 if(p.view==='V1')return <><div className="vw-metrics"><Metric label="Ready" value={p.data.generations.filter((x:any)=>x.status==='complete').length}/><Metric label="Scheduled" value="0"/><Metric label="Published" value="—" delta="connector-confirmed only"/><Metric label="Alerts" value="0"/></div><Panel title="Distribution Overview"><StatusGrid items={[['YouTube','Recorded'],['Instagram','Recorded'],['TikTok','Not Connected'],['Drive','Recorded']]}/></Panel></>;
 if(p.view==='V3')return <><div className="vw-two-col"><Panel title="Analytics & Growth"><Bars items={[['Reach',0,'not connected'],['Engagement',0,'not connected'],['Conversions',0,'not connected'],['ROI',0,'not connected']]}/></Panel><Panel title="CMGIO Handoff"><StatusGrid items={[['Signals','Available'],['Optimization','Governed'],['Budget changes','Approval required'],['Publish truth','Provider-confirmed']]}/></Panel></div></>;
 return <><Panel title="Content Pipeline"><div className="vw-pipeline">{['Approved','Schedule','Publish','Verify','Measure','Optimize'].map((x,i)=><section key={x}><header><b>{x}</b><span>{i+1}</span></header>{i===0&&p.data.generations.filter((g:any)=>g.status==='complete').slice(0,3).map((g:any)=><div className="vw-pipeline-card" key={g.id}><Film/><div><b>{g.media_type||'Media'}</b><small>{g.provider||'provider'} · recorded</small></div></div>)}{i>0&&<div className="vw-pipeline-empty">No provider-confirmed items</div>}</section>)}</div></Panel><Panel title="Connection truth"><StatusGrid items={[['YouTube','Recorded'],['Instagram','Recorded'],['TikTok','Not Connected'],['Google Drive','Recorded'],['Publish authority','Approval-gated'],['Verification','Required']]}/></Panel></>;
}
