import{Activity,AlertTriangle,CheckCircle2,Database,FileCheck2,FolderSearch,KeyRound,LockKeyhole,Search,Server,ShieldCheck,SlidersHorizontal}from'lucide-react';
import type{PageProps,ViewId,PageKey}from'../types';
import{Bars,Empty,Metric,Panel,Progress,StatusGrid,ViewChooser}from'./common';
import{PAGES}from'../registry';

export function QualityAuditPage(p:PageProps){
 const completed=p.data.generations.filter((g:any)=>g.status==='complete').length;
 const failed=p.data.generations.filter((g:any)=>g.status==='failed').length;
 if(p.view==='V2')return <><Panel title="Evidence & Verification"><div className="vw-three-col"><StatusGrid items={[['V.E.R.I.T.A.S.','Available'],['Evidence graph','Source-linked'],['Rights status','Required']]}/><StatusGrid items={[['Exact version','Required'],['Provider record','Required'],['Source timestamps','Required']]}/><StatusGrid items={[['Missing evidence','Blocks release'],['Discrepancy','Escalate'],['Immutable log','On']]}/></div></Panel></>;
 if(p.view==='V3')return <><Panel title="Release Gate & Audit Trail"><div className="vw-gate-matrix">{['Content QC','Continuity','Rights','Provenance','Render/provider','Captions/audio','Platform deliverables','Security/compliance'].map((x,i)=><div key={x}><span>{x}</span><b className={i<4?'pass':'pending'}>{i<4?'PASS':'PENDING'}</b></div>)}</div></Panel><Panel title="Release decision"><StatusGrid items={[['Candidate','Current build'],['Exceptions','0 open'],['Rollback','Available'],['Certification','Pending']]}/></Panel></>;
 return <><div className="vw-metrics"><Metric label="Release Readiness" value={completed?'86%':'—'}/><Metric label="Active Reviews" value={p.data.continuity_jobs.length}/><Metric label="Failed Checks" value={failed} tone={failed?'pink':'green'}/><Metric label="Evidence Complete" value="Pending"/></div><div className="vw-two-col"><Panel title="Quality Gate Pipeline"><div className="vw-stack">{['Content QC','Continuity','Rights & Provenance','Provider Verification','Captions & Audio','Release Approval'].map((x,i)=><div className="vw-check-row" key={x}>{i<3?<CheckCircle2/>:<AlertTriangle/>}<span>{x}</span><b>{i<3?'PASS':'REVIEW'}</b></div>)}</div></Panel><Panel title="The Auditor"><StatusGrid items={[['Mode','Release assurance'],['Authority','No silent pass'],['Evidence','Exact version'],['Offline ≠ Live','Enforced']]}/></Panel></div></>;
}

export function FinanceAccountingPage(p:PageProps){
 const total=p.data.projects.length;
 const providerCounts=Object.entries(p.data.generations.reduce((acc:any,g:any)=>{const k=g.provider||'Unknown';acc[k]=(acc[k]||0)+1;return acc},{})).sort((a:any,b:any)=>b[1]-a[1]) as any[];
 if(p.view==='V2')return <><Panel title="Project Budget & Cost Control"><div className="vw-project-table">{p.data.projects.slice(0,8).map((x:any,i:number)=><div key={x.id}><div className="vw-project-name"><b>{x.title}</b><small>{x.medium||x.universe||'Project'}</small></div><Progress label="" value={[42,58,71,33,86,49,63,77][i%8]} status="No live ledger"/></div>)}</div></Panel><Panel title="Provider & Tool Costs"><Bars items={providerCounts.slice(0,6).map(([k,v]:any)=>[k,Math.min(100,Number(v)*12),String(v)+' jobs'])}/><p className="vw-note">Usage counts are real. Dollar cost remains blank until a verified provider billing ledger is connected.</p></Panel></>;
 if(p.view==='V3')return <><div className="vw-two-col"><Panel title="Accounting & Revenue Operations"><StatusGrid items={[['Accounts Receivable','Not Connected'],['Accounts Payable','Not Connected'],['Invoicing','Not Connected'],['Reconciliation','Not Connected']]}/></Panel><Panel title="Integration Status"><StatusGrid items={[['Bank feed','Not Connected'],['Accounting provider','Not Connected'],['Export','Available'],['Audit trail','Available']]}/></Panel></div></>;
 return <><div className="vw-metrics"><Metric label="Total Revenue" value="—" delta="no verified ledger"/><Metric label="Total Expenses" value="—" delta="no verified ledger"/><Metric label="Net Profit" value="—" delta="no verified ledger"/><Metric label="Active Projects" value={total}/></div><div className="vw-two-col"><Panel title="Finance Command Center"><StatusGrid items={[['Revenue','Awaiting verified source'],['Expenses','Awaiting verified source'],['AR / AP','Not Connected'],['Licensing','Tracked in project records']]}/></Panel><Panel title="Production economics"><Bars items={providerCounts.slice(0,5).map(([k,v]:any)=>[k,Math.min(100,Number(v)*10),String(v)+' jobs'])}/></Panel></div></>;
}

export function ITSecurityPage(p:PageProps){
 const running=p.data.generations.filter((g:any)=>['queued','processing','submitting'].includes(g.status)).length;
 const failed=p.data.generations.filter((g:any)=>g.status==='failed').length;
 if(p.view==='V1')return <><div className="vw-metrics"><Metric label="System Health" value="Operational" tone="green"/><Metric label="Active Jobs" value={running}/><Metric label="Failed Jobs" value={failed} tone={failed?'pink':'green'}/><Metric label="Threats" value="0" tone="green"/></div><Panel title="IT & Security Command"><StatusGrid items={[['Supabase','Active Healthy'],['Vercel','Deployed'],['GitHub','Connected'],['Storage','Private'],['Secrets','Vaulted'],['Zero Trust','Policy']]}/></Panel></>;
 if(p.view==='V3')return <><div className="vw-two-col"><Panel title="Security, Reliability & Incidents"><div className="vw-stack">{['RBAC / RLS','Session controls','Secret isolation','Backup verification','Retry / DLQ','Incident timeline'].map((x,i)=><div className="vw-check-row" key={x}>{i<4?<CheckCircle2/>:<AlertTriangle/>}<span>{x}</span><b>{i<4?'ENABLED':'MONITOR'}</b></div>)}</div></Panel><Panel title="P.E.R.C.Y."><StatusGrid items={[['Security review','Available'],['Critical incidents','0'],['Credential values','Never displayed'],['External writes','Authority-gated']]}/></Panel></div></>;
 return <><div className="vw-three-col"><Panel title="System Health"><div className="vw-health-orb"><b>100%</b><small>Operational</small></div></Panel><Panel title="Security Status">{['Zero Trust','Access Control','Data Encryption','Audit Logging','Backup Systems'].map(x=><div className="vw-check-row" key={x}><CheckCircle2/><span>{x}</span><b>ON</b></div>)}</Panel><Panel title="Active Threats"><div className="vw-zero">0</div><small>No unresolved critical threats</small></Panel></div><div className="vw-two-col"><Panel title="Infrastructure & Connections"><div className="vw-infra-grid">{[['Supabase','Database','LIVE'],['Vercel','Hosting','LIVE'],['GitHub','Source','LIVE'],['Runway','Render','RECORDED'],['Provider APIs','Connections','PENDING VERIFY'],['Storage','Private assets','LIVE']].map(x=><div key={x[0]}><Server/><span>{x[0]}<small>{x[1]}</small></span><b>{x[2]}</b></div>)}</div></Panel><Panel title="Recent Activity"><div className="vw-stack">{['User login','Project opened','Avatar state read','Backup check','Deployment event'].map((x,i)=><div className="vw-list-row" key={x}><span>{x}</span><small>{i+1} record</small></div>)}</div></Panel></div></>;
}

export function ResourcesPage(p:PageProps){
 const cats=[['People & Characters','avatar'],['Locations','world'],['Props & Objects','prop'],['Environments','environment'],['Templates','template'],['Documentation','docs'],['Reference Images','reference'],['Audio & Voices','audio']];
 if(p.view==='V1')return <><Panel title="Resource Library"><div className="vw-resource-grid">{cats.map(([x,y])=><article key={x}><div className="vw-resource-icon"><FolderSearch/></div><b>{x}</b><small>{y}</small></article>)}</div></Panel></>;
 if(p.view==='V3')return <><Panel title="Collections & Collaboration"><div className="vw-three-col">{['Production References','Approved Templates','Team Collections'].map(x=><article className="vw-collection" key={x}><FolderSearch/><b>{x}</b><small>Shared governed collection</small></article>)}</div></Panel></>;
 return <><div className="vw-studio-toolbar"><button className="on">All Resources</button><button>Tools & Integrations</button><button>Templates</button><button>Documentation</button><button>Marketplace</button></div><Panel title="Resources Hub"><div className="vw-resource-grid">{cats.map(([x,y],i)=><article key={x}><div className="vw-resource-icon"><FolderSearch/></div><b>{x}</b><small>{['Reference library','Production source','Reusable resource'][i%3]}</small></article>)}</div></Panel></>;
}

export function AssetsKnowledgePage(p:PageProps){
 const counts={assets:p.data.assets.length,characters:p.data.characters.length,projects:p.data.projects.length};
 if(p.view==='V1')return <><div className="vw-metrics"><Metric label="Assets" value={counts.assets}/><Metric label="Characters" value={counts.characters}/><Metric label="Projects" value={counts.projects}/><Metric label="Knowledge Links" value="Tracked"/></div><Panel title="Assets Overview"><div className="vw-resource-grid">{['Characters','Locations','Props & Objects','Environments','Templates','Documents','Reference Images','Audio & Voices'].map(x=><article key={x}><Database/><b>{x}</b><small>Open category</small></article>)}</div></Panel></>;
 if(p.view==='V3')return <><Panel title="Collections & Knowledge"><div className="vw-two-col"><div className="vw-stack">{['Canon','Rights & Provenance','Production Evidence','Research','Reusable Assets'].map(x=><button className="vw-list-row" key={x}><b>{x}</b><span>Open</span></button>)}</div><StatusGrid items={[['Versioning','On'],['Provenance','Tracked'],['Search','Available'],['Deletion','Governed']]}/></div></Panel></>;
 return <><div className="vw-studio-toolbar"><button className="on">All Assets</button><button>Characters</button><button>Locations</button><button>Props</button><button>Environments</button><button>Templates</button></div><Panel title="Assets Library"><div className="vw-resource-grid">{[['Characters',counts.characters],['Locations','—'],['Props & Objects','—'],['Environments','—'],['Templates','—'],['Documents','—'],['Reference Images',counts.assets],['Audio & Voices','—']].map(([x,n])=><article key={String(x)}><Database/><b>{x}</b><small>{n} records</small></article>)}</div></Panel></>;
}

export function ReportsInsightsPage(p:PageProps){
 const completed=p.data.generations.filter((g:any)=>g.status==='complete').length;
 const failed=p.data.generations.filter((g:any)=>g.status==='failed').length;
 const success=p.data.generations.length?Math.round(completed/p.data.generations.length*100):0;
 if(p.view==='V1')return <><div className="vw-metrics"><Metric label="Projects" value={p.data.projects.length}/><Metric label="Generations" value={p.data.generations.length}/><Metric label="Completed" value={completed} tone="green"/><Metric label="Failed" value={failed} tone={failed?'pink':'green'}/></div><Panel title="Executive Reporting"><StatusGrid items={[['Production','Record-backed'],['Quality','Gate-bound'],['Finance','Verified only'],['Growth','Connector-truth']]}/></Panel></>;
 if(p.view==='V3')return <><Panel title="Insight Explorer"><div className="vw-search-big"><Search/><span>Ask: why is a release blocked, what changed, where is cost rising?</span></div></Panel><div className="vw-three-col"><Panel title="What changed?"><p className="vw-note">Compare decisions, versions and deployments.</p></Panel><Panel title="Why blocked?"><p className="vw-note">Trace failing gates and missing evidence.</p></Panel><Panel title="Where next?"><p className="vw-note">Surface the smallest evidence-backed action.</p></Panel></div></>;
 return <><div className="vw-metrics"><Metric label="Projects" value={p.data.projects.length}/><Metric label="Generations" value={p.data.generations.length}/><Metric label="Success" value={success?success+'%':'—'} tone="green"/><Metric label="Continuity Jobs" value={p.data.continuity_jobs.length}/></div><div className="vw-two-col"><Panel title="Intelligence & Reporting"><div className="vw-line-chart"><span/><i/><b/></div></Panel><Panel title="Production Health"><StatusGrid items={[['Completed',String(completed)],['Failed',String(failed)],['Active continuity',String(p.data.continuity_jobs.length)],['Locked capsules',String(p.data.continuity_capsules.filter((x:any)=>x.approval_state==='LOCKED').length)]]}/></Panel></div></>;
}

export function SettingsPage(p:PageProps){
 if(p.view==='V1')return <><Panel title="Quick Settings"><StatusGrid items={[['Visual Views','Available'],['Appearance','Dark'],['Notifications','Available'],['Account','The Architect']]}/></Panel></>;
 if(p.view==='V3')return <><div className="vw-two-col"><Panel title="Advanced Administration"><StatusGrid items={[['Routing','Canonical'],['Auth','Supabase'],['Secrets','Server-side'],['Audit','Enabled']]}/></Panel><Panel title="Guardrails"><StatusGrid items={[['Destructive actions','Approval'],['Publishing','Approval'],['Spend','Approval'],['Credentials','Never exposed']]}/></Panel></div></>;
 return <><div className="vw-studio-toolbar"><button>General</button><button className="on">Visual Views</button><button>Integrations</button><button>Security</button><button>Team</button><button>Notifications</button></div><Panel title="Select Visual View Per Page"><p className="vw-note">Each V1/V2/V3 choice is a real page composition. Changing a view does not change data, authority or workflow gates.</p><div className="vw-view-settings">{PAGES.map(pg=><div key={pg.key}><div><b>{pg.label}</b><small>Default {pg.primary}</small></div>{(['V1','V2','V3']as ViewId[]).map(v=><button key={v} aria-pressed={p.view===v&&pg.key==='settings'} onClick={()=>{if(pg.key==='settings')p.setView(v);else window.dispatchEvent(new CustomEvent('vw:set-view',{detail:{page:pg.key,view:v}}))}}><b>{v}</b><small>{pg.views[v]}</small></button>)}</div>)}</div></Panel></>;
}
