import{useEffect,useMemo,useState}from'react';
import{AlertTriangle,BookOpen,CheckCircle2,Clock3,Database,FileSearch,RefreshCw,Search,ShieldCheck,Wrench}from'lucide-react';
import{supabase}from'../lib/supabase';
import{useIdentity}from'../auth/IdentityContext';

type Rollup={system_key:string;display_name:string;system_class:string;canonical_state:string;runtime_state:string;dashboard_route:string|null;open_findings:number;corrected_findings:number;critical_open:number;last_finding_activity:string|null};
type Finding={id:string;finding_key:string;system_key:string|null;domain:string;title:string;description:string;finding_type:string;severity:'critical'|'high'|'medium'|'low'|'info';status:string;priority:number;remediation_plan:string|null;source_ref:string|null;updated_at:string};
type Action={id:string;action_key:string;action_type:string;status:string;summary:string;commit_sha:string|null;migration_version:string|null;deployment_id:string|null;test_ref:string|null;executed_at:string|null;verified_at:string|null;created_at:string};
type Memory={id:string;memory_key:string;system_key:string|null;category:string;title:string;summary:string;body:string;memory_state:string;trust_level:string;source_ref:string|null;effective_at:string;tags:string[]};
type Tab='overview'|'findings'|'systems'|'repairs'|'memory';

export default function AnalystMemoryWorkspace(){
 const identity=useIdentity();
 const[tab,setTab]=useState<Tab>('overview'),[query,setQuery]=useState(''),[status,setStatus]=useState('ACTIVE'),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const[systems,setSystems]=useState<Rollup[]>([]),[findings,setFindings]=useState<Finding[]>([]),[actions,setActions]=useState<Action[]>([]),[memories,setMemories]=useState<Memory[]>([]);
 const load=async()=>{if(!supabase||!identity.organizationId)return;setLoading(true);setError('');const org=identity.organizationId;const[a,b,c,d]=await Promise.all([
  supabase.from('analyst_system_rollup').select('*').eq('organization_id',org).order('critical_open',{ascending:false}).order('open_findings',{ascending:false}),
  supabase.from('analyst_findings').select('id,finding_key,system_key,domain,title,description,finding_type,severity,status,priority,remediation_plan,source_ref,updated_at').eq('organization_id',org).order('priority',{ascending:false}).order('updated_at',{ascending:false}).limit(400),
  supabase.from('analyst_actions').select('id,action_key,action_type,status,summary,commit_sha,migration_version,deployment_id,test_ref,executed_at,verified_at,created_at').eq('organization_id',org).order('created_at',{ascending:false}).limit(150),
  supabase.from('analyst_memory').select('id,memory_key,system_key,category,title,summary,body,memory_state,trust_level,source_ref,effective_at,tags').eq('organization_id',org).order('effective_at',{ascending:false}).limit(150)
 ]);const first=[a.error,b.error,c.error,d.error].find(Boolean);if(first)setError(first?.message??'Unable to load analyst memory.');else{setSystems((a.data??[])as Rollup[]);setFindings((b.data??[])as Finding[]);setActions((c.data??[])as Action[]);setMemories((d.data??[])as Memory[])}setLoading(false)};
 useEffect(()=>{void load()},[identity.organizationId]);
 const open=findings.filter(f=>['OPEN','IN_PROGRESS','BLOCKED'].includes(f.status)),corrected=findings.filter(f=>['FIXED','VERIFIED'].includes(f.status)),critical=open.filter(f=>f.severity==='critical');
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return findings.filter(f=>{const matches=!q||`${f.title} ${f.description} ${f.finding_key} ${f.system_key??''} ${f.domain} ${f.remediation_plan??''}`.toLowerCase().includes(q);const state=status==='ALL'||(status==='ACTIVE'?['OPEN','IN_PROGRESS','BLOCKED'].includes(f.status):status==='CORRECTED'?['FIXED','VERIFIED'].includes(f.status):f.status===status);return matches&&state})},[findings,query,status]);
 const severity=(value:string)=>`analyst-severity ${value}`;
 if(loading)return <section className="analyst-state"><RefreshCw className="spin"/><b>Loading Analyst Memory Bank…</b><span>Reading system findings, evidence footprints and repair history.</span></section>;
 return <div className="analyst-workspace">
  <div className="analyst-hero"><div><small>CANONICAL RECONSTRUCTION MEMORY</small><h2>Analyst Memory Bank</h2><p>One queryable footprint of what was found, what was wrong, what was repaired, what remains open, and which evidence proves each state.</p></div><button onClick={()=>void load()}><RefreshCw/>Refresh</button></div>
  {error&&<div className="analyst-error"><AlertTriangle/><span>{error}</span></div>}
  <div className="analyst-metrics"><article><AlertTriangle/><span>Open / blocked</span><strong>{open.length}</strong><small>Requires correction or decision</small></article><article><ShieldCheck/><span>Critical open</span><strong>{critical.length}</strong><small>Highest reconstruction priority</small></article><article><CheckCircle2/><span>Corrected / verified</span><strong>{corrected.length}</strong><small>Evidence-backed repairs</small></article><article><Database/><span>Systems indexed</span><strong>{systems.length}</strong><small>Canonical + recovery surfaces</small></article></div>
  <div className="analyst-tabs">{([['overview','Overview'],['findings','Findings'],['systems','Systems'],['repairs','Repair Footprints'],['memory','Memory Bank']]as const).map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
  {tab==='overview'&&<div className="analyst-grid"><section className="analyst-panel"><header><div><small>PRIORITY QUEUE</small><h3>Critical reconstruction work</h3></div><span>{critical.length} open</span></header>{critical.slice(0,12).map(f=><article className="analyst-finding" key={f.id}><i className={severity(f.severity)}>{f.severity}</i><div><b>{f.title}</b><small>{f.system_key??'Enterprise'} · {f.finding_type}</small><p>{f.description}</p>{f.remediation_plan&&<em>Next: {f.remediation_plan}</em>}</div></article>)}{!critical.length&&<p className="analyst-empty">No critical open findings.</p>}</section><section className="analyst-panel"><header><div><small>SYSTEM ROLLUP</small><h3>Where the puzzle stands</h3></div><span>{systems.length} systems</span></header>{systems.slice(0,12).map(s=><article className="analyst-system" key={s.system_key}><div><b>{s.display_name}</b><small>{s.system_key} · {s.canonical_state}</small></div><strong>{s.open_findings}</strong><span>open</span>{s.critical_open>0&&<i>{s.critical_open} critical</i>}</article>)}</section><section className="analyst-panel wide"><header><div><small>RECENT REPAIRS</small><h3>Verified footprints</h3></div><span>{actions.length} recorded</span></header><div className="analyst-action-grid">{actions.slice(0,8).map(a=><article key={a.id}><Wrench/><div><b>{a.summary}</b><small>{a.action_key} · {a.status}</small>{a.commit_sha&&<code>{a.commit_sha.slice(0,12)}</code>}</div></article>)}</div></section></div>}
  {tab==='findings'&&<><div className="analyst-toolbar"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search flaw, system, remediation or evidence…"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ACTIVE">Open + blocked</option><option value="CORRECTED">Corrected + verified</option><option value="ALL">All findings</option><option value="OPEN">Open only</option><option value="BLOCKED">Blocked only</option><option value="VERIFIED">Verified only</option></select><strong>{filtered.length} findings</strong></div><section className="analyst-panel"><div className="analyst-table-head"><span>Severity</span><span>Finding</span><span>System</span><span>Status</span><span>Priority</span></div>{filtered.map(f=><article className="analyst-table-row" key={f.id}><i className={severity(f.severity)}>{f.severity}</i><div><b>{f.title}</b><small>{f.finding_key}</small><p>{f.description}</p>{f.remediation_plan&&<em>Next: {f.remediation_plan}</em>}</div><code>{f.system_key??'enterprise'}</code><strong className={`analyst-status ${f.status.toLowerCase()}`}>{f.status.replaceAll('_',' ')}</strong><span>{f.priority}</span></article>)}</section></>}
  {tab==='systems'&&<div className="analyst-system-grid">{systems.map(s=><article key={s.system_key}><header><Database/><div><b>{s.display_name}</b><small>{s.system_key}</small></div></header><dl><div><dt>Canonical</dt><dd>{s.canonical_state}</dd></div><div><dt>Runtime</dt><dd>{s.runtime_state}</dd></div><div><dt>Open</dt><dd>{s.open_findings}</dd></div><div><dt>Corrected</dt><dd>{s.corrected_findings}</dd></div><div><dt>Critical</dt><dd>{s.critical_open}</dd></div></dl>{s.dashboard_route&&<code>{s.dashboard_route}</code>}</article>)}</div>}
  {tab==='repairs'&&<section className="analyst-panel"><header><div><small>CHANGE FOOTPRINT</small><h3>Repairs and proof</h3></div><span>{actions.length} actions</span></header>{actions.map(a=><article className="analyst-repair" key={a.id}><span><CheckCircle2/></span><div><b>{a.summary}</b><small>{a.action_key} · {a.action_type} · {a.status}</small><div className="analyst-proof">{a.commit_sha&&<code>commit {a.commit_sha}</code>}{a.migration_version&&<code>migration {a.migration_version}</code>}{a.deployment_id&&<code>deploy {a.deployment_id}</code>}{a.test_ref&&<code>{a.test_ref}</code>}</div></div><time>{new Date(a.verified_at??a.executed_at??a.created_at).toLocaleString()}</time></article>)}</section>}
  {tab==='memory'&&<div className="analyst-memory-grid">{memories.map(m=><article key={m.id}><header><BookOpen/><div><small>{m.category.toUpperCase()} · {m.trust_level}</small><h3>{m.title}</h3></div></header><p>{m.summary}</p><details><summary>Read canonical memory</summary><div>{m.body}</div>{m.source_ref&&<code>{m.source_ref}</code>}</details><footer>{m.tags.map(t=><span key={t}>{t}</span>)}</footer></article>)}</div>}
 </div>;
}
