import{FormEvent,useEffect,useMemo,useState}from'react';
import{Activity,BarChart3,Bot,CheckCircle2,Megaphone,Plus,RefreshCw,ShieldCheck,Sparkles,Target,TrendingUp}from'lucide-react';
import{supabase}from'../lib/supabase';
import{useIdentity}from'../auth/IdentityContext';

type Campaign={id:string;name:string;objective:string;channel:string;status:string;budget:number;spend:number;leads:number;conversions:number;revenue:number;risk_level:string;authorization_state:string};
type Signal={id:string;signal_type:string;channel:string;title:string;confidence:number;recommended_action:string;status:string};
const tabs=['Launch Center','Campaigns','Publishing','Monitoring','Optimization','Autopilot','Assets','Usage & Cost','QC','Governance'];
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);

export default function CmgioWorkspace(){
 const identity=useIdentity();
 const[campaigns,setCampaigns]=useState<Campaign[]>([]),[intel,setIntel]=useState<Signal[]>([]),[view,setView]=useState('Launch Center'),[adding,setAdding]=useState(false),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[activeId,setActiveId]=useState('');
 const[form,setForm]=useState({name:'',objective:'',channel:'Social',budget:'0'});
 async function load(){if(identity.isBuilder||!supabase)return;setBusy(true);const[c,s]=await Promise.all([supabase.from('marketing_campaigns').select('*').order('updated_at',{ascending:false}),supabase.from('marketing_signals').select('*').order('detected_at',{ascending:false})]);if(c.data){setCampaigns(c.data);setActiveId(x=>x||c.data?.[0]?.id||'')}if(s.data)setIntel(s.data);setNotice(c.error?.message||s.error?.message||'');setBusy(false)}
 useEffect(()=>{load();if(identity.isBuilder||!supabase)return;const client=supabase;const ch=client.channel('cmgio-live').on('postgres_changes',{event:'*',schema:'public',table:'marketing_campaigns'},load).on('postgres_changes',{event:'*',schema:'public',table:'marketing_signals'},load).subscribe();return()=>{client.removeChannel(ch)}},[identity.isBuilder]);
 async function create(e:FormEvent){e.preventDefault();if(!supabase||!identity.user)return;setBusy(true);const{data,error}=await supabase.from('marketing_campaigns').insert({organization_id:identity.organizationId,created_by:identity.user.id,name:form.name,objective:form.objective,channel:form.channel,status:'Bullpen',budget:Number(form.budget)||0,spend:0,leads:0,conversions:0,revenue:0,risk_level:'medium',authorization_state:'ASK'}).select('*').single();setBusy(false);if(error)setNotice(error.message);else{setCampaigns(x=>[data,...x]);setActiveId(data.id);setAdding(false);setForm({name:'',objective:'',channel:'Social',budget:'0'});setNotice('Campaign created in Bullpen.');setView('Campaigns')}}
 const active=campaigns.find(c=>c.id===activeId)||campaigns[0];
 async function updateCampaign(values:Record<string,unknown>,message:string){if(!supabase||!active)return;setBusy(true);const{error}=await supabase.from('marketing_campaigns').update(values).eq('id',active.id);setBusy(false);if(error)setNotice(error.message);else{setNotice(message);await load()}}
 async function setSignal(signal:Signal,status:string){if(!supabase)return;const{error}=await supabase.from('marketing_signals').update({status}).eq('id',signal.id);if(error)setNotice(error.message);else await load()}
 async function requestOptimization(signal:Signal){if(!supabase||!identity.user)return;const{error}=await supabase.from('orchestration_commands').insert({organization_id:identity.organizationId,requested_by:identity.user.id,source_system:'SYS-CMGIO-001',target_agent:'CMGIO',action_type:`Optimize: ${signal.recommended_action}`,risk_level:'medium',authorization_state:'ASK',execution_status:'queued',payload_reference:{signal_id:signal.id,channel:signal.channel,title:signal.title}});if(error)setNotice(error.message);else{await setSignal(signal,'accepted');setNotice('Optimization command staged in THELMA at ASK.') }}
 const m=useMemo(()=>({budget:campaigns.reduce((n,c)=>n+Number(c.budget),0),spend:campaigns.reduce((n,c)=>n+Number(c.spend),0),revenue:campaigns.reduce((n,c)=>n+Number(c.revenue),0),leads:campaigns.reduce((n,c)=>n+c.leads,0),conversions:campaigns.reduce((n,c)=>n+c.conversions,0),roas:campaigns.reduce((n,c)=>n+Number(c.spend),0)?campaigns.reduce((n,c)=>n+Number(c.revenue),0)/campaigns.reduce((n,c)=>n+Number(c.spend),0):0}),[campaigns]);
 const campaignRows=<>{campaigns.map(c=><article className="campaign" key={c.id} onClick={()=>setActiveId(c.id)} style={{cursor:'pointer'}}><Megaphone/><div><b>{c.name}</b><small>{c.objective} · {c.channel}</small></div><span>{c.status}</span><strong>{money(Number(c.budget))}</strong><em>{c.authorization_state}</em></article>)}</>;
 const signalRows=<>{intel.length?intel.map(s=><article className="signal" key={s.id}><Target/><div><b>{s.title}</b><small>{s.channel} · {s.recommended_action}</small></div><strong>{s.confidence}%</strong><span>{s.status}</span><div className="fabric-job-actions">{s.status==='review'&&<><button onClick={()=>requestOptimization(s)}>Accept & route</button><button onClick={()=>setSignal(s,'dismissed')}>Dismiss</button></>}</div></article>):<p className="muted">No marketing signals are waiting.</p>}</>;
 return <div className="cmgio"><div className="briefing cmgio-hero"><div><span className="eyebrow">SYS-CMGIO-001 · MARKETING & GROWTH INTELLIGENCE</span><h2>CMGIO</h2><p>Create campaigns, move them through governance, review signals, route optimization work and see actual spend/performance records.</p></div><button onClick={load}><RefreshCw/>{busy?'Syncing':'Refresh intelligence'}</button></div><div className="land-tabs">{tabs.map(t=><button className={view===t?'active':''} onClick={()=>setView(t)} key={t}><Sparkles/>{t}</button>)}</div><div className="metrics"><article className="metric cyan"><span>Portfolio budget</span><strong>{money(m.budget)}</strong><small>{money(m.spend)} spent</small></article><article className="metric green"><span>Attributed revenue</span><strong>{money(m.revenue)}</strong><small>{m.roas.toFixed(1)}x ROAS</small></article><article className="metric amber"><span>Qualified leads</span><strong>{m.leads}</strong><small>{m.conversions} conversions</small></article><article className="metric purple"><span>Signals</span><strong>{intel.filter(s=>s.status==='review').length}</strong><small>Awaiting review</small></article></div>
 {view==='Launch Center'&&<div className="cmgio-grid"><section className="panel"><div className="panel-title"><div><span className="eyebrow">CAMPAIGN COMMAND</span><h3>Portfolio</h3></div><button onClick={()=>setAdding(!adding)}><Plus/>New</button></div>{adding&&<form className="campaign-form" onSubmit={create}><input required placeholder="Campaign name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required placeholder="Objective" value={form.objective} onChange={e=>setForm({...form,objective:e.target.value})}/><input placeholder="Channels" value={form.channel} onChange={e=>setForm({...form,channel:e.target.value})}/><input type="number" placeholder="Budget" value={form.budget} onChange={e=>setForm({...form,budget:e.target.value})}/><button>Stage campaign</button></form>}{campaignRows}</section><section className="panel"><div className="panel-title"><div><span className="eyebrow">MONITORING</span><h3>Signals</h3></div><TrendingUp/></div>{signalRows}</section></div>}
 {view==='Campaigns'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">BULLPEN · STAGING · ACTIVE</span><h3>Campaigns</h3></div><Megaphone/></div>{campaignRows}{active&&<div className="control-grid">{['Bullpen','Staging','Active','Paused','Completed'].map(status=><button key={status} onClick={()=>updateCampaign({status},`Campaign moved to ${status}.`)}>{status}<Megaphone/></button>)}</div>}</section>}
 {view==='Publishing'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">PUBLISHING GATE</span><h3>{active?.name||'Select a campaign'}</h3></div><ShieldCheck/></div>{active&&<><p>Channel: <b>{active.channel}</b> · Status: <b>{active.status}</b> · Authorization: <b>{active.authorization_state}</b></p><button onClick={()=>updateCampaign({authorization_state:'AUTHORIZED',status:'Staging'},'Campaign approved for external publishing once its channel connector is healthy.')}>Approve publishing package</button><div className="land-boundary"><ShieldCheck/><p><b>No false publish:</b> this authorizes the campaign package. It does not claim a post or ad was published unless a configured channel connector confirms it.</p></div></>}</section>}
 {view==='Monitoring'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">SIGNAL MONITOR</span><h3>Verified intelligence</h3></div><TrendingUp/></div>{signalRows}</section>}
 {view==='Optimization'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">OPTIMIZATION QUEUE</span><h3>Recommended actions</h3></div><Bot/></div>{signalRows}</section>}
 {view==='Autopilot'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">AUTOPILOT</span><h3>Guarded automation</h3></div><Bot/></div><div className="fabric-controls"><article><ShieldCheck/><b>Internal optimization active</b><p>CMGIO can stage analysis and optimization commands through THELMA.</p></article><article><Target/><b>External writes credential-gated</b><p>Publishing, budget changes and channel writes remain off until the matching connector reports healthy write authority.</p></article></div></section>}
 {view==='Assets'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">CREATIVE ASSETS</span><h3>Campaign asset handoff</h3></div><Sparkles/></div><p>VisionWeaver and the Master Media Library are the source workspaces for generated and approved media. CMGIO references those assets at campaign execution time.</p></section>}
 {view==='Usage & Cost'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">USAGE & COST</span><h3>Portfolio economics</h3></div><BarChart3/></div><div className="fabric-controls"><article><Activity/><b>{money(m.spend)} spent</b><p>Against {money(m.budget)} budget.</p></article><article><TrendingUp/><b>{m.roas.toFixed(1)}x ROAS</b><p>{m.leads} leads and {m.conversions} conversions.</p></article></div></section>}
 {view==='QC'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">CAMPAIGN QC</span><h3>Readiness review</h3></div><CheckCircle2/></div>{campaigns.map(c=><article className="campaign" key={c.id}><CheckCircle2/><div><b>{c.name}</b><small>{c.objective}</small></div><span>{c.status}</span><strong>{c.authorization_state}</strong><em>{c.channel}</em></article>)}</section>}
 {view==='Governance'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">GOVERNANCE</span><h3>Growth operating boundary</h3></div><ShieldCheck/></div><div className="fabric-controls"><article><ShieldCheck/><b>ASK / AUTHORIZE</b><p>Optimization commands are staged for review. Publishing packages require explicit approval.</p></article><article><Target/><b>Provider truth</b><p>No channel is marked published or budget-changed without confirmation from a configured connector.</p></article></div></section>}
 {notice&&<div className="land-notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}</div>;
}
