import{FormEvent,useEffect,useMemo,useState}from'react';
import{Award,BookOpen,BriefcaseBusiness,Calculator,CheckCircle2,ClipboardCheck,FileCheck2,FileText,Library,Plus,RefreshCw,Search,Settings,ShieldCheck,Target}from'lucide-react';
import{supabase}from'../lib/supabase';
import{useIdentity}from'../auth/IdentityContext';
type Application={id:string;title:string;stage:string;requested_amount:number|null;due_at:string|null;completion_percent:number;risk_level:string;authorization_state:string};
type Requirement={id:string;application_id:string;label:string;slot_state:'Empty'|'Pending'|'Verified';required:boolean;sort_order:number};
const apps:Application[]=[
 {id:'grant-1',title:'Community Facilities Innovation Grant',stage:'Drafting',requested_amount:500000,due_at:'2026-09-18',completion_percent:62,risk_level:'high',authorization_state:'ASK'},
 {id:'grant-2',title:'Creative Workforce Development RFP',stage:'In Review',requested_amount:250000,due_at:'2026-10-02',completion_percent:28,risk_level:'high',authorization_state:'ASK'},
 {id:'grant-3',title:'Coastal Resilience Planning Award',stage:'In Review',requested_amount:400000,due_at:'2026-10-21',completion_percent:28,risk_level:'high',authorization_state:'ASK'}
];
const reqs:Requirement[]=apps.flatMap((a,ai)=>[['Eligibility evidence','Verified'],['Narrative draft',ai===0?'Pending':'Empty'],['Budget and match','Pending'],['Authority and certifications','Empty'],['Submission package','Empty']].map(([label,slot_state],i)=>({id:a.id+'-'+i,application_id:a.id,label,slot_state:slot_state as Requirement['slot_state'],required:true,sort_order:(i+1)*10})));
const tabs=[['Pipeline',BriefcaseBusiness],['Opportunities',Search],['Requirements',ClipboardCheck],['Drafting',FileText],['Budget',Calculator],['Documents',FileCheck2],['Submission',Target],['Awards',Award],['Compliance',ShieldCheck],['Memory',Library],['Settings',Settings]]as const;
const money=(n:number|null)=>n==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
export default function GrantOSWorkspace(){
 const identity=useIdentity(),[applications,setApplications]=useState<Application[]>([]),[requirements,setRequirements]=useState<Requirement[]>([]),[activeId,setActiveId]=useState(''),[view,setView]=useState('Pipeline'),[adding,setAdding]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const[form,setForm]=useState({title:'',amount:'',deadline:''});
 async function load(){if(identity.isBuilder){setApplications(apps);setRequirements(reqs);setActiveId(x=>x||apps[0].id);return}if(!supabase)return;setBusy(true);const[{data:a,error},{data:r}]=await Promise.all([supabase.from('grant_applications').select('id,title,stage,requested_amount,due_at,completion_percent,risk_level,authorization_state').order('due_at'),supabase.from('grant_requirements').select('id,application_id,label,slot_state,required,sort_order').order('sort_order')]);if(error)setNotice(error.message);else{setApplications(a||[]);setRequirements((r||[])as Requirement[]);setActiveId(x=>x||a?.[0]?.id||'')}setBusy(false)}
 useEffect(()=>{load();if(identity.isBuilder)return;const client=supabase;if(!client)return;const c=client.channel('grantos-live').on('postgres_changes',{event:'*',schema:'public',table:'grant_applications'},load).on('postgres_changes',{event:'*',schema:'public',table:'grant_requirements'},load).subscribe();return()=>{client.removeChannel(c)}},[identity.isBuilder]);
 async function create(e:FormEvent){e.preventDefault();if(identity.isBuilder){const item:Application={id:crypto.randomUUID(),title:form.title,stage:'Prospecting',requested_amount:Number(form.amount)||null,due_at:form.deadline||null,completion_percent:0,risk_level:'medium',authorization_state:'ASK'};setApplications(x=>[item,...x]);setActiveId(item.id);setAdding(false);setNotice('Opportunity added to this builder session. Submission authority remains locked.');return}if(!supabase||!identity.user)return;setBusy(true);const{data,error}=await supabase.from('grant_applications').insert({organization_id:identity.organizationId,title:form.title,stage:'Prospecting',requested_amount:Number(form.amount)||null,due_at:form.deadline||null,completion_percent:0,risk_level:'medium',authorization_state:'ASK',owner_id:identity.user.id}).select('id,title,stage,requested_amount,due_at,completion_percent,risk_level,authorization_state').single();if(error)setNotice(error.message);else{setApplications(x=>[data,...x]);setActiveId(data.id);setAdding(false)}setBusy(false)}
 const active=applications.find(a=>a.id===activeId)||applications[0],activeReqs=requirements.filter(r=>r.application_id===active?.id);
 const metrics=useMemo(()=>({pipeline:applications.reduce((n,a)=>n+(a.requested_amount||0),0),due:applications.filter(a=>a.due_at).length,review:applications.filter(a=>a.stage==='In Review').length,verified:requirements.filter(r=>r.slot_state==='Verified').length}),[applications,requirements]);
 return <div className="grantos"><div className="briefing grant-hero"><div><span className="eyebrow">SYS-GRANT-001 · GOVERNED FUNDING OPERATIONS</span><h2>Move an opportunity from discovery to compliant award management.</h2><p>Eligibility, drafting, budgets, marker slots, authority, submission and compliance remain evidence-backed.</p></div><div className="land-actions"><button onClick={()=>setAdding(!adding)}><Plus/>New opportunity</button><button className="secondary" onClick={load}><RefreshCw/>{busy?'Syncing':'Refresh'}</button></div></div>
 <div className="land-tabs">{tabs.map(([name,Icon])=><button className={view===name?'active':''} onClick={()=>setView(name)} key={name}><Icon/>{name}</button>)}</div>
 {adding&&<form className="panel grant-intake" onSubmit={create}><div className="panel-title"><div><span className="eyebrow">GOVERNED OPPORTUNITY INTAKE</span><h3>Add a funding opportunity</h3></div><ShieldCheck/></div><div className="land-form"><label>Opportunity title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Requested amount<input type="number" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Deadline<input type="date" value={form.deadline} onChange={e=>setForm({...form,deadline:e.target.value})}/></label></div><button disabled={busy}>Add to Prospecting</button></form>}
 <div className="metrics"><article className="metric green"><span>Pipeline value</span><strong>{money(metrics.pipeline)}</strong><small>Synthetic launch portfolio</small></article><article className="metric cyan"><span>Tracked deadlines</span><strong>{metrics.due}</strong><small>Countdown enabled</small></article><article className="metric amber"><span>In review</span><strong>{metrics.review}</strong><small>Eligibility gates</small></article><article className="metric purple"><span>Verified slots</span><strong>{metrics.verified}</strong><small>Evidence retained</small></article></div>
 <div className="grant-board"><section className="panel"><div className="panel-title"><div><span className="eyebrow">BULLPEN · STAGING · ACTIVE</span><h3>{view}</h3></div><span className="live"><i/>{identity.isBuilder?'Builder':'Supabase'}</span></div>{applications.map(a=><button className={active?.id===a.id?'grant-card active':'grant-card'} onClick={()=>setActiveId(a.id)} key={a.id}><div><b>{a.title}</b><small>{a.stage} · Due {a.due_at?new Date(a.due_at).toLocaleDateString():'TBD'}</small></div><strong>{money(a.requested_amount)}</strong><span>{a.completion_percent}%</span></button>)}</section>
 <section className="panel"><div className="panel-title"><div><span className="eyebrow">INTELLIGENT CARD · MARKER SLOTS</span><h3>{active?.title||'Select an application'}</h3></div>{active&&<span className="source">{active.authorization_state}</span>}</div>{active&&<div className="grant-progress"><i><em style={{width:active.completion_percent+'%'}}/></i><b>{active.completion_percent}% complete</b></div>}<div className="slot-list">{activeReqs.map(r=><article key={r.id}><span className={r.slot_state.toLowerCase()}>{r.slot_state}</span><div><b>{r.label}</b><small>{r.required?'Required':'Optional'} · Evidence slot</small></div><CheckCircle2/></article>)}{active&&!activeReqs.length&&<div className="land-empty"><BookOpen/><b>Marker slots await setup</b><p>Requirements are converted into Empty, Pending and Verified evidence slots.</p></div>}</div><div className="land-boundary"><ShieldCheck/><p><b>Submission boundary:</b> high-risk submission and certification remain at ASK until The Architect authorizes the governed action and audit record.</p></div></section></div>
 {notice&&<div className="land-notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}</div>
}
