import{FormEvent,useEffect,useMemo,useState}from'react';
import{Award,BookOpen,BriefcaseBusiness,Calculator,CheckCircle2,ClipboardCheck,FileCheck2,FileText,Library,Plus,RefreshCw,Search,Settings,ShieldCheck,Target}from'lucide-react';
import{supabase}from'../lib/supabase';
import{useIdentity}from'../auth/IdentityContext';

type Application={id:string;title:string;stage:string;requested_amount:number|null;due_at:string|null;completion_percent:number;risk_level:string;authorization_state:string};
type Requirement={id:string;application_id:string;label:string;slot_state:'Empty'|'Pending'|'Verified';required:boolean;sort_order:number;evidence_reference?:Record<string,unknown>};
const tabs=[['Pipeline',BriefcaseBusiness],['Opportunities',Search],['Requirements',ClipboardCheck],['Drafting',FileText],['Budget',Calculator],['Documents',FileCheck2],['Submission',Target],['Awards',Award],['Compliance',ShieldCheck],['Memory',Library],['Settings',Settings]]as const;
const money=(n:number|null)=>n==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);

export default function GrantOSWorkspace(){
 const identity=useIdentity();
 const[applications,setApplications]=useState<Application[]>([]),[requirements,setRequirements]=useState<Requirement[]>([]),[activeId,setActiveId]=useState(''),[view,setView]=useState('Pipeline'),[adding,setAdding]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[amount,setAmount]=useState(''),[evidence,setEvidence]=useState('');
 const[form,setForm]=useState({title:'',amount:'',deadline:''});
 async function load(){if(identity.isBuilder||!supabase)return;setBusy(true);const[{data:a,error},{data:r}]=await Promise.all([supabase.from('grant_applications').select('id,title,stage,requested_amount,due_at,completion_percent,risk_level,authorization_state').order('due_at'),supabase.from('grant_requirements').select('id,application_id,label,slot_state,required,sort_order,evidence_reference').order('sort_order')]);if(error)setNotice(error.message);else{setApplications(a||[]);setRequirements((r||[])as Requirement[]);setActiveId(x=>x||a?.[0]?.id||'')}setBusy(false)}
 useEffect(()=>{load();if(identity.isBuilder||!supabase)return;const client=supabase;const c=client.channel('grantos-live').on('postgres_changes',{event:'*',schema:'public',table:'grant_applications'},load).on('postgres_changes',{event:'*',schema:'public',table:'grant_requirements'},load).subscribe();return()=>{client.removeChannel(c)}},[identity.isBuilder]);
 async function create(e:FormEvent){e.preventDefault();if(!supabase||!identity.user)return;setBusy(true);const{data,error}=await supabase.from('grant_applications').insert({organization_id:identity.organizationId,title:form.title,stage:'Prospecting',requested_amount:Number(form.amount)||null,due_at:form.deadline||null,completion_percent:0,risk_level:'medium',authorization_state:'ASK',owner_id:identity.user.id}).select('id,title,stage,requested_amount,due_at,completion_percent,risk_level,authorization_state').single();if(error)setNotice(error.message);else{setApplications(x=>[data,...x]);setActiveId(data.id);setAdding(false);setForm({title:'',amount:'',deadline:''});setNotice('Opportunity added to Prospecting.');setView('Requirements')}setBusy(false)}
 const active=applications.find(a=>a.id===activeId)||applications[0];
 const activeReqs=requirements.filter(r=>r.application_id===active?.id);
 async function updateApp(values:Record<string,unknown>,message:string){if(!supabase||!active)return;setBusy(true);const{error}=await supabase.from('grant_applications').update(values).eq('id',active.id);setBusy(false);if(error)setNotice(error.message);else{setNotice(message);await load()}}
 async function cycleRequirement(r:Requirement){if(!supabase)return;const next:r['slot_state']=r.slot_state==='Empty'?'Pending':r.slot_state==='Pending'?'Verified':'Empty';const{error}=await supabase.from('grant_requirements').update({slot_state:next}).eq('id',r.id);if(error)setNotice(error.message);else await load()}
 async function addRequirement(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase||!active)return;const f=new FormData(e.currentTarget);const label=String(f.get('label')||'').trim();if(!label)return;const{error}=await supabase.from('grant_requirements').insert({organization_id:identity.organizationId,application_id:active.id,label,slot_state:'Empty',required:true,sort_order:(activeReqs.length+1)*10});if(error)setNotice(error.message);else{e.currentTarget.reset();await load()}}
 async function saveEvidence(e:FormEvent){e.preventDefault();if(!supabase||!activeReqs[0])return;const target=activeReqs.find(r=>r.slot_state!=='Verified')||activeReqs[0];const{error}=await supabase.from('grant_requirements').update({evidence_reference:{reference:evidence,updated_at:new Date().toISOString()},slot_state:'Pending'}).eq('id',target.id);if(error)setNotice(error.message);else{setEvidence('');setNotice(`Evidence attached to ${target.label}.`);await load()}}
 const verified=activeReqs.filter(r=>r.slot_state==='Verified').length,required=activeReqs.filter(r=>r.required).length;
 const completion=required?Math.round((verified/required)*100):0;
 useEffect(()=>{if(active&&completion!==active.completion_percent&&!identity.isBuilder&&supabase){supabase.from('grant_applications').update({completion_percent:completion}).eq('id',active.id).then(()=>{})}},[completion,active?.id]);
 const metrics=useMemo(()=>({pipeline:applications.reduce((n,a)=>n+(a.requested_amount||0),0),due:applications.filter(a=>a.due_at).length,review:applications.filter(a=>a.stage==='In Review').length,verified:requirements.filter(r=>r.slot_state==='Verified').length}),[applications,requirements]);
 const appList=<>{applications.map(a=><button className={active?.id===a.id?'grant-card active':'grant-card'} onClick={()=>setActiveId(a.id)} key={a.id}><div><b>{a.title}</b><small>{a.stage} · Due {a.due_at?new Date(a.due_at).toLocaleDateString():'TBD'}</small></div><strong>{money(a.requested_amount)}</strong><span>{a.completion_percent}%</span></button>)}</>;
 const reqList=<div className="slot-list">{activeReqs.map(r=><article key={r.id} onClick={()=>cycleRequirement(r)} style={{cursor:'pointer'}}><span className={r.slot_state.toLowerCase()}>{r.slot_state}</span><div><b>{r.label}</b><small>{r.required?'Required':'Optional'} · Click to advance state</small>{r.evidence_reference&&Object.keys(r.evidence_reference).length>0&&<small>Evidence attached</small>}</div><CheckCircle2/></article>)}{active&&!activeReqs.length&&<div className="land-empty"><BookOpen/><b>No requirements yet</b><p>Add the first requirement below.</p></div>}</div>;
 return <div className="grantos"><div className="briefing grant-hero"><div><span className="eyebrow">SYS-GRANT-001 · GOVERNED FUNDING OPERATIONS</span><h2>GrantOS</h2><p>Opportunity intake, requirements, evidence, budget, readiness and internal submission authority now operate from separate views.</p></div><div className="land-actions"><button onClick={()=>setAdding(!adding)}><Plus/>New opportunity</button><button className="secondary" onClick={load}><RefreshCw/>{busy?'Syncing':'Refresh'}</button></div></div><div className="land-tabs">{tabs.map(([name,Icon])=><button className={view===name?'active':''} onClick={()=>setView(name)} key={name}><Icon/>{name}</button>)}</div>
 {adding&&<form className="panel grant-intake" onSubmit={create}><div className="panel-title"><div><span className="eyebrow">OPPORTUNITY INTAKE</span><h3>Add a funding opportunity</h3></div><ShieldCheck/></div><div className="land-form"><label>Opportunity title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Requested amount<input type="number" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Deadline<input type="date" value={form.deadline} onChange={e=>setForm({...form,deadline:e.target.value})}/></label></div><button disabled={busy}>Add to Prospecting</button></form>}
 <div className="metrics"><article className="metric green"><span>Pipeline value</span><strong>{money(metrics.pipeline)}</strong><small>Live applications</small></article><article className="metric cyan"><span>Tracked deadlines</span><strong>{metrics.due}</strong><small>Due dates</small></article><article className="metric amber"><span>In review</span><strong>{metrics.review}</strong><small>Eligibility gates</small></article><article className="metric purple"><span>Verified slots</span><strong>{metrics.verified}</strong><small>Evidence retained</small></article></div>
 {view==='Pipeline'&&<div className="grant-board"><section className="panel"><div className="panel-title"><div><span className="eyebrow">PIPELINE</span><h3>Applications</h3></div></div>{appList}</section><section className="panel"><div className="panel-title"><div><span className="eyebrow">ACTIVE APPLICATION</span><h3>{active?.title||'Select an application'}</h3></div>{active&&<span className="source">{active.authorization_state}</span>}</div>{active&&<><div className="grant-progress"><i><em style={{width:completion+'%'}}/></i><b>{completion}% verified</b></div><div className="control-grid">{['Prospecting','In Review','Drafting','Submission Ready','Active-Funded'].map(stage=><button key={stage} onClick={()=>updateApp({stage},`Moved to ${stage}.`)}>{stage}<Target/></button>)}</div></>}</section></div>}
 {view==='Opportunities'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">DISCOVERY QUEUE</span><h3>Funding opportunities</h3></div><Search/></div>{appList}<button onClick={()=>setAdding(true)}><Plus/>Add opportunity</button></section>}
 {view==='Requirements'&&<div className="grant-board"><section className="panel"><div className="panel-title"><div><span className="eyebrow">MARKER SLOTS</span><h3>{active?.title||'Select an application'}</h3></div></div>{reqList}</section><section className="panel"><div className="panel-title"><div><span className="eyebrow">NEW REQUIREMENT</span><h3>Add marker slot</h3></div><ClipboardCheck/></div><form className="campaign-form" onSubmit={addRequirement}><input name="label" required placeholder="Requirement label"/><button>Add requirement</button></form></section></div>}
 {view==='Drafting'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">DRAFT READINESS</span><h3>{active?.title||'Select an application'}</h3></div><FileText/></div>{reqList}<div className="control-grid"><button onClick={()=>updateApp({stage:'Drafting'},'Application moved into Drafting.')}>Start drafting<FileText/></button><button onClick={()=>updateApp({stage:'In Review'},'Application returned to review.')}>Return to review<ClipboardCheck/></button></div></section>}
 {view==='Budget'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">BUDGET</span><h3>{active?.title||'Select an application'}</h3></div><Calculator/></div><p>Current request: <b>{money(active?.requested_amount||null)}</b></p><form className="campaign-form" onSubmit={e=>{e.preventDefault();updateApp({requested_amount:Number(amount)||null},'Requested amount updated.');setAmount('')}}><input type="number" placeholder="New requested amount" value={amount} onChange={e=>setAmount(e.target.value)}/><button>Update budget</button></form></section>}
 {view==='Documents'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">EVIDENCE</span><h3>Documents & references</h3></div><FileCheck2/></div>{reqList}<form className="campaign-form" onSubmit={saveEvidence}><input required placeholder="Document URL, file reference, or source note" value={evidence} onChange={e=>setEvidence(e.target.value)}/><button>Attach to next open slot</button></form></section>}
 {view==='Submission'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">SUBMISSION GATE</span><h3>{active?.title||'Select an application'}</h3></div><Target/></div><div className="grant-progress"><i><em style={{width:completion+'%'}}/></i><b>{verified}/{required} required slots verified</b></div><div className="land-boundary"><ShieldCheck/><p><b>External portal boundary:</b> GrantOS can certify the package as Submission Ready here. It does not claim a funder portal submission unless an authorized submission connector exists.</p></div><button disabled={!active||verified<required} onClick={()=>updateApp({stage:'Submission Ready',authorization_state:'AUTHORIZED'},'Package certified Submission Ready.')}>Certify submission package</button></section>}
 {view==='Awards'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">AWARDS</span><h3>Active & funded</h3></div><Award/></div>{applications.filter(a=>a.stage==='Active-Funded').length?applications.filter(a=>a.stage==='Active-Funded').map(a=><div className="grant-card" key={a.id}><div><b>{a.title}</b><small>{money(a.requested_amount)}</small></div></div>):<div className="land-empty"><Award/><b>No funded awards recorded</b></div>}</section>}
 {view==='Compliance'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">COMPLIANCE</span><h3>Evidence status</h3></div><ShieldCheck/></div>{reqList}</section>}
 {view==='Memory'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">OPERATING MEMORY</span><h3>Current application record</h3></div><Library/></div>{active?<><p><b>{active.title}</b></p><p>Stage: {active.stage} · Authorization: {active.authorization_state} · Completion: {completion}%</p>{reqList}</>:<p>No application selected.</p>}</section>}
 {view==='Settings'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">GOVERNANCE</span><h3>GrantOS controls</h3></div><Settings/></div><div className="fabric-controls"><article><ShieldCheck/><b>Evidence first</b><p>Required slots move Empty → Pending → Verified and drive readiness.</p></article><article><Target/><b>No false submission</b><p>Submission Ready is internal certification until an authorized external connector confirms delivery.</p></article></div></section>}
 {notice&&<div className="land-notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}</div>;
}
