import{FormEvent,useEffect,useMemo,useState}from'react';
import{AlertTriangle,Building2,Calculator,CheckCircle2,ChevronRight,FileSearch,Landmark,Map,Plus,RefreshCw,ShieldCheck,Sparkles,UtilityPole}from'lucide-react';
import{supabase}from'../lib/supabase';
import{useIdentity}from'../auth/IdentityContext';

type Property={id:string;address:string;city:string|null;region:string|null;parcel_id:string|null;acreage:number|null;asking_price:number|null;estimated_value:number|null;opportunity_score:number|null;stage:string;source_class:string;summary:string|null;metadata?:Record<string,unknown>};
type Finding={id:string;property_id:string;category:string;finding:string;severity:string;evidence_class:string;requires_human_review:boolean;source_name?:string|null;source_url?:string|null};
type Market={market_code:string;state_code:string;market_name:string;county_names:string[];coastal:boolean};
type Provider={provider_code:string;provider_name:string;data_domain:string;adapter_type:string;auth_method:string;configuration_status:string;coverage:string[]};
type Demo={demo_id:string;market_code:string;display_name:string;property_type:string;acreage:number;mock_asking_price:number;mock_estimated_value:number;mock_score:number;mock_stage:string};
const views=[['Overview',Landmark],['Map Search',Map],['Results',FileSearch],['Property',Building2],['Hazards',AlertTriangle],['Utilities',UtilityPole],['Zoning',ShieldCheck],['Financial',Calculator],['Comps',Map],['AI Analyst',Sparkles],['Pipeline',CheckCircle2],['Diligence',CheckCircle2],['Documents',FileSearch],['Alerts',AlertTriangle],['Settings',ShieldCheck]]as const;
const money=(n:number|null)=>n==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);

export default function LandWeaverWorkspace(){
 const identity=useIdentity();
 const[properties,setProperties]=useState<Property[]>([]),[findings,setFindings]=useState<Finding[]>([]),[markets,setMarkets]=useState<Market[]>([]),[providers,setProviders]=useState<Provider[]>([]),[demos,setDemos]=useState<Demo[]>([]),[activeId,setActiveId]=useState(''),[view,setView]=useState('Overview'),[showForm,setShowForm]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[estimate,setEstimate]=useState(''),[documentRef,setDocumentRef]=useState('');
 const[form,setForm]=useState({address:'',city:'',region:'FL',parcel:'',acreage:'',price:'',summary:''});
 async function load(){if(identity.isBuilder||!supabase)return;setBusy(true);const[{data:p,error},{data:f},{data:m},{data:pr},{data:d}]=await Promise.all([supabase.from('land_properties').select('id,address,city,region,parcel_id,acreage,asking_price,estimated_value,opportunity_score,stage,source_class,summary,metadata').order('updated_at',{ascending:false}),supabase.from('land_assessments').select('id,property_id,category,finding,severity,evidence_class,requires_human_review,source_name,source_url').order('created_at',{ascending:false}),supabase.from('land_markets').select('*').eq('active',true).order('priority'),supabase.from('land_data_providers').select('provider_code,provider_name,data_domain,adapter_type,auth_method,configuration_status,coverage').order('data_domain'),supabase.from('land_demo_properties').select('*').order('market_code')]);if(error)setNotice(error.message);else{setProperties(p||[]);setFindings(f||[]);setMarkets(m||[]);setProviders(pr||[]);setDemos(d||[]);setActiveId(x=>x||p?.[0]?.id||'')}setBusy(false)}
 useEffect(()=>{load();if(identity.isBuilder||!supabase)return;const client=supabase;const c=client.channel('landweaver-live').on('postgres_changes',{event:'*',schema:'public',table:'land_properties'},load).on('postgres_changes',{event:'*',schema:'public',table:'land_assessments'},load).subscribe();return()=>{client.removeChannel(c)}},[identity.isBuilder]);
 async function create(e:FormEvent){e.preventDefault();if(!supabase||!identity.user)return;setBusy(true);const{data,error}=await supabase.from('land_properties').insert({owner_id:identity.user.id,address:form.address.trim(),city:form.city||null,region:form.region||null,parcel_id:form.parcel||null,acreage:form.acreage?Number(form.acreage):null,asking_price:form.price?Number(form.price):null,summary:form.summary||null,source_class:'user_entered',freshness_state:'current'}).select('id').single();setBusy(false);if(error)setNotice(error.message);else{setActiveId(data.id);setShowForm(false);setForm({address:'',city:'',region:'FL',parcel:'',acreage:'',price:'',summary:''});setNotice('Property entered into governed screening.');setView('Property');await load()}}
 const active=properties.find(p=>p.id===activeId)||properties[0];
 const activeFindings=findings.filter(f=>f.property_id===active?.id);
 const filtered=properties.filter(p=>!query.trim()||`${p.address} ${p.city||''} ${p.region||''} ${p.parcel_id||''}`.toLowerCase().includes(query.toLowerCase()));
 async function updateProperty(values:Record<string,unknown>,message:string){if(!supabase||!active)return;setBusy(true);const{error}=await supabase.from('land_properties').update(values).eq('id',active.id);setBusy(false);if(error)setNotice(error.message);else{setNotice(message);await load()}}
 async function addAssessment(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase||!active)return;const f=new FormData(e.currentTarget);const{error}=await supabase.from('land_assessments').insert({property_id:active.id,category:String(f.get('category')),finding:String(f.get('finding')),severity:String(f.get('severity')),evidence_class:'user_supplied',source_name:String(f.get('source')||'User review'),source_url:String(f.get('url')||'')||null,requires_human_review:true});if(error)setNotice(error.message);else{e.currentTarget.reset();setNotice('Assessment added with provenance.');await load()}}
 async function runAnalyst(){if(!active)return;const high=activeFindings.filter(f=>['high','critical'].includes(f.severity)).length;const medium=activeFindings.filter(f=>f.severity==='medium').length;let score=70-high*15-medium*5;if(active.asking_price&&active.estimated_value){const spread=(active.estimated_value-active.asking_price)/active.asking_price;score+=Math.max(-20,Math.min(20,Math.round(spread*100)))}if(active.acreage&&active.acreage>=5)score+=5;score=Math.max(0,Math.min(100,score));await updateProperty({opportunity_score:score,stage:score>=75?'screening':'under_review'},`Evidence-aware score updated to ${score}/100.`)}
 async function addDocument(e:FormEvent){e.preventDefault();if(!active)return;const current=Array.isArray(active.metadata?.document_refs)?active.metadata?.document_refs as unknown[]:[];await updateProperty({metadata:{...(active.metadata||{}),document_refs:[...current,{reference:documentRef,added_at:new Date().toISOString()}]}},'Document reference added.');setDocumentRef('')}
 const categoryFindings=(pattern:string)=>activeFindings.filter(f=>f.category.toLowerCase().includes(pattern));
 const metrics=useMemo(()=>({pipeline:properties.length,review:properties.filter(p=>['screening','due_diligence','under_review'].includes(p.stage)).length,risks:findings.filter(f=>['high','critical'].includes(f.severity)).length,value:properties.reduce((s,p)=>s+(p.estimated_value||p.asking_price||0),0)}),[properties,findings]);
 const propertyList=<div className="property-list">{filtered.map(p=><button className={active?.id===p.id?'property active':'property'} onClick={()=>setActiveId(p.id)} key={p.id}><div><b>{p.address}</b><small>{[p.city,p.region,p.acreage?`${p.acreage} acres`:null].filter(Boolean).join(' · ')}</small></div><span>{p.stage.replaceAll('_',' ')}</span><ChevronRight/></button>)}{!filtered.length&&<div className="land-empty"><Landmark/><b>No matching properties</b></div>}</div>;
 const findingsList=(items:Finding[])=>items.length?items.map(f=><div className="finding" key={f.id}><span className={f.severity}>{f.severity}</span><div><b>{f.category}</b><p>{f.finding}</p><small>{f.evidence_class.replaceAll('_',' ')}{f.source_name?` · ${f.source_name}`:''}{f.requires_human_review?' · Human review required':''}</small></div></div>):<p className="muted">No sourced findings in this category yet.</p>;
 return <div className="landweaver"><div className="briefing land-hero"><div><span className="eyebrow">SYS-LAND-001 · PROPERTY INTELLIGENCE</span><h2>LandWeaver</h2><p>Search your portfolio, manage property records, document evidence, assess risk, score opportunities and move work through diligence.</p></div><div className="land-actions"><button onClick={()=>setShowForm(!showForm)}><Plus/>New property</button><button className="secondary" onClick={load}><RefreshCw/>{busy?'Syncing':'Refresh'}</button></div></div><div className="land-tabs">{views.map(([name,Icon])=><button className={view===name?'active':''} onClick={()=>setView(name)} key={name}><Icon/>{name}</button>)}</div>
 {showForm&&<form className="panel land-intake" onSubmit={create}><div className="panel-title"><div><span className="eyebrow">GOVERNED INTAKE</span><h3>Add a property opportunity</h3></div><ShieldCheck/></div><div className="land-form"><label>Address<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})} required/></label><label>City<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>State<input value={form.region} onChange={e=>setForm({...form,region:e.target.value})}/></label><label>Parcel ID<input value={form.parcel} onChange={e=>setForm({...form,parcel:e.target.value})}/></label><label>Acres<input type="number" step="0.01" value={form.acreage} onChange={e=>setForm({...form,acreage:e.target.value})}/></label><label>Asking price<input type="number" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label className="wide">Notes<textarea value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/></label></div><button disabled={busy}>Add to screening</button></form>}
 <div className="metrics"><article className="metric cyan"><span>Properties</span><strong>{metrics.pipeline}</strong><small>Live portfolio</small></article><article className="metric amber"><span>In diligence</span><strong>{metrics.review}</strong><small>Screening / review</small></article><article className="metric purple"><span>Material risks</span><strong>{metrics.risks}</strong><small>High / critical findings</small></article><article className="metric green"><span>Tracked value</span><strong>{money(metrics.value)}</strong><small>Asking / estimated</small></article></div>
 {view==='Overview'&&<div className="land-grid"><section className="panel"><div className="panel-title"><div><span className="eyebrow">PORTFOLIO</span><h3>Current opportunities</h3></div></div>{propertyList}</section><section className="panel"><div className="panel-title"><div><span className="eyebrow">LAUNCH MARKETS</span><h3>Configured coverage</h3></div><Map/></div><div className="market-chips">{markets.map(m=><span key={m.market_code}>{m.market_name}, {m.state_code}{m.coastal?' · Coastal':''}</span>)}</div></section></div>}
 {view==='Map Search'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">PORTFOLIO SEARCH</span><h3>Find property by address, city, state or parcel</h3></div><Map/></div><label className="auth-email">Search<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tampa, FL or parcel ID"/></label>{propertyList}<div className="land-boundary"><ShieldCheck/><p><b>Map tile boundary:</b> live interactive parcel maps require a configured mapping provider. Search and property operations remain available without inventing map data.</p></div></section>}
 {view==='Results'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">SEARCH RESULTS</span><h3>{filtered.length} properties</h3></div><FileSearch/></div>{propertyList}</section>}
 {view==='Property'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">PROPERTY FILE</span><h3>{active?.address||'Select a property'}</h3></div>{active&&<span className="source">{active.source_class.replaceAll('_',' ')}</span>}</div>{active?<><div className="land-facts"><div><small>Parcel</small><b>{active.parcel_id||'Unknown'}</b></div><div><small>Asking</small><b>{money(active.asking_price)}</b></div><div><small>Estimated</small><b>{money(active.estimated_value)}</b></div><div><small>Score</small><b>{active.opportunity_score??'Pending'}</b></div></div><p>{active.summary||'No analyst summary entered.'}</p>{findingsList(activeFindings)}</>:<div className="land-empty"><Building2/><b>Select a property</b></div>}</section>}
 {view==='Hazards'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">HAZARD REVIEW</span><h3>{active?.address||'Select a property'}</h3></div><AlertTriangle/></div>{findingsList([...categoryFindings('hazard'),...categoryFindings('flood'),...categoryFindings('environment')])}</section>}
 {view==='Utilities'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">UTILITY REVIEW</span><h3>{active?.address||'Select a property'}</h3></div><UtilityPole/></div>{findingsList(categoryFindings('util'))}</section>}
 {view==='Zoning'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">ZONING REVIEW</span><h3>{active?.address||'Select a property'}</h3></div><ShieldCheck/></div>{findingsList(categoryFindings('zon'))}</section>}
 {view==='Financial'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">FINANCIAL SCREEN</span><h3>{active?.address||'Select a property'}</h3></div><Calculator/></div>{active&&<><div className="land-facts"><div><small>Asking</small><b>{money(active.asking_price)}</b></div><div><small>Estimated</small><b>{money(active.estimated_value)}</b></div><div><small>Spread</small><b>{active.asking_price&&active.estimated_value?money(active.estimated_value-active.asking_price):'—'}</b></div></div><form className="campaign-form" onSubmit={e=>{e.preventDefault();updateProperty({estimated_value:Number(estimate)||null},'Estimated value updated.');setEstimate('')}}><input type="number" value={estimate} onChange={e=>setEstimate(e.target.value)} placeholder="Estimated value"/><button>Save estimate</button></form></>}</section>}
 {view==='Comps'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">COMPARABLE EVIDENCE</span><h3>{active?.address||'Select a property'}</h3></div><Map/></div>{findingsList(categoryFindings('comp'))}</section>}
 {view==='AI Analyst'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">EVIDENCE-AWARE ANALYST</span><h3>{active?.address||'Select a property'}</h3></div><Sparkles/></div><p>The score uses only values and findings currently present in the governed property file. Missing facts are not invented.</p><button disabled={!active||busy} onClick={runAnalyst}><Sparkles/>Run opportunity analysis</button>{active&&<p>Current score: <b>{active.opportunity_score??'Pending'}</b></p>}</section>}
 {view==='Pipeline'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">ACQUISITION PIPELINE</span><h3>{active?.address||'Select a property'}</h3></div><CheckCircle2/></div>{propertyList}{active&&<div className="control-grid">{['discovery','screening','under_review','due_diligence','approved','rejected'].map(stage=><button key={stage} onClick={()=>updateProperty({stage},`Moved to ${stage.replaceAll('_',' ')}.`)}>{stage.replaceAll('_',' ')}<ChevronRight/></button>)}</div>}</section>}
 {view==='Diligence'&&<div className="land-grid"><section className="panel"><div className="panel-title"><div><span className="eyebrow">DILIGENCE FILE</span><h3>{active?.address||'Select a property'}</h3></div><ShieldCheck/></div>{findingsList(activeFindings)}</section><section className="panel"><div className="panel-title"><div><span className="eyebrow">ADD EVIDENCE</span><h3>Assessment</h3></div><Plus/></div><form className="campaign-form" onSubmit={addAssessment}><input name="category" required placeholder="Category: zoning, flood, utilities…"/><input name="finding" required placeholder="Finding"/><select name="severity"><option>info</option><option>medium</option><option>high</option><option>critical</option></select><input name="source" placeholder="Source name"/><input name="url" placeholder="Source URL"/><button>Add assessment</button></form></section></div>}
 {view==='Documents'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">DOCUMENT REFERENCES</span><h3>{active?.address||'Select a property'}</h3></div><FileSearch/></div>{active&&<><form className="campaign-form" onSubmit={addDocument}><input required value={documentRef} onChange={e=>setDocumentRef(e.target.value)} placeholder="Drive URL, file ID or document note"/><button>Add document reference</button></form><pre>{JSON.stringify(active.metadata?.document_refs||[],null,2)}</pre></>}</section>}
 {view==='Alerts'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">MATERIAL ALERTS</span><h3>High & critical findings</h3></div><AlertTriangle/></div>{findingsList(findings.filter(f=>['high','critical'].includes(f.severity)))}</section>}
 {view==='Settings'&&<section className="panel provider-panel"><div className="panel-title"><div><span className="eyebrow">API & SOURCE SETTINGS</span><h3>Provider configuration registry</h3></div><ShieldCheck/></div><div className="provider-grid">{providers.map(p=><article key={p.provider_code}><div><b>{p.provider_name}</b><span>{p.configuration_status.replaceAll('_',' ')}</span></div><small>{p.data_domain.replaceAll('_',' ')} · {p.adapter_type.replaceAll('_',' ')} · auth: {p.auth_method.replaceAll('_',' ')}</small><p>{p.coverage.join(' · ')}</p></article>)}</div><div className="demo-grid">{demos.map(d=><article key={d.demo_id}><b>{d.display_name}</b><small>SYNTHETIC · {d.property_type}</small><div><span>{money(d.mock_asking_price)}</span><strong>{d.mock_score}/100</strong></div></article>)}</div></section>}
 {notice&&<div className="land-notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}</div>;
}
