import {FormEvent,useEffect,useMemo,useState} from 'react';
import {AlertTriangle,Building2,Calculator,CheckCircle2,ChevronRight,FileSearch,Landmark,Map,Plus,RefreshCw,ShieldCheck,Sparkles,UtilityPole} from 'lucide-react';
import {supabase} from '../lib/supabase';
import {useIdentity} from '../auth/IdentityContext';
type Property={id:string;address:string;city:string|null;region:string|null;parcel_id:string|null;acreage:number|null;asking_price:number|null;estimated_value:number|null;opportunity_score:number|null;stage:string;source_class:string;summary:string|null};
type Finding={id:string;property_id:string;category:string;finding:string;severity:string;evidence_class:string;requires_human_review:boolean};
type Market={market_code:string;state_code:string;market_name:string;county_names:string[];coastal:boolean};
type Provider={provider_code:string;provider_name:string;data_domain:string;adapter_type:string;auth_method:string;configuration_status:string;coverage:string[]};
type Demo={demo_id:string;market_code:string;display_name:string;property_type:string;acreage:number;mock_asking_price:number;mock_estimated_value:number;mock_score:number;mock_stage:string};
const views=[['Overview',Landmark],['Map Search',Map],['Results',FileSearch],['Property',Building2],['Hazards',AlertTriangle],['Utilities',UtilityPole],['Zoning',ShieldCheck],['Financial',Calculator],['Comps',Map],['AI Analyst',Sparkles],['Pipeline',CheckCircle2],['Diligence',CheckCircle2],['Documents',FileSearch],['Alerts',AlertTriangle],['Settings',ShieldCheck]] as const;
const money=(n:number|null)=>n==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const BUILDER_MARKETS:Market[]=[
 ...[['FL-TAMPA','Tampa'],['FL-ORLANDO','Orlando'],['FL-PLANTATION','Plantation'],['FL-SANFORD','Sanford']].map(([market_code,market_name],priority)=>({market_code,market_name,state_code:'FL',county_names:[],coastal:false,priority})),
 ...[['GA-ATLANTA','Atlanta'],['GA-DECATUR','Decatur'],['GA-AUGUSTA','Augusta'],['GA-SAVANNAH','Savannah'],['GA-NORCROSS','Norcross']].map(([market_code,market_name],priority)=>({market_code,market_name,state_code:'GA',county_names:[],coastal:market_name==='Savannah',priority})),
 ...[['AL-MOBILE','Mobile'],['AL-GULF-SHORES','Gulf Shores'],['AL-ORANGE-BEACH','Orange Beach'],['AL-FOLEY','Foley'],['AL-DAPHNE','Daphne'],['AL-FAIRHOPE','Fairhope']].map(([market_code,market_name],priority)=>({market_code,market_name,state_code:'AL',county_names:[],coastal:true,priority}))
];
const BUILDER_PROVIDERS:Provider[]=[
 ['US-CENSUS-GEOCODER','U.S. Census Geocoder','geocoding','rest_api','none','available'],['FEMA-NFHL','FEMA National Flood Hazard Layer','flood_hazard','rest_api','none','available'],
 ['FL-GIO','Florida Geographic Information Office','state_gis','open_data','none','available'],['GA-DOR-DIGEST','Georgia Department of Revenue Tax Digest','tax_digest','download','none','available'],
 ['FL-HILLSBOROUGH-PA','Hillsborough County Property Appraiser','parcel','manual','none','manual_only'],['FL-ORANGE-PA','Orange County Property Appraiser','parcel','manual','none','manual_only'],
 ['FL-BROWARD-PA','Broward County Property Appraiser','parcel','manual','none','manual_only'],['FL-SEMINOLE-PA','Seminole County Property Appraiser','parcel','manual','none','manual_only'],
 ['GA-QPUBLIC','Georgia County Property Records','parcel','licensed','account','requires_license'],['AL-PARCELS','Alabama Parcel and County Sources','parcel','manual','none','manual_only'],
 ['MAP-TILES','Map tile and geocoding provider','mapping','rest_api','api_key','requires_credentials'],['LICENSED-LISTINGS','Licensed listings and comparable sales provider','listings','licensed','account','requires_license']
].map(([provider_code,provider_name,data_domain,adapter_type,auth_method,configuration_status])=>({provider_code,provider_name,data_domain,adapter_type,auth_method,configuration_status,coverage:['FL','GA','AL']} as Provider));
const BUILDER_DEMOS:Demo[]=BUILDER_MARKETS.map(m=>({demo_id:'DEMO-'+m.market_code,market_code:m.market_code,display_name:m.market_name+' Opportunity Alpha',property_type:m.coastal?'coastal mixed-use land':'development parcel',acreage:m.coastal?6.4:12.5,mock_asking_price:m.state_code==='FL'?785000:m.state_code==='GA'?625000:545000,mock_estimated_value:m.state_code==='FL'?910000:m.state_code==='GA'?740000:660000,mock_score:m.coastal?74:82,mock_stage:'screening'}));
export default function LandWeaverWorkspace(){
 const identity=useIdentity();
 const [properties,setProperties]=useState<Property[]>([]),[findings,setFindings]=useState<Finding[]>([]),[markets,setMarkets]=useState<Market[]>([]),[providers,setProviders]=useState<Provider[]>([]),[demos,setDemos]=useState<Demo[]>([]),[activeId,setActiveId]=useState(''),[view,setView]=useState('Overview'),[showForm,setShowForm]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const [form,setForm]=useState({address:'',city:'',region:'FL',parcel:'',acreage:'',price:'',summary:''});
 async function load(){if(identity.isBuilder){setMarkets(BUILDER_MARKETS);setProviders(BUILDER_PROVIDERS);setDemos(BUILDER_DEMOS);setBusy(false);return}if(!supabase)return;setBusy(true);const[{data:p,error},{data:f},{data:m},{data:pr},{data:d}]=await Promise.all([supabase.from('land_properties').select('*').order('updated_at',{ascending:false}),supabase.from('land_assessments').select('*').order('created_at',{ascending:false}),supabase.from('land_markets').select('*').eq('active',true).order('priority'),supabase.from('land_data_providers').select('provider_code,provider_name,data_domain,adapter_type,auth_method,configuration_status,coverage').order('data_domain'),supabase.from('land_demo_properties').select('*').order('market_code')]);if(error)setNotice(error.message);else{setProperties(p||[]);setFindings(f||[]);setMarkets(m||[]);setProviders(pr||[]);setDemos(d||[]);if(!activeId&&p?.[0])setActiveId(p[0].id)}setBusy(false)}
 useEffect(()=>{load();if(identity.isBuilder)return;const client=supabase;if(!client)return;const c=client.channel('landweaver-live').on('postgres_changes',{event:'*',schema:'public',table:'land_properties'},load).on('postgres_changes',{event:'*',schema:'public',table:'land_assessments'},load).subscribe();return()=>{client.removeChannel(c)}},[identity.isBuilder]);
 async function create(e:FormEvent){e.preventDefault();setBusy(true);if(identity.isBuilder){const item:Property={id:crypto.randomUUID(),address:form.address.trim(),city:form.city||null,region:form.region||null,parcel_id:form.parcel||null,acreage:form.acreage?Number(form.acreage):null,asking_price:form.price?Number(form.price):null,estimated_value:null,opportunity_score:null,stage:'screening',source_class:'builder_mock',summary:form.summary||null};setProperties(p=>[item,...p]);setActiveId(item.id);setNotice('Added to this builder session. Production writes remain locked.');setShowForm(false);setForm({address:'',city:'',region:'FL',parcel:'',acreage:'',price:'',summary:''});setBusy(false);return}if(!supabase)return;const{data:{user}}=await supabase.auth.getUser();if(!user){setNotice('Sign in is required.');setBusy(false);return}const{data,error}=await supabase.from('land_properties').insert({owner_id:user.id,address:form.address.trim(),city:form.city||null,region:form.region||null,parcel_id:form.parcel||null,acreage:form.acreage?Number(form.acreage):null,asking_price:form.price?Number(form.price):null,summary:form.summary||null,source_class:'user_entered',freshness_state:'current'}).select().single();if(error)setNotice(error.message);else{setNotice('Property entered into governed screening.');setActiveId(data.id);setShowForm(false);setForm({address:'',city:'',region:'FL',parcel:'',acreage:'',price:'',summary:''});await load()}setBusy(false)}
 const active=properties.find(p=>p.id===activeId)||properties[0],activeFindings=findings.filter(f=>f.property_id===active?.id);
 const metrics=useMemo(()=>({pipeline:properties.length,review:properties.filter(p=>['screening','due_diligence','under_review'].includes(p.stage)).length,risks:findings.filter(f=>['high','critical'].includes(f.severity)).length,value:properties.reduce((s,p)=>s+(p.estimated_value||p.asking_price||0),0)}),[properties,findings]);
 return <div className="landweaver"><div className="briefing land-hero"><div><span className="eyebrow">SYS-LAND-001 · CONNECTED PROPERTY INTELLIGENCE</span><h2>Find, verify and govern the next property decision.</h2><p>Facts, vendor data, calculations and AI interpretation remain separated through acquisition review.</p></div><div className="land-actions"><button onClick={()=>setShowForm(!showForm)}><Plus/>New property</button><button className="secondary" onClick={load}><RefreshCw/>{busy?'Syncing':'Refresh'}</button></div></div>
 <div className="land-tabs">{views.map(([name,Icon])=><button className={view===name?'active':''} onClick={()=>setView(name)} key={name}><Icon/>{name}</button>)}</div>
 {showForm&&<form className="panel land-intake" onSubmit={create}><div className="panel-title"><div><span className="eyebrow">GOVERNED INTAKE</span><h3>Add a property opportunity</h3></div><ShieldCheck/></div><div className="land-form"><label>Address<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})} required/></label><label>City<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>State<input value={form.region} onChange={e=>setForm({...form,region:e.target.value})}/></label><label>Parcel ID<input value={form.parcel} onChange={e=>setForm({...form,parcel:e.target.value})}/></label><label>Acres<input type="number" step="0.01" value={form.acreage} onChange={e=>setForm({...form,acreage:e.target.value})}/></label><label>Asking price<input type="number" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label className="wide">Notes<textarea value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/></label></div><button disabled={busy}>Add to screening</button></form>}
 <div className="metrics"><article className="metric cyan"><span>Launch markets</span><strong>{markets.length}</strong><small>FL · GA · AL Gulf</small></article><article className="metric amber"><span>User properties</span><strong>{metrics.pipeline}</strong><small>Accuracy-owned records</small></article><article className="metric purple"><span>Data adapters</span><strong>{providers.length}</strong><small>API-ready registry</small></article><article className="metric green"><span>Demo portfolio</span><strong>{demos.length}</strong><small>Synthetic records</small></article></div>
 {view==='Settings'?<section className="panel provider-panel"><div className="panel-title"><div><span className="eyebrow">API & SOURCE SETTINGS</span><h3>Provider configuration registry</h3></div><ShieldCheck/></div><p className="muted">Public sources are enabled only where automated use is allowed. Licensed adapters remain off until the user supplies an authorized account; raw secrets are never stored here.</p><div className="provider-grid">{providers.map(p=><article key={p.provider_code}><div><b>{p.provider_name}</b><span>{p.configuration_status.replaceAll('_',' ')}</span></div><small>{p.data_domain.replaceAll('_',' ')} · {p.adapter_type.replaceAll('_',' ')} · auth: {p.auth_method.replaceAll('_',' ')}</small><p>{p.coverage.join(' · ')}</p></article>)}</div></section>:<section className="panel market-panel"><div className="panel-title"><div><span className="eyebrow">REGIONAL LAUNCH BUNDLE</span><h3>Configured markets and synthetic workflow records</h3></div><span className="source">MOCK MODE</span></div><div className="market-chips">{markets.map(m=><span key={m.market_code}>{m.market_name}, {m.state_code}{m.coastal?' · Gulf/Coastal':''}</span>)}</div><div className="demo-grid">{demos.map(d=><article key={d.demo_id}><b>{d.display_name}</b><small>{d.property_type} · {d.acreage} acres</small><div><span>{money(d.mock_asking_price)}</span><strong>{d.mock_score}/100</strong></div><p>SYNTHETIC · {d.mock_stage}</p></article>)}</div></section>}
 <div className="land-grid"><section className="panel"><div className="panel-title"><div><span className="eyebrow">ACQUISITION PIPELINE</span><h3>{view}</h3></div><span className="live"><i/>Supabase</span></div><div className="property-list">{properties.map(p=><button className={active?.id===p.id?'property active':'property'} onClick={()=>setActiveId(p.id)} key={p.id}><div><b>{p.address}</b><small>{[p.city,p.region,p.acreage?String(p.acreage)+' acres':null].filter(Boolean).join(' · ')}</small></div><span>{p.stage.replaceAll('_',' ')}</span><ChevronRight/></button>)}{!properties.length&&<div className="land-empty"><Landmark/><b>No properties entered</b><p>Start with New property. Provider data remains unknown until an authorized adapter is connected.</p></div>}</div></section>
 <section className="panel"><div className="panel-title"><div><span className="eyebrow">EVIDENCE-AWARE PROPERTY FILE</span><h3>{active?.address||'Select a property'}</h3></div>{active&&<span className="source">{active.source_class.replaceAll('_',' ')}</span>}</div>{active?<><div className="land-facts"><div><small>Parcel</small><b>{active.parcel_id||'Unknown'}</b></div><div><small>Asking</small><b>{money(active.asking_price)}</b></div><div><small>Estimated</small><b>{money(active.estimated_value)}</b></div><div><small>Score</small><b>{active.opportunity_score??'Pending'}</b></div></div><p className="land-summary">{active.summary||'No analyst summary has been entered.'}</p><h4>Assessments & provenance</h4>{activeFindings.map(f=><div className="finding" key={f.id}><span className={f.severity}>{f.severity}</span><div><b>{f.category}</b><p>{f.finding}</p><small>{f.evidence_class.replaceAll('_',' ')} · {f.requires_human_review?'Human review required':'Reviewed'}</small></div></div>)}{!activeFindings.length&&<p className="muted">No sourced assessments yet. Unknown is retained instead of being presented as fact.</p>}<div className="land-boundary"><ShieldCheck/><p><b>Authority boundary:</b> AI findings are decision support—not title, zoning, appraisal, environmental, legal or engineering certification. Commitments require executive approval and an audit event.</p></div></>:<div className="land-empty"><FileSearch/><b>Property file awaiting intake</b></div>}</section></div>{notice&&<div className="land-notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}</div>
}
