import {FormEvent,useEffect,useMemo,useState} from 'react';
import {AlertTriangle,Building2,Calculator,CheckCircle2,ChevronRight,FileSearch,Landmark,Map,Plus,RefreshCw,ShieldCheck,Sparkles,UtilityPole} from 'lucide-react';
import {supabase} from '../lib/supabase';
type Property={id:string;address:string;city:string|null;region:string|null;parcel_id:string|null;acreage:number|null;asking_price:number|null;estimated_value:number|null;opportunity_score:number|null;stage:string;source_class:string;summary:string|null};
type Finding={id:string;property_id:string;category:string;finding:string;severity:string;evidence_class:string;requires_human_review:boolean};
const views=[['Overview',Landmark],['Map Search',Map],['Results',FileSearch],['Property',Building2],['Hazards',AlertTriangle],['Utilities',UtilityPole],['Zoning',ShieldCheck],['Financial',Calculator],['Comps',Map],['AI Analyst',Sparkles],['Pipeline',CheckCircle2],['Diligence',CheckCircle2],['Documents',FileSearch],['Alerts',AlertTriangle],['Settings',ShieldCheck]] as const;
const money=(n:number|null)=>n==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
export default function LandWeaverWorkspace(){
 const [properties,setProperties]=useState<Property[]>([]),[findings,setFindings]=useState<Finding[]>([]),[activeId,setActiveId]=useState(''),[view,setView]=useState('Overview'),[showForm,setShowForm]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const [form,setForm]=useState({address:'',city:'',region:'FL',parcel:'',acreage:'',price:'',summary:''});
 async function load(){if(!supabase)return;setBusy(true);const[{data:p,error},{data:f}]=await Promise.all([supabase.from('land_properties').select('*').order('updated_at',{ascending:false}),supabase.from('land_assessments').select('*').order('created_at',{ascending:false})]);if(error)setNotice(error.message);else{setProperties(p||[]);setFindings(f||[]);if(!activeId&&p?.[0])setActiveId(p[0].id)}setBusy(false)}
 useEffect(()=>{load();const client=supabase;if(!client)return;const c=client.channel('landweaver-live').on('postgres_changes',{event:'*',schema:'public',table:'land_properties'},load).on('postgres_changes',{event:'*',schema:'public',table:'land_assessments'},load).subscribe();return()=>{client.removeChannel(c)}},[]);
 async function create(e:FormEvent){e.preventDefault();if(!supabase)return;setBusy(true);const{data:{user}}=await supabase.auth.getUser();if(!user){setNotice('Sign in is required.');setBusy(false);return}const{data,error}=await supabase.from('land_properties').insert({owner_id:user.id,address:form.address.trim(),city:form.city||null,region:form.region||null,parcel_id:form.parcel||null,acreage:form.acreage?Number(form.acreage):null,asking_price:form.price?Number(form.price):null,summary:form.summary||null,source_class:'user_entered',freshness_state:'current'}).select().single();if(error)setNotice(error.message);else{setNotice('Property entered into governed screening.');setActiveId(data.id);setShowForm(false);setForm({address:'',city:'',region:'FL',parcel:'',acreage:'',price:'',summary:''});await load()}setBusy(false)}
 const active=properties.find(p=>p.id===activeId)||properties[0],activeFindings=findings.filter(f=>f.property_id===active?.id);
 const metrics=useMemo(()=>({pipeline:properties.length,review:properties.filter(p=>['screening','due_diligence','under_review'].includes(p.stage)).length,risks:findings.filter(f=>['high','critical'].includes(f.severity)).length,value:properties.reduce((s,p)=>s+(p.estimated_value||p.asking_price||0),0)}),[properties,findings]);
 return <div className="landweaver"><div className="briefing land-hero"><div><span className="eyebrow">SYS-LAND-001 · CONNECTED PROPERTY INTELLIGENCE</span><h2>Find, verify and govern the next property decision.</h2><p>Facts, vendor data, calculations and AI interpretation remain separated through acquisition review.</p></div><div className="land-actions"><button onClick={()=>setShowForm(!showForm)}><Plus/>New property</button><button className="secondary" onClick={load}><RefreshCw/>{busy?'Syncing':'Refresh'}</button></div></div>
 <div className="land-tabs">{views.map(([name,Icon])=><button className={view===name?'active':''} onClick={()=>setView(name)} key={name}><Icon/>{name}</button>)}</div>
 {showForm&&<form className="panel land-intake" onSubmit={create}><div className="panel-title"><div><span className="eyebrow">GOVERNED INTAKE</span><h3>Add a property opportunity</h3></div><ShieldCheck/></div><div className="land-form"><label>Address<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})} required/></label><label>City<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>State<input value={form.region} onChange={e=>setForm({...form,region:e.target.value})}/></label><label>Parcel ID<input value={form.parcel} onChange={e=>setForm({...form,parcel:e.target.value})}/></label><label>Acres<input type="number" step="0.01" value={form.acreage} onChange={e=>setForm({...form,acreage:e.target.value})}/></label><label>Asking price<input type="number" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label className="wide">Notes<textarea value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/></label></div><button disabled={busy}>Add to screening</button></form>}
 <div className="metrics"><article className="metric cyan"><span>Pipeline</span><strong>{metrics.pipeline}</strong><small>Tracked properties</small></article><article className="metric amber"><span>In review</span><strong>{metrics.review}</strong><small>Human diligence</small></article><article className="metric purple"><span>Material risks</span><strong>{metrics.risks}</strong><small>High or critical</small></article><article className="metric green"><span>Modeled value</span><strong>{money(metrics.value)}</strong><small>Evidence-dependent</small></article></div>
 <div className="land-grid"><section className="panel"><div className="panel-title"><div><span className="eyebrow">ACQUISITION PIPELINE</span><h3>{view}</h3></div><span className="live"><i/>Supabase</span></div><div className="property-list">{properties.map(p=><button className={active?.id===p.id?'property active':'property'} onClick={()=>setActiveId(p.id)} key={p.id}><div><b>{p.address}</b><small>{[p.city,p.region,p.acreage?String(p.acreage)+' acres':null].filter(Boolean).join(' · ')}</small></div><span>{p.stage.replaceAll('_',' ')}</span><ChevronRight/></button>)}{!properties.length&&<div className="land-empty"><Landmark/><b>No properties entered</b><p>Start with New property. Provider data remains unknown until an authorized adapter is connected.</p></div>}</div></section>
 <section className="panel"><div className="panel-title"><div><span className="eyebrow">EVIDENCE-AWARE PROPERTY FILE</span><h3>{active?.address||'Select a property'}</h3></div>{active&&<span className="source">{active.source_class.replaceAll('_',' ')}</span>}</div>{active?<><div className="land-facts"><div><small>Parcel</small><b>{active.parcel_id||'Unknown'}</b></div><div><small>Asking</small><b>{money(active.asking_price)}</b></div><div><small>Estimated</small><b>{money(active.estimated_value)}</b></div><div><small>Score</small><b>{active.opportunity_score??'Pending'}</b></div></div><p className="land-summary">{active.summary||'No analyst summary has been entered.'}</p><h4>Assessments & provenance</h4>{activeFindings.map(f=><div className="finding" key={f.id}><span className={f.severity}>{f.severity}</span><div><b>{f.category}</b><p>{f.finding}</p><small>{f.evidence_class.replaceAll('_',' ')} · {f.requires_human_review?'Human review required':'Reviewed'}</small></div></div>)}{!activeFindings.length&&<p className="muted">No sourced assessments yet. Unknown is retained instead of being presented as fact.</p>}<div className="land-boundary"><ShieldCheck/><p><b>Authority boundary:</b> AI findings are decision support—not title, zoning, appraisal, environmental, legal or engineering certification. Commitments require executive approval and an audit event.</p></div></>:<div className="land-empty"><FileSearch/><b>Property file awaiting intake</b></div>}</section></div>{notice&&<div className="land-notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}</div>
}
