import{FormEvent,useEffect,useMemo,useState}from'react';
import{Activity,AlertTriangle,BarChart3,CheckCircle2,Coins,RefreshCw,Route,Search,SlidersHorizontal,WalletCards}from'lucide-react';
import{supabase}from'../lib/supabase';

type Account={id:string;provider_key:string;account_key:string;display_name:string;resource_class:string;unit:string;current_quantity:number|null;unit_usd:number|null;status:string;balance_confidence:string;last_synced_at:string|null;expires_at:string|null;metadata:any};
type Daily={system_key:string;system_name:string;opening_estimated_value_usd:number|null;spend_today_usd:number;avoided_cost_today_usd:number;usage_event_count:number;stale_resource_count:number;warnings:any[];preferred_route:any};
type Policy={system_key:string;free_included_first:boolean;manual_override_allowed:boolean;runway_preferred:boolean;openai_project_preferred:boolean;minimum_quality_score:number;preferred_provider_order:string[];notes:string|null};
type Billing={billing_month:string;system_key:string;project_key:string|null;provider_key:string;model_id:string|null;task_class:string|null;usage_events:number;provider_credits:number;cost_usd:number;avoided_cost_usd:number;chargeback_amount_usd:number};
type Research={provider_key:string|null;product_name:string|null;model_id:string|null;category:string;title:string;summary:string;why_it_matters:string|null;recommendation:string|null;recommendation_state:string;commercial_fit:string|null;free_or_included_state:string|null;source_urls:string[];confidence:number|null;observed_at:string};
type Score={task_class:string;provider_key:string;model_id:string;sample_count:number;avg_quality:number|null;avg_verifier:number|null;avg_latency_ms:number|null;avg_cost_usd:number|null;acceptance_rate_pct:number|null;last_observed_at:string|null};
type Packet={accounts:Account[];reports:Daily[];policies:Policy[];overrides:any[];recommendations:any[];scorecard:Score[];sync_runs:any[]};
const tabs=['Balances','Systems','Billing','Model Scorecard','Research','Manual Override'] as const;
const money=(n:any)=>Number(n||0).toLocaleString(undefined,{style:'currency',currency:'USD',maximumFractionDigits:2});
const date=(v:string|null)=>v?new Date(v).toLocaleString():'Never';
export default function ResourceIntelligencePanel(){
 const[packet,setPacket]=useState<Packet|null>(null),[billing,setBilling]=useState<Billing[]>([]),[research,setResearch]=useState<Research[]>([]),[tab,setTab]=useState<(typeof tabs)[number]>('Balances'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const[override,setOverride]=useState({system_key:'SYS-VISION-001',project_key:'',task_class:'',provider_key:'runway',model_id:'',reason:'Keep this project/task on Runway by CEO choice'});
 async function load(sync=false){if(!supabase)return;setBusy(true);setError('');const{data,error:e}=await supabase.functions.invoke('resource-intelligence',{body:{action:sync?'sync':'report',trigger:sync?'operator_refresh':'operator_view',force:sync}});if(e||!data?.ok){setError(e?.message||data?.error||'Resource Intelligence unavailable.');setBusy(false);return}const p=(data?.reports?.[0]||data?.results?.[0]) as Packet|undefined;if(p)setPacket(p);const[b,r]=await Promise.all([supabase.from('resource_billing_monthly').select('*').order('billing_month',{ascending:false}).limit(250),supabase.from('model_intelligence_weekly_digest').select('*').order('observed_at',{ascending:false}).limit(100)]);if(b.data)setBilling(b.data as Billing[]);if(r.data)setResearch(r.data as Research[]);if(b.error||r.error)setError(b.error?.message||r.error?.message||'');setBusy(false)}
 useEffect(()=>{void load(false)},[]);
 async function saveOverride(e:FormEvent){e.preventDefault();if(!supabase)return;setBusy(true);setError('');const{data,error:e2}=await supabase.functions.invoke('resource-intelligence',{body:{action:'set_override',...override,project_key:override.project_key||null,task_class:override.task_class||null,model_id:override.model_id||null}});if(e2||!data?.ok)setError(e2?.message||data?.error||'Override could not be saved.');else{setNotice('Manual provider/model override recorded. THELMA must honor it while the override is active.');await load(false)}setBusy(false)}
 const totals=useMemo(()=>({known:(packet?.accounts||[]).reduce((n,a)=>n+(a.current_quantity!=null&&a.unit_usd!=null?Number(a.current_quantity)*Number(a.unit_usd):0),0),today:(packet?.reports||[]).reduce((n,r)=>n+Number(r.spend_today_usd||0),0),events:(packet?.reports||[]).reduce((n,r)=>n+Number(r.usage_event_count||0),0),stale:new Set((packet?.reports||[]).filter(r=>r.stale_resource_count>0).map(r=>r.system_key)).size}),[packet]);
 const runway=packet?.accounts?.find(a=>a.provider_key==='runway');
 return <div className="thelma-ai-console resource-intelligence"><section className="thelma-ai-head"><div><span className="eyebrow">RESOURCE INTELLIGENCE · DAILY STARTUP + BILLING</span><h3>Credits, usage, model routing and research</h3><p>THELMA checks available resources daily, tracks billable usage, keeps Runway preferred for VisionWeaver, and supports explicit provider/model selection when you want to keep a project in a specific ecosystem.</p></div><button onClick={()=>load(true)} disabled={busy}><RefreshCw/>{busy?'Checking…':'Check balances now'}</button></section>{error&&<div className="thelma-ai-error"><AlertTriangle/>{error}</div>}{notice&&<div className="land-notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}<div className="thelma-ai-stats"><article><Coins/><span>Runway</span><strong>{runway?.current_quantity!=null?`${Number(runway.current_quantity).toLocaleString()} cr`:'—'}</strong></article><article><WalletCards/><span>Known value</span><strong>{money(totals.known)}</strong></article><article><Activity/><span>Usage today</span><strong>{totals.events}</strong></article><article><AlertTriangle/><span>Systems with stale resources</span><strong>{totals.stale}</strong></article></div><div className="land-tabs">{tabs.map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}><BarChart3/>{t}</button>)}</div>
 {tab==='Balances'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">CURRENT RESOURCE ACCOUNTS</span><h3>Balances & entitlements</h3></div><Coins/></div><div className="command-list">{packet?.accounts?.map(a=><div className="command-row" key={a.id}><div><b>{a.display_name}</b><small>{a.provider_key} · {a.resource_class} · confidence {a.balance_confidence}</small></div><span>{a.current_quantity!=null?`${Number(a.current_quantity).toLocaleString()} ${a.unit}`:'Usage tracked'}</span><strong>{a.current_quantity!=null&&a.unit_usd!=null?money(Number(a.current_quantity)*Number(a.unit_usd)):a.status}</strong><small>{date(a.last_synced_at)}</small></div>)}</div></section>}
 {tab==='Systems'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">STARTUP REPORT · EVERY REGISTERED SYSTEM</span><h3>System resource posture</h3></div><Route/></div><div className="command-list">{packet?.reports?.map(r=>{const p=packet.policies?.find(x=>x.system_key===r.system_key);return <div className="command-row" key={r.system_key}><div><b>{r.system_name}</b><small>{r.system_key} · quality floor {p?.minimum_quality_score??'—'}{p?.runway_preferred?' · RUNWAY PREFERRED':''}</small></div><span>{money(r.spend_today_usd)} today</span><strong>{r.usage_event_count} events</strong><small>{p?.preferred_provider_order?.join(' → ')||'Policy pending'}</small></div>})}</div></section>}
 {tab==='Billing'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">BILLING / CHARGEBACK</span><h3>Monthly usage ledger</h3></div><WalletCards/></div><div className="metrics"><article className="metric cyan"><span>Today</span><strong>{money(totals.today)}</strong><small>Tracked incremental cost</small></article><article className="metric green"><span>Records</span><strong>{billing.length}</strong><small>Monthly summary rows</small></article></div><div className="command-list">{billing.map((b,i)=><div className="command-row" key={`${b.billing_month}-${b.system_key}-${b.project_key}-${b.provider_key}-${i}`}><div><b>{b.provider_key}{b.model_id?` · ${b.model_id}`:''}</b><small>{b.system_key}{b.project_key?` · project ${b.project_key}`:''} · {b.task_class||'usage'}</small></div><span>{Number(b.provider_credits||0).toLocaleString()} credits</span><strong>{money(b.cost_usd)}</strong><small>{b.usage_events} events · avoided {money(b.avoided_cost_usd)}</small></div>)}</div></section>}
 {tab==='Model Scorecard'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">EMPIRICAL MODEL INTELLIGENCE</span><h3>Which models work best for us</h3></div><BarChart3/></div>{packet?.scorecard?.length?<div className="command-list">{packet.scorecard.map((s,i)=><div className="command-row" key={`${s.task_class}-${s.provider_key}-${s.model_id}-${i}`}><div><b>{s.task_class}</b><small>{s.provider_key} · {s.model_id} · {s.sample_count} samples</small></div><span>Q {s.avg_quality??'—'} · V {s.avg_verifier??'—'}</span><strong>{s.acceptance_rate_pct!=null?`${s.acceptance_rate_pct}%`:'—'}</strong><small>{money(s.avg_cost_usd)} avg · {s.avg_latency_ms??'—'} ms</small></div>)}</div>:<div className="thelma-clear"><Search/><b>Benchmark learning starts with production evidence.</b><p>Models will rank by our own acceptance, QC, cost and latency history instead of vendor claims.</p></div>}</section>}
 {tab==='Research'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">MONDAY + THURSDAY INTELLIGENCE REVIEW</span><h3>Models, tools, pricing, free tiers and licensing</h3></div><Search/></div>{research.length?<div className="command-list">{research.map((r,i)=><div className="command-row" key={`${r.observed_at}-${i}`}><div><b>{r.title}</b><small>{r.provider_key||'ecosystem'} · {r.category} · confidence {r.confidence??'—'} · {r.free_or_included_state||'UNKNOWN'}</small><p>{r.why_it_matters||r.summary}</p></div><span>{r.recommendation_state}</span><strong>{r.commercial_fit||'UNKNOWN'}</strong><small>{new Date(r.observed_at).toLocaleDateString()}</small></div>)}</div>:<div className="thelma-clear"><Search/><b>No model/tool research findings stored yet.</b><p>The scheduled scout runs Monday and Thursday and records official-source updates here.</p></div>}</section>}
 {tab==='Manual Override'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">CEO MODEL / PROVIDER CONTROL</span><h3>Force a route when the project belongs somewhere specific</h3></div><SlidersHorizontal/></div><form className="dispatch" onSubmit={saveOverride}><label>System<select value={override.system_key} onChange={e=>setOverride({...override,system_key:e.target.value})}>{packet?.reports?.map(r=><option key={r.system_key} value={r.system_key}>{r.system_name}</option>)}</select></label><label>Project ID / key<input value={override.project_key} onChange={e=>setOverride({...override,project_key:e.target.value})} placeholder="Optional"/></label><label>Task class<input value={override.task_class} onChange={e=>setOverride({...override,task_class:e.target.value})} placeholder="Optional: video_render, image_final…"/></label><label>Provider<select value={override.provider_key} onChange={e=>setOverride({...override,provider_key:e.target.value})}><option value="runway">Runway</option><option value="openai">OpenAI API</option><option value="chatgpt">ChatGPT interactive project</option><option value="gemini">Gemini</option><option value="anthropic">Claude / Anthropic</option><option value="deepseek">DeepSeek</option><option value="openrouter">OpenRouter</option></select></label><label>Model<input value={override.model_id} onChange={e=>setOverride({...override,model_id:e.target.value})} placeholder="Optional exact model"/></label><label>Reason<input value={override.reason} onChange={e=>setOverride({...override,reason:e.target.value})}/></label><button disabled={busy}><CheckCircle2/>Save override</button></form></section>}
 </div>;
}
