import{FormEvent,useEffect,useMemo,useState}from'react';
import{Activity,AlertTriangle,Bot,CheckCircle2,Clock3,Command,Network,Plus,RefreshCw,ShieldCheck,Workflow,XCircle}from'lucide-react';
import{supabase}from'../lib/supabase';
import{useIdentity}from'../auth/IdentityContext';

type Agent={agent_key:string;display_name:string;operating_role:string;status:string;authority_scopes:string[];health_percent:number};
type Run={id:string;workflow_key:string;engine:string;trigger_type:string;status:string;duration_ms:number|null;usage_cost:number|null;created_at:string};
type Cmd={id:string;target_agent:string;action_type:string;risk_level:string;authorization_state:string;execution_status:string;created_at:string;result_reference?:Record<string,unknown>};
type Incident={id:string;title:string;severity:string;status:string;detection_source:string;owner_agent:string|null};
const seedAgents:Agent[]=[['THELMA','THELMA','Operations lead and governed dispatcher','online',['dispatch','monitor','brief'],96],['AUDITOR','The Auditor','Quality control and evidence review','online',['inspect','reject','certify'],98],['CMGIO','CMGIO','Marketing and growth intelligence','idle',['analyze','recommend','optimize'],94],['LANDWEAVER','LandWeaver','Property intelligence worker','idle',['screen','assess','brief'],92],['VISIONWEAVER','VisionWeaver','Creative production worker','online',['plan','render','qc'],96],['GRANTOS','GrantOS','Funding operations worker','idle',['research','draft','track'],92]].map(([agent_key,display_name,operating_role,status,authority_scopes,health_percent])=>({agent_key,display_name,operating_role,status,authority_scopes,health_percent}as Agent));
const tabs=['Command Center','Agent Roster','Dispatch Queue','Fabric Runs','Incidents','Usage & Cost','Audit','Settings'];

export default function ThelmaWorkspace(){
 const identity=useIdentity();
 const[agents,setAgents]=useState<Agent[]>(seedAgents),[runs,setRuns]=useState<Run[]>([]),[commands,setCommands]=useState<Cmd[]>([]),[incidents,setIncidents]=useState<Incident[]>([]),[view,setView]=useState('Command Center'),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[acting,setActing]=useState('');
 const[form,setForm]=useState({target:'LANDWEAVER',action:'Run governed property screen',risk:'medium'});
 async function load(){if(identity.isBuilder||!supabase)return;setBusy(true);const[a,c,r,i]=await Promise.all([supabase.from('orchestration_agents').select('*').order('agent_key'),supabase.from('orchestration_commands').select('id,target_agent,action_type,risk_level,authorization_state,execution_status,created_at,result_reference').order('created_at',{ascending:false}).limit(40),supabase.from('orchestration_runs').select('*').order('created_at',{ascending:false}).limit(30),supabase.from('orchestration_incidents').select('*').order('opened_at',{ascending:false}).limit(30)]);if(a.data?.length)setAgents(a.data);if(c.data)setCommands(c.data);if(r.data)setRuns(r.data);if(i.data)setIncidents(i.data);setNotice(a.error?.message||c.error?.message||r.error?.message||i.error?.message||'');setBusy(false)}
 useEffect(()=>{load();if(identity.isBuilder||!supabase)return;const client=supabase;const channel=client.channel('thelma-live').on('postgres_changes',{event:'*',schema:'public',table:'orchestration_commands'},load).on('postgres_changes',{event:'*',schema:'public',table:'orchestration_runs'},load).on('postgres_changes',{event:'*',schema:'public',table:'orchestration_incidents'},load).subscribe();return()=>{client.removeChannel(channel)}},[identity.isBuilder]);
 async function dispatch(e:FormEvent){e.preventDefault();if(!supabase||!identity.user)return;setBusy(true);const{error}=await supabase.from('orchestration_commands').insert({organization_id:identity.organizationId,requested_by:identity.user.id,source_system:'SYS-CEO-001',target_agent:form.target,action_type:form.action,risk_level:form.risk,authorization_state:'ASK',execution_status:'queued',payload_reference:{submitted_from:'THELMA UI'}});setBusy(false);if(error)setNotice(error.message);else{setNotice('Command staged at ASK. Review it in Dispatch Queue and click Authorize & Run.');setView('Dispatch Queue');await load()}}
 async function authorizeAndRun(command:Cmd){
  if(!supabase||!identity.user)return;
  setActing(command.id);setNotice('');
  const now=new Date().toISOString();
  const{error:updateError}=await supabase.from('orchestration_commands').update({authorization_state:'AUTHORIZED',authorized_by:identity.user.id,authorized_at:now,execution_status:'queued'}).eq('id',command.id);
  if(updateError){setActing('');setNotice(updateError.message);return}
  const{data:job,error:createError}=await supabase.from('ec_integration_jobs').insert({organization_id:identity.organizationId,idempotency_key:`thelma-${command.id}-${crypto.randomUUID()}`,module_key:'THELMA',workflow_key:'agent-command-dispatch',requested_by:identity.user.id,risk_level:command.risk_level,authorization_state:'ASK',execution_state:'queued',payload:{command_id:command.id,target_agent:command.target_agent,action_type:command.action_type}}).select('id').single();
  if(createError||!job){setActing('');setNotice(createError?.message||'Could not create Fabric job.');return}
  const{error:authorizeError}=await supabase.from('ec_integration_jobs').update({authorization_state:'AUTHORIZED'}).eq('id',job.id);
  setActing('');
  if(authorizeError)setNotice(authorizeError.message);else{setNotice('Authorized through the zero-trust gate and handed to EC Fabric. The Agents queue will execute it and sync the result back here.');await load()}
 }
 async function reject(command:Cmd){if(!supabase)return;setActing(command.id);const{error}=await supabase.from('orchestration_commands').update({authorization_state:'REJECTED',execution_status:'cancelled'}).eq('id',command.id);setActing('');if(error)setNotice(error.message);else await load()}
 const metrics=useMemo(()=>({online:agents.filter(a=>a.status==='online').length,queued:commands.filter(c=>c.execution_status==='queued').length,success:runs.filter(r=>r.status==='succeeded').length,open:incidents.filter(i=>i.status!=='resolved').length,cost:runs.reduce((n,r)=>n+Number(r.usage_cost||0),0)}),[agents,commands,runs,incidents]);
 const roster=<>{agents.map(a=><article className="agent" key={a.agent_key}><Bot/><div><b>{a.display_name}</b><small>{a.operating_role}</small><em>{a.authority_scopes.join(' · ')}</em></div><span className={a.status}>{a.status}</span><strong>{a.health_percent}%</strong></article>)}</>;
 const queue=<>{commands.length?commands.map(c=><div className="command-row" key={c.id}><div><b>{c.action_type}</b><small>{c.target_agent} · {c.risk_level} risk · {new Date(c.created_at).toLocaleString()}</small></div><span>{c.authorization_state}</span><strong>{c.execution_status}</strong><div className="fabric-job-actions">{c.authorization_state==='ASK'&&c.execution_status==='queued'&&<><button disabled={acting!==''} onClick={()=>authorizeAndRun(c)}><CheckCircle2/>Authorize & Run</button><button disabled={acting!==''} onClick={()=>reject(c)}><XCircle/>Reject</button></>}{c.execution_status==='completed'&&<small>Fabric execution complete</small>}</div></div>):<div className="thelma-clear"><CheckCircle2/><b>No commands waiting</b></div>}</>;
 const incidentsPanel=<>{incidents.length?incidents.map(i=><div className="incident" key={i.id}><AlertTriangle/><div><b>{i.title}</b><small>{i.detection_source} · owner {i.owner_agent||'unassigned'}</small></div><span>{i.severity}</span><strong>{i.status}</strong></div>):<div className="thelma-clear"><CheckCircle2/><b>No open production incidents</b><p>White Blood Cell monitoring is clear.</p></div>}</>;
 return <div className="thelma"><div className="briefing thelma-hero"><div><span className="eyebrow">SYS-THELMA-001 · GOVERNED ORCHESTRATION</span><h2>THELMA command center</h2><p>Stage commands, explicitly authorize them, send them through EC Fabric and watch execution state return here.</p></div><button onClick={load}><RefreshCw/>{busy?'Syncing':'Refresh fabric'}</button></div><div className="land-tabs">{tabs.map(t=><button className={view===t?'active':''} onClick={()=>setView(t)} key={t}><Workflow/>{t}</button>)}</div><div className="metrics"><article className="metric green"><span>Online agents</span><strong>{metrics.online}/{agents.length}</strong><small>Roster heartbeat</small></article><article className="metric amber"><span>Queued commands</span><strong>{metrics.queued}</strong><small>ASK / authorized work</small></article><article className="metric cyan"><span>Successful runs</span><strong>{metrics.success}</strong><small>Fabric telemetry</small></article><article className="metric purple"><span>Open incidents</span><strong>{metrics.open}</strong><small>${metrics.cost.toFixed(3)} tracked</small></article></div>
 {view==='Command Center'&&<div className="thelma-grid"><section className="panel"><div className="panel-title"><div><span className="eyebrow">AUTHORITY CHAIN</span><h3>Agent roster</h3></div><Network/></div><div className="authority"><b>The Architect</b><span>authorizes</span><b>THELMA</b><span>dispatches</span><b>EC Fabric</b></div>{roster}</section><section className="panel"><div className="panel-title"><div><span className="eyebrow">NEW COMMAND</span><h3>Stage governed work</h3></div><Command/></div><form className="dispatch" onSubmit={dispatch}><label>Target<select value={form.target} onChange={e=>setForm({...form,target:e.target.value})}>{agents.filter(a=>a.agent_key!=='THELMA').map(a=><option key={a.agent_key}>{a.agent_key}</option>)}</select></label><label>Action<input required value={form.action} onChange={e=>setForm({...form,action:e.target.value})}/></label><label>Risk<select value={form.risk} onChange={e=>setForm({...form,risk:e.target.value})}><option>low</option><option>medium</option><option>high</option><option>critical</option></select></label><button disabled={busy}><Plus/>Stage command</button></form>{queue}</section></div>}
 {view==='Agent Roster'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">LIVE AGENTS</span><h3>Agent roster & authority</h3></div><Network/></div>{roster}</section>}
 {view==='Dispatch Queue'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">ASK → AUTHORIZE → EXECUTE</span><h3>Dispatch queue</h3></div><Command/></div>{queue}</section>}
 {view==='Fabric Runs'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">EXECUTION TELEMETRY</span><h3>Recent EC Fabric runs</h3></div><Activity/></div>{runs.length?runs.map(r=><div className="run" key={r.id}><Workflow/><div><b>{r.workflow_key}</b><small>{r.engine} · {r.trigger_type}</small></div><span className={r.status}>{r.status}</span><strong>{r.duration_ms?`${(r.duration_ms/1000).toFixed(1)}s`:'—'}</strong><small>${Number(r.usage_cost||0).toFixed(3)}</small></div>):<div className="thelma-clear"><Clock3/><b>No run telemetry yet</b></div>}</section>}
 {view==='Incidents'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">WHITE BLOOD CELLS</span><h3>Incidents & containment</h3></div><ShieldCheck/></div>{incidentsPanel}</section>}
 {view==='Usage & Cost'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">RESOURCE CONTROL</span><h3>Usage & cost</h3></div><Activity/></div><div className="fabric-controls"><article><Activity/><b>{runs.length} recent runs</b><p>Total tracked cost ${metrics.cost.toFixed(3)}.</p></article><article><Clock3/><b>{commands.length} commands</b><p>{commands.filter(c=>c.execution_status==='completed').length} completed through the governed chain.</p></article></div></section>}
 {view==='Audit'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">COMMAND HISTORY</span><h3>Authorization & execution audit</h3></div><ShieldCheck/></div>{commands.map(c=><div className="command-row" key={c.id}><div><b>{c.action_type}</b><small>{c.target_agent} · {new Date(c.created_at).toLocaleString()}</small></div><span>{c.authorization_state}</span><strong>{c.execution_status}</strong></div>)}</section>}
 {view==='Settings'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">GOVERNANCE</span><h3>THELMA operating boundary</h3></div><ShieldCheck/></div><div className="fabric-controls"><article><CheckCircle2/><b>Explicit authorization</b><p>ASK commands do not enter the Fabric until you click Authorize & Run.</p></article><article><ShieldCheck/><b>No silent provider writes</b><p>External side effects remain credential and policy gated.</p></article></div></section>}
 {notice&&<div className="land-notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}</div>;
}
