import{useEffect,useMemo,useState}from'react';
import{AlertTriangle,Bell,CheckCircle2,ExternalLink,GitFork,Plug,RefreshCw,Search,ShieldCheck,Star,XCircle}from'lucide-react';
import{supabase}from'../lib/supabase';

type Mode='alerts'|'ecosystem'|'plugins';
type Alert={id:string;severity:string;title:string;summary:string;system_key:string;state:string;recommended_action:string|null;approval_request_id:string|null;created_at:string};
type Approval={id:string;requested_by_agent:string;action_type:string;risk_tier:string;title:string;description:string;status:string;requested_at:string;proposed_payload:Record<string,unknown>};
type Candidate={id:string;repository:string;url:string;description:string|null;license_spdx:string|null;stars:number;forks:number;score:number;system_key:string;last_pushed_at:string|null;disposition:string};
type Advice={id:string;candidate_id:string;title:string;why_it_matters:string;recommendation:string;status:string;approval_request_id:string|null};
type Plugin={id:string;plugin_key:string;display_name:string;provider:string;capability_class:string;integration_mode:string;connection_state:string;approval_policy:string;allowed_operations:string[];prohibited_operations:string[];endpoint:string|null;notes:string|null};
type Scan={id:string;status:string;sources_scanned:number;candidates_seen:number;advisements_created:number;started_at:string;completed_at:string|null;error_summary:string|null};

export default function ThelmaGovernanceCenter({mode}:{mode:Mode}){
 const[alerts,setAlerts]=useState<Alert[]>([]),[approvals,setApprovals]=useState<Approval[]>([]),[candidates,setCandidates]=useState<Candidate[]>([]),[advice,setAdvice]=useState<Advice[]>([]),[plugins,setPlugins]=useState<Plugin[]>([]),[scans,setScans]=useState<Scan[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 async function load(){if(!supabase)return;setBusy(true);const[a,p,c,d,g,s]=await Promise.all([
  supabase.from('thelma_alerts').select('*').order('created_at',{ascending:false}).limit(100),
  supabase.from('thelma_approval_requests').select('*').order('requested_at',{ascending:false}).limit(100),
  supabase.from('ecosystem_candidates').select('*').order('score',{ascending:false}).limit(100),
  supabase.from('ecosystem_advisements').select('*').order('created_at',{ascending:false}).limit(100),
  supabase.from('thelma_plugin_registry').select('*').order('display_name'),
  supabase.from('ecosystem_scan_runs').select('*').order('started_at',{ascending:false}).limit(10)
 ]);setAlerts((a.data||[])as Alert[]);setApprovals((p.data||[])as Approval[]);setCandidates((c.data||[])as Candidate[]);setAdvice((d.data||[])as Advice[]);setPlugins((g.data||[])as Plugin[]);setScans((s.data||[])as Scan[]);setNotice(a.error?.message||p.error?.message||c.error?.message||d.error?.message||g.error?.message||s.error?.message||'');setBusy(false)}
 useEffect(()=>{void load()},[]);
 async function decide(id:string,decision:'APPROVED'|'REJECTED'){if(!supabase)return;setBusy(true);const{error}=await supabase.rpc('decide_thelma_approval',{p_request_id:id,p_decision:decision,p_reason:decision==='APPROVED'?'CEO approved bounded action from THELMA console.':'CEO rejected action from THELMA console.'});setNotice(error?.message||`${decision==='APPROVED'?'Approved':'Rejected'} and written to the security ledger.`);await load()}
 async function acknowledge(id:string){if(!supabase)return;await supabase.from('thelma_alerts').update({state:'ACKNOWLEDGED'}).eq('id',id);await load()}
 async function runScan(){if(!supabase)return;setBusy(true);setNotice('');const{data,error}=await supabase.functions.invoke('ecosystem-watch',{body:{trigger:'ceo_manual'}});setNotice(error?.message||data?.error||'Ecosystem scan finished and THELMA prepared the review queue.');await load()}
 const pending=useMemo(()=>approvals.filter(x=>x.status==='PENDING'),[approvals]);
 const candidateById=useMemo(()=>new Map(candidates.map(x=>[x.id,x])),[candidates]);

 if(mode==='alerts')return <div className="thelma-governance"><section className="thelma-ai-head"><div><span className="eyebrow">CEO ALERT + AUTHORIZATION INBOX</span><h3>THELMA tells you first. You decide what may proceed.</h3><p>Detection and diagnosis can run automatically. External writes, deployments, credentials, finances, destructive actions, sandbox tests, and medium/high-risk repairs pause here.</p></div><button onClick={load} disabled={busy}><RefreshCw/>{busy?'Syncing…':'Refresh'}</button></section>{notice&&<div className="thelma-ai-error"><Bell/>{notice}</div>}<div className="thelma-ai-stats"><article><Bell/><span>New alerts</span><strong>{alerts.filter(x=>x.state==='NEW').length}</strong></article><article><ShieldCheck/><span>Pending approvals</span><strong>{pending.length}</strong></article><article><AlertTriangle/><span>Critical</span><strong>{alerts.filter(x=>x.state==='NEW'&&x.severity==='critical').length}</strong></article><article><CheckCircle2/><span>Decided</span><strong>{approvals.filter(x=>['APPROVED','REJECTED'].includes(x.status)).length}</strong></article></div><section className="thelma-inbox-grid"><div><h4>Needs your decision</h4>{pending.length?pending.map(p=><article className="thelma-approval-card" key={p.id}><header><i className={`wbc-severity ${p.risk_tier}`}>{p.risk_tier}</i><span>{p.requested_by_agent}</span><small>{new Date(p.requested_at).toLocaleString()}</small></header><h5>{p.title}</h5><p>{p.description}</p><div><button disabled={busy} onClick={()=>decide(p.id,'APPROVED')}><CheckCircle2/>Approve bounded action</button><button className="danger" disabled={busy} onClick={()=>decide(p.id,'REJECTED')}><XCircle/>Reject</button></div></article>):<div className="thelma-clear"><CheckCircle2/><b>No approvals waiting.</b></div>}</div><div><h4>Alert stream</h4>{alerts.map(a=><article className={`thelma-alert-card ${a.state.toLowerCase()}`} key={a.id}><header><i className={`wbc-severity ${a.severity}`}>{a.severity}</i><span>{a.system_key}</span><small>{a.state}</small></header><h5>{a.title}</h5><p>{a.summary}</p>{a.recommended_action&&<em>{a.recommended_action}</em>}{a.state==='NEW'&&<button onClick={()=>acknowledge(a.id)}>Acknowledge</button>}</article>)}</div></section></div>;

 if(mode==='ecosystem')return <div className="thelma-governance"><section className="thelma-ai-head"><div><span className="eyebrow">ECOSYSTEM DISCOVERY + LEARNING ENGINE</span><h3>Weekly updates, ratings, usage evidence, and adoption advice</h3><p>Ecosystem Scout searches and scores automatically. Popularity is context—not proof. Nothing installs until you approve evaluation and a later production gate.</p></div><button onClick={runScan} disabled={busy}><Search/>{busy?'Scanning…':'Run scan now'}</button></section>{notice&&<div className="thelma-ai-error"><Bell/>{notice}</div>}<div className="thelma-ai-stats"><article><Search/><span>Candidates</span><strong>{candidates.length}</strong></article><article><Star/><span>Advisements</span><strong>{advice.length}</strong></article><article><ShieldCheck/><span>Awaiting review</span><strong>{advice.filter(x=>x.status==='PENDING_REVIEW').length}</strong></article><article><RefreshCw/><span>Last scan</span><strong>{scans[0]?.status||'—'}</strong></article></div>{scans[0]&&<div className="thelma-scan-receipt"><b>Latest scan: {scans[0].status}</b><span>{scans[0].sources_scanned} sources · {scans[0].candidates_seen} candidates · {scans[0].advisements_created} advisements</span>{scans[0].error_summary&&<em>{scans[0].error_summary}</em>}</div>}<section className="ecosystem-grid">{advice.map(a=>{const c=candidateById.get(a.candidate_id);return <article className="ecosystem-card" key={a.id}><header><span>{a.recommendation}</span><strong>{c?.score??'—'}/100</strong></header><h4>{c?.repository||a.title}</h4><p>{a.why_it_matters}</p><div className="ecosystem-signals"><span><Star/>{c?.stars??0}</span><span><GitFork/>{c?.forks??0}</span><span>{c?.license_spdx||'LICENSE UNVERIFIED'}</span><span>{c?.system_key}</span></div><footer><b>{a.status.replaceAll('_',' ')}</b>{c?.url&&<a href={c.url} target="_blank" rel="noreferrer">Inspect source<ExternalLink/></a>}</footer></article>})}</section></div>;

 return <div className="thelma-governance"><section className="thelma-ai-head"><div><span className="eyebrow">THELMA PLUGIN + MODEL REGISTRY</span><h3>One governed tool fabric—not a pile of shared passwords</h3><p>ChatGPT plugins, model APIs, MCP servers, and source-code executors are different connection types. This registry shows what THELMA can actually use.</p></div><button onClick={load} disabled={busy}><RefreshCw/>Refresh</button></section><section className="plugin-grid">{plugins.map(p=><article className="plugin-card" key={p.id}><header><Plug/><div><h4>{p.display_name}</h4><small>{p.provider} · {p.capability_class}</small></div><span className={p.connection_state.toLowerCase()}>{p.connection_state.replaceAll('_',' ')}</span></header><dl><div><dt>Integration</dt><dd>{p.integration_mode}</dd></div><div><dt>Approval</dt><dd>{p.approval_policy.replaceAll('_',' ')}</dd></div></dl><p>{p.notes}</p><div className="plugin-boundary"><b>Allowed</b><span>{p.allowed_operations.length?p.allowed_operations.join(' · '):'None until connected'}</span><b>Blocked</b><span>{p.prohibited_operations.length?p.prohibited_operations.join(' · '):'Default deny'}</span></div>{p.endpoint&&<a href={p.endpoint} target="_blank" rel="noreferrer">Provider endpoint<ExternalLink/></a>}</article>)}</section></div>;
}

