import{FormEvent,useEffect,useMemo,useState}from'react';
import{Activity,AlertTriangle,Bot,CheckCircle2,Clock3,Command,Network,Plus,RefreshCw,ShieldCheck,Workflow,XCircle}from'lucide-react';
import{supabase}from'../lib/supabase';
import{useIdentity}from'../auth/IdentityContext';
import ThelmaAIConsole from'./ThelmaAIConsole';
import ThelmaGovernanceCenter from'./ThelmaGovernanceCenter';

type Agent={agent_key:string;display_name:string;operating_role:string;status:string;authority_scopes:string[];health_percent:number};
type Run={id:string;workflow_key:string;engine:string;trigger_type:string;status:string;duration_ms:number|null;usage_cost:number|null;created_at:string;error_summary?:string|null};
type Cmd={id:string;target_agent:string;action_type:string;risk_level:string;authorization_state:string;execution_status:string;created_at:string;result_reference?:Record<string,unknown>};
type Incident={id:string;title:string;severity:string;status:string;detection_source:string;owner_agent:string|null};
const tabs=['Ask THELMA','Alerts & Approvals','White Blood Cells','Ecosystem Watch','Plugins & Models','Agent Roster','Dispatch Queue','Fabric Runs','Incidents','Usage & Cost','Settings'];

export default function ThelmaWorkspace(){
 const identity=useIdentity();
 const[agents,setAgents]=useState<Agent[]>([]),[runs,setRuns]=useState<Run[]>([]),[commands,setCommands]=useState<Cmd[]>([]),[incidents,setIncidents]=useState<Incident[]>([]),[view,setView]=useState('Ask THELMA'),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[acting,setActing]=useState('');
 const[form,setForm]=useState({target:'THELMA',action:'Diagnose the highest-priority CEO system defect and propose a bounded repair plan',risk:'medium'});
 async function load(){if(identity.isBuilder||!supabase)return;setBusy(true);const[a,c,r,i]=await Promise.all([supabase.from('orchestration_agents').select('*').order('agent_key'),supabase.from('orchestration_commands').select('id,target_agent,action_type,risk_level,authorization_state,execution_status,created_at,result_reference').order('created_at',{ascending:false}).limit(40),supabase.from('orchestration_runs').select('*').order('created_at',{ascending:false}).limit(30),supabase.from('orchestration_incidents').select('*').order('opened_at',{ascending:false}).limit(30)]);if(a.data)setAgents(a.data as Agent[]);if(c.data)setCommands(c.data as Cmd[]);if(r.data)setRuns(r.data as Run[]);if(i.data)setIncidents(i.data as Incident[]);setNotice(a.error?.message||c.error?.message||r.error?.message||i.error?.message||'');setBusy(false)}
 useEffect(()=>{void load();if(identity.isBuilder||!supabase)return;const client=supabase;const channel=client.channel('thelma-live').on('postgres_changes',{event:'*',schema:'public',table:'orchestration_commands'},load).on('postgres_changes',{event:'*',schema:'public',table:'orchestration_runs'},load).on('postgres_changes',{event:'*',schema:'public',table:'orchestration_incidents'},load).on('postgres_changes',{event:'*',schema:'public',table:'white_blood_cell_signals'},load).subscribe();return()=>{client.removeChannel(channel)}},[identity.isBuilder]);
 async function dispatch(e:FormEvent){e.preventDefault();if(!supabase||!identity.user)return;setBusy(true);const{error}=await supabase.from('orchestration_commands').insert({organization_id:identity.organizationId,requested_by:identity.user.id,source_system:'SYS-CEO-001',target_agent:form.target,action_type:form.action,risk_level:form.risk,authorization_state:'ASK',execution_status:'queued',payload_reference:{submitted_from:'THELMA UI',runtime:'thelma-ai'}});setBusy(false);if(error)setNotice(error.message);else{setNotice('Command recorded at ASK. Use Ask THELMA or White Blood Cells for active diagnosis/repair planning. Generic legacy Fabric dispatch is intentionally disabled until a certified handler exists.');setView('Dispatch Queue');await load()}}
 async function reject(command:Cmd){if(!supabase)return;setActing(command.id);const{error}=await supabase.from('orchestration_commands').update({authorization_state:'REJECTED',execution_status:'cancelled'}).eq('id',command.id);setActing('');if(error)setNotice(error.message);else await load()}
 const metrics=useMemo(()=>({online:agents.filter(a=>a.status==='online').length,queued:commands.filter(c=>c.execution_status==='queued').length,success:runs.filter(r=>r.status==='succeeded').length,open:incidents.filter(i=>i.status!=='resolved').length,cost:runs.reduce((n,r)=>n+Number(r.usage_cost||0),0)}),[agents,commands,runs,incidents]);
 const roster=<>{agents.length?agents.map(a=><article className="agent" key={a.agent_key}><Bot/><div><b>{a.display_name}</b><small>{a.operating_role}</small><em>{Array.isArray(a.authority_scopes)?a.authority_scopes.join(' · '):''}</em></div><span className={a.status}>{a.status}</span><strong>{a.health_percent}%</strong></article>):<div className="thelma-clear"><Clock3/><b>Loading agent roster…</b></div>}</>;
 const queue=<>{commands.length?commands.map(c=><div className="command-row" key={c.id}><div><b>{c.action_type}</b><small>{c.target_agent} · {c.risk_level} risk · {new Date(c.created_at).toLocaleString()}</small></div><span>{c.authorization_state}</span><strong>{c.execution_status}</strong><div className="fabric-job-actions">{c.authorization_state==='ASK'&&c.execution_status==='queued'&&<button disabled={acting!==''} onClick={()=>reject(c)}><XCircle/>Reject</button>}{c.authorization_state==='ASK'&&<small>Use THELMA AI / White Blood Cells to diagnose and plan before authorization.</small>}</div></div>):<div className="thelma-clear"><CheckCircle2/><b>No commands waiting</b></div>}</>;
 const incidentsPanel=<>{incidents.length?incidents.map(i=><div className="incident" key={i.id}><AlertTriangle/><div><b>{i.title}</b><small>{i.detection_source} · owner {i.owner_agent||'unassigned'}</small></div><span>{i.severity}</span><strong>{i.status}</strong></div>):<div className="thelma-clear"><CheckCircle2/><b>No legacy orchestration incidents</b><p>Use White Blood Cells for the active repair signal ledger.</p></div>}</>;
 return <div className="thelma"><div className="briefing thelma-hero"><div><span className="eyebrow">SYS-THELMA-001 · INTELLIGENCE + REPAIR ORCHESTRATION</span><h2>THELMA AI command center</h2><p>THELMA reads the Analyst Memory Bank, supervises specialist agents, turns failures into White Blood Cell repair signals, proposes bounded fixes, and verifies evidence before anything is called complete.</p></div><button onClick={load}><RefreshCw/>{busy?'Syncing':'Refresh runtime'}</button></div><div className="land-tabs">{tabs.map(t=><button className={view===t?'active':''} onClick={()=>setView(t)} key={t}><Workflow/>{t}</button>)}</div><div className="metrics"><article className="metric green"><span>Online agents</span><strong>{metrics.online}/{agents.length||'—'}</strong><small>THELMA + specialists</small></article><article className="metric amber"><span>Legacy queued commands</span><strong>{metrics.queued}</strong><small>Not auto-executed</small></article><article className="metric cyan"><span>Certified Fabric runs</span><strong>{metrics.success}</strong><small>Real handlers only</small></article><article className="metric purple"><span>Legacy incidents</span><strong>{metrics.open}</strong><small>${metrics.cost.toFixed(3)} tracked</small></article></div>
 {view==='Ask THELMA'&&<ThelmaAIConsole mode="chat"/>}
 {view==='White Blood Cells'&&<ThelmaAIConsole mode="wbc"/>}
 {view==='Alerts & Approvals'&&<ThelmaGovernanceCenter mode="alerts"/>}
 {view==='Ecosystem Watch'&&<ThelmaGovernanceCenter mode="ecosystem"/>}
 {view==='Plugins & Models'&&<ThelmaGovernanceCenter mode="plugins"/>}
 {view==='Agent Roster'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">THELMA + SPECIALISTS + REPAIR CELLS</span><h3>Agent roster & bounded authority</h3></div><Network/></div><div className="authority"><b>CEO / Architect</b><span>authorizes high-risk work</span><b>THELMA</b><span>coordinates</span><b>specialists + White Cells</b></div>{roster}</section>}
 {view==='Dispatch Queue'&&<div className="thelma-grid"><section className="panel"><div className="panel-title"><div><span className="eyebrow">LEGACY COMMAND LEDGER</span><h3>ASK records</h3></div><Command/></div><div className="thelma-dispatch-warning"><AlertTriangle/><p><b>Generic agent-command-dispatch is intentionally disabled.</b> It previously produced false completion. Use Ask THELMA and White Blood Cells for real analysis and repair planning; only certified executors may enter Fabric.</p></div>{queue}</section><section className="panel"><div className="panel-title"><div><span className="eyebrow">RECORD WORK REQUEST</span><h3>Stage an ASK record</h3></div><Plus/></div><form className="dispatch" onSubmit={dispatch}><label>Target<select value={form.target} onChange={e=>setForm({...form,target:e.target.value})}>{agents.map(a=><option key={a.agent_key}>{a.agent_key}</option>)}</select></label><label>Request<input required value={form.action} onChange={e=>setForm({...form,action:e.target.value})}/></label><label>Risk<select value={form.risk} onChange={e=>setForm({...form,risk:e.target.value})}><option>low</option><option>medium</option><option>high</option><option>critical</option></select></label><button disabled={busy}><Plus/>Record ASK</button></form></section></div>}
 {view==='Fabric Runs'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">EXECUTION TELEMETRY</span><h3>Recent EC Fabric runs</h3></div><Activity/></div>{runs.length?runs.map(r=><div className="run" key={r.id}><Workflow/><div><b>{r.workflow_key}</b><small>{r.engine} · {r.trigger_type}{r.error_summary?` · ${r.error_summary}`:''}</small></div><span className={r.status}>{r.status}</span><strong>{r.duration_ms?`${(r.duration_ms/1000).toFixed(1)}s`:'—'}</strong><small>${Number(r.usage_cost||0).toFixed(3)}</small></div>):<div className="thelma-clear"><Clock3/><b>No run telemetry yet</b></div>}</section>}
 {view==='Incidents'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">LEGACY INCIDENTS</span><h3>Orchestration incidents</h3></div><ShieldCheck/></div>{incidentsPanel}</section>}
 {view==='Usage & Cost'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">RESOURCE CONTROL</span><h3>Usage & cost</h3></div><Activity/></div><div className="fabric-controls"><article><Activity/><b>{runs.length} recent runs</b><p>Total tracked Fabric cost ${metrics.cost.toFixed(3)}.</p></article><article><Bot/><b>{agents.length} registered agents</b><p>{metrics.online} are currently marked online. Model usage is separately recorded in THELMA message/tool footprints.</p></article></div></section>}
 {view==='Settings'&&<section className="panel"><div className="panel-title"><div><span className="eyebrow">THELMA GOVERNANCE</span><h3>Operating boundary</h3></div><ShieldCheck/></div><div className="fabric-controls"><article><CheckCircle2/><b>Read / diagnose / propose / verify</b><p>Bounded low-risk intelligence capabilities are active.</p></article><article><ShieldCheck/><b>Approval-gated side effects</b><p>Destructive, external, credential, financial, deployment and medium/high-risk repairs require explicit authorization and a certified executor.</p></article><article><CheckCircle2/><b>No fake completion</b><p>Unsupported Fabric workflows now fail instead of being marked completed.</p></article></div></section>}
 {notice&&<div className="land-notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}</div>;
}
