import{FormEvent,useEffect,useMemo,useState}from'react';
import{Activity,CheckCircle2,Clapperboard,Film,FileVideo,Layers3,Play,Plus,RefreshCw,ShieldCheck,Sparkles}from'lucide-react';
import{supabase}from'../lib/supabase';
import{useIdentity}from'../auth/IdentityContext';
type Job={id:string;project_title:string;concept:string;scene_count:number;target_platform:string;status:string;approval_state:string;created_at:string};
type Scene={id:string;job_id:string;scene_index:number;scene_id:string;prompt:string;status:string;provider:string|null;qc_state:string;prompt_version:number};
const builderJobs:Job[]=[
 {id:'vw-1',project_title:'The Matriarch’s Debt',concept:'Bittersweet family legacy short film',scene_count:12,target_platform:'YouTube',status:'scene_breakdown',approval_state:'review',created_at:'2026-08-14'},
 {id:'vw-2',project_title:'LandWeaver Launch',concept:'Property intelligence product story',scene_count:8,target_platform:'Instagram',status:'cinematography',approval_state:'approved',created_at:'2026-08-13'},
 {id:'vw-3',project_title:'GrantOS Authority',concept:'Governed funding workflow explainer',scene_count:6,target_platform:'LinkedIn',status:'queued',approval_state:'draft',created_at:'2026-08-12'}
];
const builderScenes:Scene[]=Array.from({length:12},(_,i)=>({id:'scene-'+i,job_id:'vw-1',scene_index:i+1,scene_id:'MAT-'+String(i+1).padStart(2,'0'),prompt:['Hope Memorial Chapel exterior at blue hour','Evelyn Reed enters the silent chapel','Close portrait: memory and resolve','Family photographs across an empty pew'][i%4],status:i<4?'ready':'pending',provider:null,qc_state:i<2?'passed':'pending',prompt_version:1}));
const tabs=[['Overview',Activity],['Productions',Film],['Storyboard',Clapperboard],['Scene Queue',Layers3],['Render Queue',Play],['Review & QC',CheckCircle2],['Integrations',ShieldCheck],['Run Log',FileVideo]]as const;
export default function VisionWeaverWorkspace(){
 const identity=useIdentity(),[jobs,setJobs]=useState<Job[]>([]),[scenes,setScenes]=useState<Scene[]>([]),[activeId,setActiveId]=useState(''),[view,setView]=useState('Overview'),[adding,setAdding]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const[form,setForm]=useState({title:'',concept:'',scenes:'6',platform:'YouTube'});
 async function load(){if(identity.isBuilder){setJobs(builderJobs);setScenes(builderScenes);setActiveId(x=>x||builderJobs[0].id);return}if(!supabase)return;setBusy(true);const[{data:j,error},{data:s}]=await Promise.all([supabase.from('production_jobs').select('id,project_title,concept,scene_count,target_platform,status,approval_state,created_at').order('created_at',{ascending:false}),supabase.from('production_scenes').select('id,job_id,scene_index,scene_id,prompt,status,provider,qc_state,prompt_version').order('scene_index')]);if(error)setNotice(error.message);else{setJobs(j||[]);setScenes(s||[]);setActiveId(x=>x||j?.[0]?.id||'')}setBusy(false)}
 useEffect(()=>{load();if(identity.isBuilder)return;const client=supabase;if(!client)return;const c=client.channel('visionweaver-live').on('postgres_changes',{event:'*',schema:'public',table:'production_jobs'},load).on('postgres_changes',{event:'*',schema:'public',table:'production_scenes'},load).subscribe();return()=>{client.removeChannel(c)}},[identity.isBuilder]);
 async function create(e:FormEvent){e.preventDefault();const count=Math.max(1,Math.min(20,Number(form.scenes)||1));if(identity.isBuilder){const item:Job={id:crypto.randomUUID(),project_title:form.title,concept:form.concept,scene_count:count,target_platform:form.platform,status:'queued',approval_state:'draft',created_at:new Date().toISOString()};setJobs(x=>[item,...x]);setActiveId(item.id);setAdding(false);setNotice('Production added to this builder session. Provider execution remains locked.');return}if(!supabase||!identity.user)return;setBusy(true);const{data,error}=await supabase.from('production_jobs').insert({project_title:form.title,concept:form.concept,scene_count:count,target_platform:form.platform,status:'queued',approval_state:'draft',owner_id:identity.user.id,created_by:identity.user.email}).select('id,project_title,concept,scene_count,target_platform,status,approval_state,created_at').single();if(error)setNotice(error.message);else{setJobs(x=>[data,...x]);setActiveId(data.id);setAdding(false)}setBusy(false)}
 const active=jobs.find(j=>j.id===activeId)||jobs[0],activeScenes=scenes.filter(s=>s.job_id===active?.id);
 const metrics=useMemo(()=>({jobs:jobs.length,scenes:jobs.reduce((n,j)=>n+j.scene_count,0),review:jobs.filter(j=>j.approval_state==='review').length,ready:scenes.filter(s=>s.status==='ready'||s.status==='completed').length}),[jobs,scenes]);
 return <div className="visionweaver"><div className="briefing vision-hero"><div><span className="eyebrow">SYS-VISION-001 · GOVERNED CREATIVE PRODUCTION</span><h2>Turn an approved vision into a durable production run.</h2><p>Intake, scene planning, rendering, QC, provenance and release remain separated by review gates.</p></div><div className="land-actions"><button onClick={()=>setAdding(!adding)}><Plus/>New production</button><button className="secondary" onClick={load}><RefreshCw/>{busy?'Syncing':'Refresh'}</button></div></div>
 <div className="land-tabs">{tabs.map(([name,Icon])=><button className={view===name?'active':''} onClick={()=>setView(name)} key={name}><Icon/>{name}</button>)}</div>
 {adding&&<form className="panel vision-intake" onSubmit={create}><div className="panel-title"><div><span className="eyebrow">APPROVED CREATIVE INTAKE</span><h3>Create a production job</h3></div><ShieldCheck/></div><div className="land-form"><label>Project title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Target platform<select value={form.platform} onChange={e=>setForm({...form,platform:e.target.value})}><option>YouTube</option><option>Instagram</option><option>TikTok</option><option>LinkedIn</option></select></label><label>Scene count<input type="number" min="1" max="20" value={form.scenes} onChange={e=>setForm({...form,scenes:e.target.value})}/></label><label className="wide">Creative concept<textarea required value={form.concept} onChange={e=>setForm({...form,concept:e.target.value})}/></label></div><button disabled={busy}>Create draft production</button></form>}
 <div className="metrics"><article className="metric purple"><span>Productions</span><strong>{metrics.jobs}</strong><small>Durable jobs</small></article><article className="metric cyan"><span>Planned scenes</span><strong>{metrics.scenes}</strong><small>1–20 per job</small></article><article className="metric amber"><span>Review gates</span><strong>{metrics.review}</strong><small>Human decision</small></article><article className="metric green"><span>Scenes ready</span><strong>{metrics.ready}</strong><small>QC tracked</small></article></div>
 {view==='Integrations'?<section className="panel vision-integrations"><div className="panel-title"><div><span className="eyebrow">SERVER-SIDE ADAPTERS</span><h3>Production connections</h3></div><ShieldCheck/></div><div className="provider-grid">{[['Supabase','Connected','Auth · Postgres · Realtime · Cron'],['Anthropic','Credential required','Structured planning'],['Runway','Credential required','Video rendering'],['Google Drive','Source inventory','References · archives'],['CEO Dashboard','Connected','Health · exceptions'],['n8n v2.1','Fallback preserved','Historical orchestration']].map(x=><article key={x[0]}><div><b>{x[0]}</b><span>{x[1]}</span></div><p>{x[2]}</p></article>)}</div><div className="land-boundary"><ShieldCheck/><p><b>Production blocker:</b> live generation starts only after the account owner installs Anthropic and Runway keys in Supabase Vault. Keys never enter the browser.</p></div></section>:<div className="vision-grid"><section className="panel"><div className="panel-title"><div><span className="eyebrow">DURABLE PRODUCTION QUEUE</span><h3>{view}</h3></div><span className="live"><i/>{identity.isBuilder?'Builder':'Supabase'}</span></div>{jobs.map(j=><button className={active?.id===j.id?'vision-job active':'vision-job'} onClick={()=>setActiveId(j.id)} key={j.id}><div><b>{j.project_title}</b><small>{j.target_platform} · {j.scene_count} scenes</small></div><span>{j.status.replaceAll('_',' ')}</span></button>)}</section><section className="panel"><div className="panel-title"><div><span className="eyebrow">STORYBOARD & QC</span><h3>{active?.project_title||'Select a production'}</h3></div>{active&&<span className="source">{active.approval_state}</span>}</div>{active&&<p className="vision-concept">{active.concept}</p>}<div className="scene-list">{activeScenes.map(s=><article key={s.id}><span>{String(s.scene_index).padStart(2,'0')}</span><div><b>{s.scene_id}</b><p>{s.prompt}</p><small>Prompt v{s.prompt_version} · {s.status} · QC {s.qc_state}</small></div></article>)}{active&&!activeScenes.length&&<div className="land-empty"><Sparkles/><b>Scene planning awaits orchestration</b><p>The minute-based worker advances one durable phase per run after approval.</p></div>}</div></section></div>}
 {notice&&<div className="land-notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}</div>
}
