import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import AuthGate from './components/AuthGate';
import GlobalNavigation from './components/GlobalNavigation';
import './styles.css';
import './workspace.css';
import './vision.css';
import './grantos.css';
import './thelma.css';
import './cmgio.css';
import './fabric.css';
import './auth.css';
import './master.css';
import './theme.css';
import './product-ui.css';
import './analyst.css';
createRoot(document.getElementById('root')!).render(<StrictMode><AuthGate><GlobalNavigation><App /></GlobalNavigation></AuthGate></StrictMode>);
