create table if not exists public.workspace_jobs(
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.ceo_organizations(id) on delete cascade,
  source_system text not null,
  source_workspace text not null,
  return_workspace text not null,
  requested_by uuid not null references auth.users(id),
  title text not null,
  request_payload jsonb not null default '{}'::jsonb,
  assigned_agent text,
  orchestration_command_id uuid references public.orchestration_commands(id) on delete set null,
  status text not null default 'requested' check(status in ('requested','working','review','returned','rejected','failed')),
  result_reference jsonb,
  review_state text not null default 'pending' check(review_state in ('pending','approved','rejected','changes_requested')),
  reviewed_by uuid references auth.users(id),
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists workspace_jobs_org_status_idx
  on public.workspace_jobs(organization_id,status,created_at desc);
create index if not exists workspace_jobs_return_workspace_idx
  on public.workspace_jobs(organization_id,return_workspace,status,created_at desc);
create index if not exists workspace_jobs_command_idx
  on public.workspace_jobs(orchestration_command_id);

create table if not exists public.workspace_job_events(
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.ceo_organizations(id) on delete cascade,
  job_id uuid not null references public.workspace_jobs(id) on delete cascade,
  event_type text not null,
  from_status text,
  to_status text,
  actor_id uuid references auth.users(id),
  note text,
  evidence jsonb,
  created_at timestamptz not null default now()
);

create index if not exists workspace_job_events_job_idx
  on public.workspace_job_events(organization_id,job_id,created_at);

alter table public.workspace_jobs enable row level security;
alter table public.workspace_job_events enable row level security;

drop policy if exists workspace_jobs_member_select on public.workspace_jobs;
create policy workspace_jobs_member_select
  on public.workspace_jobs for select to authenticated
  using(exists(
    select 1 from public.ceo_organization_memberships m
    where m.organization_id=workspace_jobs.organization_id
      and m.user_id=(select auth.uid())
      and m.status='active'
  ));

drop policy if exists workspace_jobs_member_insert on public.workspace_jobs;
create policy workspace_jobs_member_insert
  on public.workspace_jobs for insert to authenticated
  with check(
    requested_by=(select auth.uid())
    and exists(
      select 1 from public.ceo_organization_memberships m
      where m.organization_id=workspace_jobs.organization_id
        and m.user_id=(select auth.uid())
        and m.status='active'
    )
  );

drop policy if exists workspace_jobs_member_update on public.workspace_jobs;
create policy workspace_jobs_member_update
  on public.workspace_jobs for update to authenticated
  using(exists(
    select 1 from public.ceo_organization_memberships m
    where m.organization_id=workspace_jobs.organization_id
      and m.user_id=(select auth.uid())
      and m.status='active'
  ))
  with check(exists(
    select 1 from public.ceo_organization_memberships m
    where m.organization_id=workspace_jobs.organization_id
      and m.user_id=(select auth.uid())
      and m.status='active'
  ));

drop policy if exists workspace_job_events_member_select on public.workspace_job_events;
create policy workspace_job_events_member_select
  on public.workspace_job_events for select to authenticated
  using(exists(
    select 1 from public.ceo_organization_memberships m
    where m.organization_id=workspace_job_events.organization_id
      and m.user_id=(select auth.uid())
      and m.status='active'
  ));

drop policy if exists workspace_job_events_member_insert on public.workspace_job_events;
create policy workspace_job_events_member_insert
  on public.workspace_job_events for insert to authenticated
  with check(exists(
    select 1 from public.ceo_organization_memberships m
    where m.organization_id=workspace_job_events.organization_id
      and m.user_id=(select auth.uid())
      and m.status='active'
  ));
