-- Section 7: CMGIO and reusable Marketing Automation Platform control plane.
begin;
create table if not exists public.marketing_campaigns(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.ceo_organizations(id) on delete cascade,name text not null,objective text not null,channel text not null,status text not null default 'Bullpen' check(status in('Bullpen','Staging','Active','Paused','Completed','Graveyard')),budget numeric(12,2) not null default 0,spend numeric(12,2) not null default 0,leads integer not null default 0,conversions integer not null default 0,revenue numeric(12,2) not null default 0,risk_level text not null default 'medium' check(risk_level in('low','medium','high','critical')),authorization_state text not null default 'ASK' check(authorization_state in('ASK','AUTHORIZED','REJECTED','EXECUTED','FAILED')),created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.marketing_assets(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.ceo_organizations(id) on delete cascade,campaign_id uuid references public.marketing_campaigns(id) on delete cascade,asset_type text not null,title text not null,production_state text not null default 'planned',source_system text not null default 'MAP',qc_state text not null default 'pending',usage_cost numeric(12,4) not null default 0,created_at timestamptz not null default now());
create table if not exists public.marketing_signals(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.ceo_organizations(id) on delete cascade,signal_type text not null,channel text not null,title text not null,confidence integer not null check(confidence between 0 and 100),recommended_action text not null,status text not null default 'review',detected_at timestamptz not null default now());
create index if not exists marketing_campaigns_org_status_idx on public.marketing_campaigns(organization_id,status,updated_at);create index if not exists marketing_assets_campaign_idx on public.marketing_assets(campaign_id,production_state);create index if not exists marketing_signals_org_idx on public.marketing_signals(organization_id,status,detected_at);
alter table public.marketing_campaigns enable row level security;alter table public.marketing_assets enable row level security;alter table public.marketing_signals enable row level security;
create policy "members read marketing campaigns" on public.marketing_campaigns for select to authenticated using(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=marketing_campaigns.organization_id and m.user_id=(select auth.uid())and m.status='active'));
create policy "operators create marketing campaigns" on public.marketing_campaigns for insert to authenticated with check(authorization_state='ASK'and exists(select 1 from public.ceo_organization_memberships m where m.organization_id=marketing_campaigns.organization_id and m.user_id=(select auth.uid())and m.status='active'and m.role in('architect','ceo','operator')));
create policy "architect governs marketing campaigns" on public.marketing_campaigns for update to authenticated using(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=marketing_campaigns.organization_id and m.user_id=(select auth.uid())and m.status='active'and(m.role='architect'or(m.role in('ceo','delegated_approver','operator')and marketing_campaigns.risk_level not in('high','critical')))))with check(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=marketing_campaigns.organization_id and m.user_id=(select auth.uid())and m.status='active'and(m.role='architect'or(m.role in('ceo','delegated_approver','operator')and marketing_campaigns.risk_level not in('high','critical')))));
create policy "members read marketing assets" on public.marketing_assets for select to authenticated using(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=marketing_assets.organization_id and m.user_id=(select auth.uid())and m.status='active'));
create policy "operators manage marketing assets" on public.marketing_assets for all to authenticated using(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=marketing_assets.organization_id and m.user_id=(select auth.uid())and m.status='active'and m.role in('architect','ceo','operator')))with check(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=marketing_assets.organization_id and m.user_id=(select auth.uid())and m.status='active'and m.role in('architect','ceo','operator')));
create policy "members read marketing signals" on public.marketing_signals for select to authenticated using(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=marketing_signals.organization_id and m.user_id=(select auth.uid())and m.status='active'));
create policy "operators manage marketing signals" on public.marketing_signals for all to authenticated using(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=marketing_signals.organization_id and m.user_id=(select auth.uid())and m.status='active'and m.role in('architect','ceo','operator')))with check(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=marketing_signals.organization_id and m.user_id=(select auth.uid())and m.status='active'and m.role in('architect','ceo','operator')));
with o as(select id,created_by from public.ceo_organizations where slug='estiban-creations') insert into public.marketing_campaigns(organization_id,name,objective,channel,status,budget,spend,leads,conversions,revenue,risk_level,authorization_state,created_by) select o.id,x.name,x.objective,x.channel,x.status,x.budget,x.spend,x.leads,x.conversions,x.revenue,x.risk,'ASK',o.created_by from o cross join(values('Florida Land Opportunity Engine','Generate qualified property leads','Meta + Google','Staging',8500,2140,184,13,54230,'high'),('GrantOS Authority Campaign','Build funding-services demand','LinkedIn + Email','Bullpen',3200,420,61,4,12500,'medium'),('Reunion Story Launch','Drive registration and engagement','YouTube + Social','Active',2400,1080,327,48,18600,'medium'))x(name,objective,channel,status,budget,spend,leads,conversions,revenue,risk) where not exists(select 1 from public.marketing_campaigns c where c.organization_id=o.id and c.name=x.name);
with o as(select id from public.ceo_organizations where slug='estiban-creations') insert into public.marketing_signals(organization_id,signal_type,channel,title,confidence,recommended_action,status) select o.id,x.* from o cross join(values('trend','Pinterest','Florida land-search velocity rising',91,'Increase property creative tests','review'),('performance','YouTube','Reunion story completion rate above benchmark',88,'Extend winning narrative format','review'),('cost','Meta','Lead cost increased 14 percent',84,'Hold scale and test audience split','review'))x(signal_type,channel,title,confidence,recommended_action,status) where not exists(select 1 from public.marketing_signals s where s.organization_id=o.id and s.title=x.title);
insert into public.ceo_system_status(organization_id,system_id,system_name,lifecycle_state,health_state,progress_percent,source_system,source_updated_at,blocker_count,qc_state,summary) select o.id,'SYS-CMGIO-001','CMGIO / MAP','mvp','healthy',86,'CMGIO',now(),1,'passed','Campaign intake, performance read models, reusable MAP capabilities, signals, usage and governed approval are active. External channel adapters remain manual-pilot until the API run.' from public.ceo_organizations o where o.slug='estiban-creations' on conflict(organization_id,system_id)do update set lifecycle_state=excluded.lifecycle_state,health_state=excluded.health_state,progress_percent=excluded.progress_percent,source_system=excluded.source_system,source_updated_at=excluded.source_updated_at,blocker_count=excluded.blocker_count,qc_state=excluded.qc_state,summary=excluded.summary,updated_at=now();
commit;
