-- Resolve EC Fabric advisor findings without weakening tenant isolation.
begin;
create index if not exists ec_jobs_requested_by_idx on public.ec_integration_jobs(requested_by);
create index if not exists ec_job_events_job_id_idx on public.ec_job_events(job_id);
create index if not exists ec_dead_letters_org_idx on public.ec_dead_letters(organization_id);
drop policy if exists "architect manages ec connectors" on public.ec_connectors;
create policy "architect inserts ec connectors" on public.ec_connectors for insert to authenticated with check(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=ec_connectors.organization_id and m.user_id=(select auth.uid())and m.status='active'and m.role='architect'));
create policy "architect updates ec connectors" on public.ec_connectors for update to authenticated using(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=ec_connectors.organization_id and m.user_id=(select auth.uid())and m.status='active'and m.role='architect'))with check(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=ec_connectors.organization_id and m.user_id=(select auth.uid())and m.status='active'and m.role='architect'));
drop policy if exists "architect manages ec workflows" on public.ec_workflows;
create policy "architect inserts ec workflows" on public.ec_workflows for insert to authenticated with check(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=ec_workflows.organization_id and m.user_id=(select auth.uid())and m.status='active'and m.role='architect'));
create policy "architect updates ec workflows" on public.ec_workflows for update to authenticated using(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=ec_workflows.organization_id and m.user_id=(select auth.uid())and m.status='active'and m.role='architect'))with check(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=ec_workflows.organization_id and m.user_id=(select auth.uid())and m.status='active'and m.role='architect'));
drop policy if exists "architect manages ec bindings" on public.ec_module_bindings;
create policy "architect inserts ec bindings" on public.ec_module_bindings for insert to authenticated with check(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=ec_module_bindings.organization_id and m.user_id=(select auth.uid())and m.status='active'and m.role='architect'));
create policy "architect updates ec bindings" on public.ec_module_bindings for update to authenticated using(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=ec_module_bindings.organization_id and m.user_id=(select auth.uid())and m.status='active'and m.role='architect'))with check(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=ec_module_bindings.organization_id and m.user_id=(select auth.uid())and m.status='active'and m.role='architect'));
drop policy if exists "architect manages ec dead letters" on public.ec_dead_letters;
create policy "architect inserts ec dead letters" on public.ec_dead_letters for insert to authenticated with check(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=ec_dead_letters.organization_id and m.user_id=(select auth.uid())and m.status='active'and m.role='architect'));
create policy "architect updates ec dead letters" on public.ec_dead_letters for update to authenticated using(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=ec_dead_letters.organization_id and m.user_id=(select auth.uid())and m.status='active'and m.role='architect'))with check(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=ec_dead_letters.organization_id and m.user_id=(select auth.uid())and m.status='active'and m.role='architect'));
commit;
