-- Section 8: owned EC Integration Fabric; no paid workflow runtime required.
begin;
create table if not exists public.ec_connectors(
 organization_id uuid not null references public.ceo_organizations(id) on delete cascade,
 connector_key text not null,display_name text not null,category text not null,
 connection_state text not null default 'staged' check(connection_state in('active','staged','deferred','degraded','disabled')),
 transport text not null,capabilities jsonb not null default '[]',credential_mode text not null default 'not_configured',
 last_health_at timestamptz,last_error text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 primary key(organization_id,connector_key));
create table if not exists public.ec_workflows(
 organization_id uuid not null references public.ceo_organizations(id) on delete cascade,
 workflow_key text not null,display_name text not null,owning_system text not null,trigger_type text not null,
 execution_mode text not null default 'manual_pilot' check(execution_mode in('internal','manual_pilot','external_authorized')),
 risk_level text not null default 'medium' check(risk_level in('low','medium','high','critical')),
 max_retries integer not null default 3,enabled boolean not null default true,steps jsonb not null default '[]',updated_at timestamptz not null default now(),
 primary key(organization_id,workflow_key));
create table if not exists public.ec_module_bindings(
 organization_id uuid not null references public.ceo_organizations(id) on delete cascade,module_key text not null,
 adapter_key text not null default 'internal.read_model',binding_state text not null default 'active' check(binding_state in('active','staged','blocked','disabled')),
 read_authority boolean not null default true,write_authority boolean not null default false,updated_at timestamptz not null default now(),
 primary key(organization_id,module_key));
create table if not exists public.ec_integration_jobs(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.ceo_organizations(id) on delete cascade,
 correlation_id uuid not null default gen_random_uuid(),causation_id uuid,idempotency_key text not null,module_key text not null,
 workflow_key text not null,target_connector text,requested_by uuid references auth.users(id),payload jsonb not null default '{}',
 risk_level text not null default 'medium' check(risk_level in('low','medium','high','critical')),
 authorization_state text not null default 'ASK' check(authorization_state in('ASK','AUTHORIZED','REJECTED','EXECUTED','FAILED')),
 execution_state text not null default 'queued' check(execution_state in('queued','claimed','running','completed','retry_wait','dead_letter','cancelled')),
 retry_count integer not null default 0,max_retries integer not null default 3,next_attempt_at timestamptz,last_error text,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,idempotency_key));
create table if not exists public.ec_job_events(
 id bigint generated always as identity primary key,organization_id uuid not null references public.ceo_organizations(id) on delete cascade,
 job_id uuid not null references public.ec_integration_jobs(id) on delete cascade,event_type text not null,actor_type text not null,
 actor_id text,details jsonb not null default '{}',created_at timestamptz not null default now());
create table if not exists public.ec_dead_letters(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.ceo_organizations(id) on delete cascade,
 job_id uuid not null references public.ec_integration_jobs(id) on delete cascade,reason text not null,payload_snapshot jsonb not null default '{}',
 remediation_state text not null default 'open' check(remediation_state in('open','investigating','requeued','resolved','accepted')),
 created_at timestamptz not null default now(),resolved_at timestamptz,unique(job_id));
create index if not exists ec_jobs_queue_idx on public.ec_integration_jobs(organization_id,execution_state,next_attempt_at,created_at);
create index if not exists ec_job_events_job_idx on public.ec_job_events(organization_id,job_id,created_at);
alter table public.ec_connectors enable row level security;alter table public.ec_workflows enable row level security;alter table public.ec_module_bindings enable row level security;alter table public.ec_integration_jobs enable row level security;alter table public.ec_job_events enable row level security;alter table public.ec_dead_letters enable row level security;
create policy "members read ec connectors" on public.ec_connectors for select to authenticated using(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=ec_connectors.organization_id and m.user_id=(select auth.uid())and m.status='active'));
create policy "architect manages ec connectors" on public.ec_connectors for all to authenticated using(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=ec_connectors.organization_id and m.user_id=(select auth.uid())and m.status='active'and m.role='architect'))with check(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=ec_connectors.organization_id and m.user_id=(select auth.uid())and m.status='active'and m.role='architect'));
create policy "members read ec workflows" on public.ec_workflows for select to authenticated using(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=ec_workflows.organization_id and m.user_id=(select auth.uid())and m.status='active'));
create policy "architect manages ec workflows" on public.ec_workflows for all to authenticated using(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=ec_workflows.organization_id and m.user_id=(select auth.uid())and m.status='active'and m.role='architect'))with check(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=ec_workflows.organization_id and m.user_id=(select auth.uid())and m.status='active'and m.role='architect'));
create policy "members read ec bindings" on public.ec_module_bindings for select to authenticated using(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=ec_module_bindings.organization_id and m.user_id=(select auth.uid())and m.status='active'));
create policy "architect manages ec bindings" on public.ec_module_bindings for all to authenticated using(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=ec_module_bindings.organization_id and m.user_id=(select auth.uid())and m.status='active'and m.role='architect'))with check(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=ec_module_bindings.organization_id and m.user_id=(select auth.uid())and m.status='active'and m.role='architect'));
create policy "members read ec jobs" on public.ec_integration_jobs for select to authenticated using(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=ec_integration_jobs.organization_id and m.user_id=(select auth.uid())and m.status='active'));
create policy "operators request ec jobs" on public.ec_integration_jobs for insert to authenticated with check(requested_by=(select auth.uid())and authorization_state='ASK'and execution_state='queued'and exists(select 1 from public.ceo_organization_memberships m where m.organization_id=ec_integration_jobs.organization_id and m.user_id=(select auth.uid())and m.status='active'and m.role in('architect','ceo','operator')));
create policy "architect governs ec jobs" on public.ec_integration_jobs for update to authenticated using(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=ec_integration_jobs.organization_id and m.user_id=(select auth.uid())and m.status='active'and(m.role='architect'or(m.role='delegated_approver'and ec_integration_jobs.risk_level not in('high','critical')))))with check(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=ec_integration_jobs.organization_id and m.user_id=(select auth.uid())and m.status='active'and(m.role='architect'or(m.role='delegated_approver'and ec_integration_jobs.risk_level not in('high','critical')))));
create policy "members read ec job events" on public.ec_job_events for select to authenticated using(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=ec_job_events.organization_id and m.user_id=(select auth.uid())and m.status='active'));
create policy "operators append ec job events" on public.ec_job_events for insert to authenticated with check(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=ec_job_events.organization_id and m.user_id=(select auth.uid())and m.status='active'and m.role in('architect','ceo','operator','auditor')));
create policy "members read ec dead letters" on public.ec_dead_letters for select to authenticated using(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=ec_dead_letters.organization_id and m.user_id=(select auth.uid())and m.status='active'));
create policy "architect manages ec dead letters" on public.ec_dead_letters for all to authenticated using(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=ec_dead_letters.organization_id and m.user_id=(select auth.uid())and m.status='active'and m.role='architect'))with check(exists(select 1 from public.ceo_organization_memberships m where m.organization_id=ec_dead_letters.organization_id and m.user_id=(select auth.uid())and m.status='active'and m.role='architect'));
grant select,insert,update on public.ec_connectors,public.ec_workflows,public.ec_module_bindings,public.ec_integration_jobs,public.ec_job_events,public.ec_dead_letters to authenticated;
grant usage,select on sequence public.ec_job_events_id_seq to authenticated;
with o as(select id from public.ceo_organizations where slug='estiban-creations') insert into public.ec_connectors(organization_id,connector_key,display_name,category,connection_state,transport,capabilities,credential_mode,last_health_at) select o.id,x.key,x.name,x.category,x.state,x.transport,x.capabilities::jsonb,x.credential,case when x.state='active'then now()else null end from o cross join(values('supabase','Supabase','data','active','native','["database","auth","realtime","storage"]','publishable_key'),('vercel','Vercel','deployment','active','https','["deploy","logs","health"]','oauth'),('github','GitHub','source_control','active','https','["repos","pull_requests","commits"]','oauth'),('google_drive','Google Drive','documents','deferred','https','["files","docs","sheets"]','not_configured'),('canva','Canva','creative','staged','https','["designs","templates","exports"]','not_configured'),('ads','Ads Manager','marketing','staged','https','["campaigns","performance","audiences"]','not_configured'),('email','Email','communications','staged','https','["send","receive","status"]','not_configured'),('base44','Base44','application_runtime','deferred','https','["apps","resources","deployments"]','not_configured'))x(key,name,category,state,transport,capabilities,credential) on conflict(organization_id,connector_key)do update set connection_state=excluded.connection_state,capabilities=excluded.capabilities,credential_mode=excluded.credential_mode,updated_at=now();
with o as(select id from public.ceo_organizations where slug='estiban-creations') insert into public.ec_workflows(organization_id,workflow_key,display_name,owning_system,trigger_type,execution_mode,risk_level,steps) select o.id,x.key,x.name,x.owner,x.trigger,x.mode,x.risk,x.steps::jsonb from o cross join(values('system-health-pulse','System health pulse','THELMA','schedule','internal','low','["collect","validate","record","report"]'),('dashboard-memory-capture','Dashboard memory capture','CEO Dashboard','event','internal','medium','["validate","classify","store","audit"]'),('marketing-campaign-intake','Marketing campaign intake','CMGIO','user','manual_pilot','high','["ingest","verify","check","ask","stage"]'),('land-opportunity-score','Land opportunity score','LandWeaver','user','internal','medium','["ingest","normalize","score","brief"]'),('vision-production-intake','Vision production intake','VisionWeaver','user','manual_pilot','medium','["brief","plan","assemble","qc"]'),('grant-deadline-watch','Grant deadline watch','GrantOS','schedule','internal','low','["scan","rank","alert","record"]'))x(key,name,owner,trigger,mode,risk,steps) on conflict(organization_id,workflow_key)do update set execution_mode=excluded.execution_mode,risk_level=excluded.risk_level,steps=excluded.steps,updated_at=now();
with o as(select id from public.ceo_organizations where slug='estiban-creations'),mods(module_key)as(values('Dashboard'),('AI Mastery'),('Agent Hub'),('Leads Pipeline'),('Content Engine'),('Social Media'),('Trends'),('Communications'),('CRM'),('Products'),('Finance'),('System Audit'),('Certificates'),('Settings'),('Team Overview'),('Video Storyboard'),('Social Analytics'),('Lead Scoring Rules'),('API Integration'),('Revenue Report'),('Agent Logs'),('Media Library'),('Multi-Account Posting'),('Trend Signal Alerts'),('Help Center')) insert into public.ec_module_bindings(organization_id,module_key) select o.id,m.module_key from o cross join mods m on conflict(organization_id,module_key)do update set binding_state='active',read_authority=true,updated_at=now();
update public.orchestration_runs set engine='EC Fabric' where engine='n8n'and workflow_key in('daily-executive-briefing','system-health-pulse','visionweaver-provider-check');
update public.ceo_system_status set system_name='THELMA / EC Fabric',summary='Governed command queue, agent registry, owned EC Fabric telemetry and white-blood-cell incident model are active without a paid workflow runtime.',blocker_count=0,progress_percent=94 where system_id='SYS-THELMA-001';
insert into public.ceo_system_status(organization_id,system_id,system_name,lifecycle_state,health_state,progress_percent,source_system,source_updated_at,blocker_count,qc_state,summary) select o.id,'SYS-FABRIC-001','EC Integration Fabric','mvp','healthy',90,'EC Fabric',now(),1,'passed','Owned connectors, module bindings, governed jobs, retries, dead letters, audit events and human override are active. Provider credentials remain deferred to the API-key run.' from public.ceo_organizations o where o.slug='estiban-creations' on conflict(organization_id,system_id)do update set lifecycle_state=excluded.lifecycle_state,health_state=excluded.health_state,progress_percent=excluded.progress_percent,source_system=excluded.source_system,source_updated_at=excluded.source_updated_at,blocker_count=excluded.blocker_count,qc_state=excluded.qc_state,summary=excluded.summary,updated_at=now();
commit;
